### ISSUE TITLE
Flycheck errors disapear after changing a buffer in Python

### ISSUE THREAD

**Issue by ashkan-leo** [emacs-lsp/lsp-mode#1476] opened 2020-03-06 01:07 UTC
**Describe the bug**
When I open a Python file that contains some linting errors, flycheck correctly marks the errors/warnings. Then, I randomly change the file and save it. flycheck stops highlighting all the errors and warnings.
When I run flycheck-compile I see all the errors in a separate buffer. Also flycheck-verify-setup says everything is okay.
Also, flycheck-buffer doesn't seem to have any effect.
I need to restart Emacs to see the errors again.

**To Reproduce**
Open a python file with linting error. Then, do some random change to the file and save the buffer. Observe that the errors disappear. 

**Expected behavior**
The Flycheck errors should not disappear.

**Which Language Server did you use**
lsp-python.  I have used Microsoft language server protocol as well as Pyls.

**OS**
Mac OS Catalina

**Comment by brotzeit** [comment] 2020-03-06 09:41
Did it work before ?

**Comment by yyoncho** [comment] 2020-03-06 13:10
Also, does it reproduce with lsp-start-plain.el?

**Comment by ashkan-leo** [comment] 2020-03-06 19:36
I'm using Doom Emacs. I tried with `lsp-start-plain.el`, but it will take me some time to figure out how to start the language server, etc. Right now, I can't even start the server using it.
@brotzeit I have recently started to use lsp-mode. So, I can't tell if it worked before -- migrating from Pycharm :)

**Comment by yyoncho** [comment] 2020-03-06 20:51
@sebastiansturm willing to take a look? I know that you recently updated doom's lsp layer?

@ashkan-leo to reproduce the issue do: edit the list of packages to install in lsp-start-plain.el and add flycheck to in. Then when you open the file(you could pass it to the command line) do `M-x lsp`.

I am unable to reproduce it following these steps so it seems like it is either doom configuration issue or you have some stale packages locally.

**Comment by ashkan-leo** [comment] 2020-03-06 22:17
@yyoncho Thanks for your instruction.
I can't reproduce this error using lsp-start-plain.el.
It seems it's a Doom specific thing. Any help on how to pin down this issue would be appreciated though.

**Comment by sebastiansturm** [comment] 2020-03-06 23:20
can't reproduce that behavior, though I did introduce a bug with my lsp PR to doom-emacs that would break flycheck on Emacs < 27 (https://github.com/hlissner/doom-emacs/issues/2636). That bug has since been fixed and should look different from what you report (no error highlighting at all, not even during the first run). Still, could you verify that you're using an up-to-date version of doom and maybe post the output of `flycheck-verify-setup`?

**Comment by ashkan-leo** [comment] 2020-03-07 00:22
I'm using the latest Doom Emacs. I just updated it to make sure nothing is missing.
Here is the output of `flycheck-verify-setup`:

```
Syntax checkers for buffer test.py in python-mode:

First checker to run:

  lsp (explicitly selected)
    - may enable: yes
    - predicate:  t

Checkers that could run if selected:

  python-flake8  select
    - may enable:         yes
    - executable:         Found at /usr/local/bin/flake8
    - configuration file: Not found
    - next checkers:      python-pylint, python-mypy

  python-pylint  select
    - may enable:         yes
    - executable:         Found at /usr/local/bin/pylint
    - configuration file: Not found
    - next checkers:      python-mypy

  python-pycompile  select
    - may enable:    yes
    - executable:    Found at /usr/bin/python3
    - next checkers: python-mypy

  python-mypy  select
    - may enable:         yes
    - predicate:          t
    - executable:         Found at /usr/local/bin/mypy
    - configuration file: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    26.3
System:           x86_64-apple-darwin19.0.0
Window system:    mac
```

Also I attached two screenshots showing the flycheck output before and after save on a sample source code that I'm also attaching -- I appended `.txt` to the source because I can't upload `.py` files here for some reason.
[test.py.txt](https://github.com/emacs-lsp/lsp-mode/files/4301160/test.py.txt)

<img width="1680" alt="Screen Shot 2020-03-06 at 6 15 30 PM" src="https://user-images.githubusercontent.com/10341965/76132154-14375780-5fd7-11ea-85a0-5f399aa0041b.png">
<img width="1680" alt="Screen Shot 2020-03-06 at 6 16 08 PM" src="https://user-images.githubusercontent.com/10341965/76132155-14375780-5fd7-11ea-970c-a60ffc44254f.png">

**Comment by yyoncho** [comment] 2020-03-07 07:31
AFACS the errors on the first screenshot are not from lsp. So my guess is that after save it runs only the lsp checker and the errors are deleted since there are no errors from lsp. I am not familiar with doom and flycheck internals.

**Comment by sebastiansturm** [comment] 2020-03-07 13:59
I guess that since doom's `lsp` module only sets up `flycheck-lsp` the first time `lsp-mode` is invoked, `python-pylint` gets a chance to run once. Though that behavior shouldn't have changed with my doom/lsp PR; did you previously use `lsp-mode` but not `lsp-ui` (because lsp flycheck support used to be bound to `lsp-ui-mode-hook`)?
Getting both lsp and pylint to run should be possible by adding to `lsp`'s `next-checker` property,
```
(flycheck-add-next-checker 'lsp '(warning . python-pylint))
```
I don't like that approach though; it's good for most flycheck checkers but with `'lsp` being mode-agnostic you'd quickly assemble a long list of next-checkers for different modes, most of which will then be disabled by flycheck. It does work but it's not pretty. @yyoncho: is there a recommendation on how to do checker chaining with `lsp-flycheck`?

**Comment by yyoncho** [comment] 2020-03-07 14:10
sebastiansturm writes:

> I don't like that approach though; it's good for most flycheck checkers but with `'lsp` being mode-agnostic you'd quickly assemble a long list of next-checkers for different modes, most of which will then be disabled by flycheck. It does work but it's not pretty. @yyoncho: is there a recommendation on how to do checker chaining with `lsp-flycheck`?

I haven't researched the topic, but indeed, we have to provide a recipe
for this scenario. Why don't you like this approach appart from being
lsp-mode centric it looks fine to me?

**Comment by sebastiansturm** [comment] 2020-03-07 14:38
I think typically you'd add mode-specific next checkers to another mode-specific checker, so perhaps `python-pylint` might have `python-pylint` and `pyflakes` set as its next checkers. With the `lsp` checker being active in all sorts of different modes though, I might want a different next checker for every language I'm using lsp with, so the list of next checkers attached to `lsp` might quickly balloon to a dozen unrelated entries or so.
Since flycheck will disable all checkers that don't apply to the current mode I think this will work in practice; it just seems a bit messy to me. But on the other hand it doesn't require any extra effort on the lsp side, so if you think that approach is fine, I'll gladly adjust my point of view (also, I'm not sure what else to do; adding explicit mode restrictions to flycheck's `next-checker` entries would be redundant and hence even worse)

**Comment by yyoncho** [comment] 2020-03-07 14:58
sebastiansturm writes:

> I think typically you'd add mode-specific next checkers to another mode-specific checker, so perhaps `python-pylint` might have `python-pylint` and `pyflakes` set as its next checkers. With the `lsp` checker being active in all sorts of different modes though, I might want a different next checker for every language I'm using lsp with, so the list of next checkers attached to `lsp` might quickly balloon to a dozen unrelated entries or so.
> Since flycheck will disable all checkers that don't apply to the current mode I think this will work in practice; it just seems a bit messy to me. But on the other hand it doesn't require any extra effort on the lsp side, so if you think that approach is fine, I'll gladly adjust my point of view (also, I'm not sure what else to do; adding explicit mode restrictions to flycheck's `next-checker` entries would be redundant and hence even worse)

I understood - the issue seems to be caused by the fact that flycheck is
not designed to support checkers like lsp that handle multiple modes.
And also the api for chaining checkers is a bit odd and limiting. In
general, we may fix that by generating lsp checker per
major-mode/language, changing these lines:

>  (lsp-flycheck-add-mode major-mode)
>  (add-to-list 'flycheck-checkers 'lsp)

IMO we can keep it as it is and provide a fix in case there is a
scenario we cannot handle. But of course if you want to provide PR I am
fine with that.

**Comment by ashkan-leo** [comment] 2020-03-07 23:02
> did you previously use `lsp-mode` but not `lsp-ui` (because lsp flycheck support used to be bound to `lsp-ui-mode-hook`)?

I used both `lsp-mode` and `lsp-ui` before. However, I recently started using Emacs for Python. I have used lsp for Scala a lot, but I noticed the only flycheck source for that comes from lsp. So, my observation with that doesn't apply here.


> `(flycheck-add-next-checker 'lsp '(warning . python-pylint))`

I can confirm that this actually solves the problem. After saving the buffer, if you wait a while the linting errors reappear again. However, I didn't notice this delay when using `lsp-start-plain.el`.

**Comment by 3lcarry** [comment] 2020-06-13 06:27
Hi,

I have a similar error, flycheck doesn't show any error (from the beginning), using the suggested solution `(flycheck-add-next-checker 'lsp '(warning . python-pylint))` solves my problem partially. The errors are display on the first line:

![image](https://user-images.githubusercontent.com/1786817/84561568-5670e300-ad02-11ea-911f-13a0d5a94e69.png)

On the logs I can see the following warning:
> 2020-06-12 23:24:42,443 UTC - WARNING - pyls_jsonrpc.endpoint - Received cancel notification for unknown message id 16

**Comment by yyoncho** [comment] 2020-06-13 08:40
Closing the issue, I think that this should be solved by the recent flycheck rewrite. The flycheck chaining is tracked by https://github.com/flycheck/flycheck/issues/1762 .

**Closed by yyoncho** 2020-06-13 08:40 UTC
Labels: flycheck
