### ISSUE TITLE
ccls: "expected array for /context/diagnostics[0]/relatedInformation"

### ISSUE THREAD

**Issue by hpdeifel** [emacs-lsp/lsp-mode#690] opened 2019-03-04 14:26 UTC
**Describe the bug**
ccls complains that `/context/diagnostics[0]/relatedInformation` in the `document/codeAction` request is not an array. ccls originally sends `[]` in the diagnostics and this somehow gets transformed to `null` when echoed back to the server.

**To Reproduce**
Go to a line with diagnostics and code actions in a ccls-project buffer.

**Which Language Server did you use**
ccls master from yesterday.

**OS**
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-03-04

**IO**

```
>>> ccls:7828(async)
Content-Length: 2888

{
  "jsonrpc": "2.0",
  "method": "textDocument/codeAction",
  "params": {
    "textDocument": {
      "uri": "HIDDEN"
    },
    "range": {
      "start": {
        "line": 96,
        "character": 0
      },
      "end": {
        "line": 96,
        "character": 66
      }
    },
    "context": {
      "diagnostics": [
        {
          "relatedInformation": null,
          "message": "use of undeclared identifier 'td'",
          "source": "ccls",
          "code": 2,
          "severity": 1,
          "range": {
            "end": {
              "character": 2,
              "line": 96
            },
            "start": {
              "character": 0,
              "line": 96
            }
          }
        },
        {
          "relatedInformation": null,
          "message": "HIDDEN",
          "source": "ccls",
          "code": 2,
          "severity": 1,
          "range": {
            "end": {
              "character": 37,
              "line": 96
            },
            "start": {
              "character": 31,
              "line": 96
            }
          }
        },
        ...
      ]
    }
  },
  "id": 2409
}

<<<< ccls:7828
{
  "jsonrpc": "2.0",
  "id": 2409,
  "error": {
    "code": -32602,
    "message": "invalid params of textDocument/codeAction: expected array for /context/diagnostics[0]/relatedInformation"
  }
}
```

And the original diagnostics look like so:

```
<<<< ccls:7828
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "HIDDEN",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 84,
            "character": 1
          },
          "end": {
            "line": 84,
            "character": 12
          }
        },
        "severity": 1,
        "code": 2,
        "source": "ccls",
        "message": "HIDDEN",
        "relatedInformation": []
      },
      {
        "range": {
          "start": {
            "line": 96,
            "character": 0
          },
          "end": {
            "line": 96,
            "character": 2
          }
        },
        "severity": 1,
        "code": 2,
        "source": "ccls",
        "message": "use of undeclared identifier 'td'",
        "relatedInformation": []
      },
      ...
    ]
  }
}

```

**Comment by yyoncho** [comment] 2019-03-04 15:53
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/395 will be fixed with https://github.com/emacs-lsp/lsp-mode/issues/210

**Closed by yyoncho** 2019-03-04 15:53 UTC

**Comment by yyoncho** [comment] 2019-03-04 18:03
@hpdeifel PR at https://github.com/emacs-lsp/lsp-mode/pull/691 . I will appreciate help with testing the PR .
