### ISSUE TITLE
Can't recover after lsp stdio client dies

### ISSUE THREAD

**Issue by nelhage-stripe** [emacs-lsp/lsp-mode#465] opened 2018-11-01 01:03 UTC
**Describe the bug**
If an LSP stdio client dies, there seems to be no way to recover and restart+reconnect to the client without manual fiddling.

**To Reproduce**
Define an LSP stdio client. Start that LSP mode in a buffer. Kill the client from outside of emacs.

**Expected behavior**
I expect `lsp-mode` to respawn the server and continue executing.

Barring that, I expect `lsp-restart-workspace` to allow me to explicitly do so.

Instead, the behavior I see is that `lsp--cur-workspace` is set to `nil`, which breaks all LSP functionality, including `lsp-restart-workspace`, but `lsp-mode` is kept enabled, which prevents `lsp-MODE-enable` from functioning. In addition, functions like `lsp--xref-backend` fail unceremoniously with type errors.

**Which Language Server did you use**
I've been using a stdio client to `sorbet`, an internal Ruby LSP client. I've defined it as

```
(lsp-define-stdio-client
   lsp-sorbet-mode
   "Ruby"
   (lsp-make-traverser "Gemfile")
   '("pay" "exec" "scripts/bin/typecheck" "--lsp"))
```

**OS**
MacOS 10.13.6
Emacs 26.1

**Comment by yyoncho** [comment] 2018-11-01 04:44
Duplicate of #285 . I am working on a solution. For now the workaround is to close the buffers related to the mode and reopen them or go to each one and call `lsp-*-enable`.

**Closed by yyoncho** 2018-11-01 04:44 UTC

**Comment by nelhage-stripe** [comment] 2018-11-01 15:50
I'll follow #285, thanks. I do want to call out that  even an explicit `lsp-*-enable` doesn't work, because `lsp-mode` is left enabled and so it no-ops out. An interim fix that lets that work would be an improvement, although I can probably hack something together locally.
