### ISSUE TITLE
lsp-rust diagnostic is not updated when using lsp-use-plists

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#1807] opened 2020-06-16 00:00 UTC
With `lsp-use-plists` enabled, the diagnostic information for `lsp-rust` is not updated.
Sample rust file:
``` rust
fn main() {
    let foobar = 1;
    let Foobar: i32 = 2;
    // foobar = 2;
}
```

After removing the comment (`//`), the diagnostic is not updated

**Comment by yyoncho** [comment] 2020-06-17 17:52
I will take a look.

**Comment by yyoncho** [comment] 2020-06-17 19:35
AFACS the issue is dup of https://github.com/emacs-lsp/lsp-mode/issues/1792 . Rust analyzer does not re-report errors until the file is saved and the errors stay like that. @brotzeit @flodiebold is this correct?

**Comment by flodiebold** [comment] 2020-06-17 21:16
That's mostly correct (rust-analyzer does provide some errors on the fly, but the compiler is only rerun on save).

**Comment by kiennq** [comment] 2020-06-18 23:29
I do save the file but the diagnostic is not refreshed. Without `lsp-use-plists`, the diagnostics are updated though

**Comment by yyoncho** [comment] 2020-06-19 04:19
The issue here is that plists does not distinguish json's  `{}`, `nil` and `false` and we do not send didSave event. The correct solution here is painful and will be perf hit.

**Comment by kiennq** [comment] 2020-06-19 05:11
It's indeed painful. Is there alternative solution for this?
How about bind `null-object` to `:null`? Will there be perf hit somewhere?

**Comment by yyoncho** [comment] 2020-06-19 05:12
> It's indeed painful. Is there alternative solution for this?
> How about bind `null-object` to `:null`? Will there be perf hit somewhere?

we should bind both nil and false to :nil and :false and eventually fix somehow `if` checks.

**Comment by kiennq** [comment] 2020-06-19 05:16
> we should bind both nil and false to :nil and :false and eventually fix somehow `if` checks.

That will be a big change. On other hand, to have same feature parity with hash table, perhaps only binding `null-object` is enough?
I hope it will just work without more change (maybe change in `lsp-empty?` too).

**Comment by yyoncho** [comment] 2020-06-19 05:17
> > we should bind both nil and false to :nil and :false and eventually fix somehow `if` checks.
> 
> That will be a big change. On other hand, to have same feature parity with hash table, perhaps only binding `null-object` is enough?
> I hope it will just work without more change (maybe change in `lsp-empty?` too).

This is won't fix the issue.

**Comment by kiennq** [comment] 2020-06-19 05:30
Actually when I tried to bind both `null-object` and `false-object` to `:nil` and `:false`, this snippet still return `nil`.

``` elisp
(lsp--read-json "{\"test\": {}}")
(:test nil)
```

**Comment by yyoncho** [comment] 2020-06-19 05:33
Then
```
:false = false
:null = null
nil = {}
```

**Comment by yyoncho** [comment] 2020-06-19 05:34
Not it is:
```
nil = false
nil = null
nil = {}
```

We could also try to replace `{}` in the message with `{"_empty": true}`.

**Comment by yyoncho** [comment] 2020-06-19 18:23
Proposed fix: when calling method callback we could pass the original json message as a dynamic variable. Then in initializing result handler, we will extract the correct using different json deserialization technique. I filed feature request in emacs-devel for providing `:empty-object` param for json serialization but given the fact that emacs 27 is going to be released soon it seems like that it is not going to make it which means we should find a workaround.

**Comment by scturtle** [comment] 2020-06-21 05:07
> It's indeed painful. Is there alternative solution for this?

I just call `flycheck-buffer` manually and repeatedly.

**Comment by kiennq** [comment] 2020-06-21 05:44
> > It's indeed painful. Is there alternative solution for this?
> 
> I just call `flycheck-buffer` manually and repeatedly.

Since the diagnostics are returned from the server, if the server is not updated with `didSave`, then no diagnostic will be updated :(

**Comment by scturtle** [comment] 2020-06-21 05:50
Sorry I misunderstood the issue. I'm not using `lsp-use-plists` but still encountered delay of diagnostics.

Every time I saved, the diagnostics are result of the last time I saved. I'm not sure it's issue of doom-emacs or lsp-mode or rust-analyzer. Does anyone have the same issue?

**Comment by yyoncho** [comment] 2020-06-21 06:04
@scturtle see https://github.com/emacs-lsp/lsp-mode/issues/1807#issuecomment-645629224

**Comment by yyoncho** [comment] 2020-06-21 06:09
@scturtle FYI flycheck-buffer won't trigger anything on the server but it will show the last reported errors. Once the server sends new diagnostics we will show them after some delay.

**Comment by bk138** [comment] 2020-10-04 16:45
> That's mostly correct (rust-analyzer does provide some errors on the fly, but the compiler is only rerun on save).

Just chiming in here as I was switching over from rls to rust-analyzer and was surprised that (some) diagnostics get updated on save only: The only way to get updates-as-you-type would be some save-timer or is there some config setting for this @flodiebold ?

**Comment by flodiebold** [comment] 2020-10-04 19:35
No, there is no config setting for this, it's a technical limitation.

**Closed** 2020-10-25 01:46 UTC
