### ISSUE TITLE
lsp-prefer-capf has no effect?

### ISSUE THREAD

**Issue by haoyuan80s** [emacs-lsp/lsp-mode#1736] opened 2020-05-31 02:14 UTC
Hi,

I use clangd as c's server. `company-capf` can complete the "#inc"

![image](https://user-images.githubusercontent.com/9064146/83342572-ef851000-a2a5-11ea-9fb4-f1619d53bded.png)

But, it is not triggered automatically by lsp-mode/company. I tried `(setq lsp-prefer-capf t)`. Still not working.
My solution is to reorder the company-backends manually, and put company-capf first of the list. What is the correct way to config it in lsp-mode? What is the effect of `(setq lsp-prefer-capf t)`?

**Comment by yyoncho** [comment] 2020-05-31 06:09
We have to figure that out. I think that this is caused by the fact that company has clang backend configured by default. One option is to strip company-clang. We use to set company-capf/lsp as a single backend but we had complaints about overriding the user's configuration. 

cc @dgutov

**Comment by yyoncho** [comment] 2020-05-31 06:10
For now, the following snippet should be sufficient:
``` elisp
(add-hook 'lsp-managed-mode-hook (lambda () (setq-local company-backends '(company-capf))))
```

**Comment by haoyuan80s** [comment] 2020-05-31 06:41
Indeed sufficient. Thanks!

**Comment by yyoncho** [comment] 2020-05-31 06:44
Reopening because we should work OOTB.

**Comment by dgutov** [comment] 2020-05-31 11:40
Why not create a configuration helper? For users to put into their config.

The complaint about `company-capf` is not a new one, and I should probably remove it by default, but this will likewise need documentation, at least with existing users in mind, who kept the default value of `company-backends`.

**Comment by yyoncho** [comment] 2020-05-31 13:35
I just wanted to hear your plans here. We could remove it as part of our autoconfiguration.

**Comment by dgutov** [comment] 2020-05-31 17:41
The plan is to take care of this moderately soon-ish. It's just not at the top of my list, though, and writing documentation is harder than writing code.

I also don't want to simply remove it without prominently documenting how to put it back (and why), because it is a neat small piece of tech, some people actually like it, and it showcases asynchronous backends.

**Comment by yyoncho** [comment] 2020-08-06 14:12
@dgutov - what about putting capf on the first position in default backends
list?

**Comment by dgutov** [comment] 2020-08-07 00:10
@yyoncho Not exactly the first position, but how about this?

https://github.com/company-mode/company-mode/commit/664dd19c2f3d088be3c82bfa3abcc589b491b8f1

**Comment by yyoncho** [comment] 2020-08-07 05:08
> @yyoncho Not exactly the first position, but how about this?
> 
> [company-mode/company-mode@664dd19](https://github.com/company-mode/company-mode/commit/664dd19c2f3d088be3c82bfa3abcc589b491b8f1)

Can we move it in front of nxml and CSS as well - it will cause the same issue there.

**Comment by dgutov** [comment] 2020-08-07 07:00
They're only there in Emacs 25 and older. `lsp-mode` requires 26.1+.

**Comment by yyoncho** [comment] 2020-08-07 07:09
> They're only there in Emacs 25 and older. `lsp-mode` requires 26.1+.

Ah, you are right (my issue was caused by spacemacs overriding capf function itself). Then the fix is fine.

**Comment by yyoncho** [comment] 2020-08-07 16:06
closing since  [company-mode/company-mode@664dd19](https://github.com/company-mode/company-mode/commit/664dd19c2f3d088be3c82bfa3abcc589b491b8f1) should be sufficient.

**Closed** 2020-08-07 16:06 UTC
