### ISSUE TITLE
Add support for Deno's builtin LSP

### ISSUE THREAD

**Issue by XO39** [emacs-lsp/lsp-mode#2545] opened 2021-01-20 07:46 UTC
Can you add support for [Deno's builtin LSP](https://deno.land/manual/getting_started/setup_your_environment#lsp-clients), It's just awful to work with `tide`, and 'lsp-mode' working for everywhere else in Emacs.

**Comment by yyoncho** [comment] 2021-01-20 08:21
duplicate of https://github.com/emacs-lsp/lsp-mode/issues/2235

**Closed by yyoncho** 2021-01-20 08:21 UTC
