### ISSUE TITLE
After update to lsp-mode-20210624.1915 on elpa: File mode specification error: (void-variable lsp-actionscript)

### ISSUE THREAD

**Issue by wgmitchener** [emacs-lsp/lsp-mode#2963] opened 2021-06-27 03:40 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

When I try to open a Haskell file. instead of communicating with the Haskell lsp server, something goes wrong and lsp-mode fails to start. It prints a message

File mode specification error: (void-variable lsp-actionscript)

The problem first appeared today after I updated a bunch of elpa packages.

### Steps to reproduce

I updated to lsp-mode-20210624.1915 using elpa today. Now when I try to open a Haskell source file, it fails and gives the message

File mode specification error: (void-variable lsp-actionscript)

I don't have any actionscript-related packages or settings anywhere that I can see. I don't use actionscript at all.

### Expected behavior

lsp-mode should start.

It was working before I updated lsp-mode packages from elpa.

### Which Language Server did you use?

I'm trying to use lsp-haskell but the problem is in the elpa package

### OS

Linux

### Anything else?

I'm using Fedora 34.

M-x version:

GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-06-13

rpm -q emacs:

emacs-27.2-3.fc34.x86_64

I restored ~/.emacs.d/elpa/lsp-mode-20210518.1256 and ditto for lsp-treemacs, and removed the lsp-mode-202106* folders and restarted emacs. Now emacs opens my Haskell files properly and launches lsp-mode with no error message.

**Comment by jngbng** [comment] 2021-07-06 01:51
I had the same problem. For my case, it has been fixed in lsp-mode-20210705.801 on elpa.

**Comment by husainaloos** [comment] 2021-07-14 18:54
I am having a similar issue when I run `lsp-install-server`. I get

```
 Symbol’s value as variable is void: lsp-actionscript
```

I am using version 20210710.1312 on emacs 27.2.

**Comment by yyoncho** [comment] 2021-07-14 19:07
can you delete lsp-mode, restart emacs and install it again?

**Comment by husainaloos** [comment] 2021-07-15 16:31
> can you delete lsp-mode, restart emacs and install it again?

Indeed that worked. I `package-delete` lsp-mode and then reinstalled it and it worked. I suggest that whoever is running into this problem tries that first.

**Comment by wgmitchener** [comment] 2021-07-23 16:50
I think there may be some kind of collision of packages somewhere. I uninstalled all my lsp-* packages and also company-lsp. I then installed lsp-mode, lsp-haskell, and lsp-ui. Now when I load a .hs file, lsp mode seems to work fine.

It appears that company-lsp has disappeared from elpa. Maybe it's no longer maintained? Maybe something in company-lsp caused the error?

**Comment by yyoncho** [comment] 2021-10-17 20:43
This issue is caused by introducing macros used outside of lsp-mode.el. Deleting lsp-mode + restarting emacs + installing should fix the issue.

**Closed by yyoncho** 2021-10-17 20:43 UTC
Labels: bug
