### ISSUE TITLE
Make it easier to customize lsp-modeline-code-actions-face

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#1944] opened 2020-07-21 17:39 UTC
Currently this is a variable pointing to an existing face `homoglyph`. If I want to customize the appearance of the code action in the modeline, I need to define a new face myself and then assign it to `lsp-modeline-code-actions-face` (right?). Can we instead make `lsp-modeline-code-actions-face` an actual face that just inherits from `homoglyph` so that themes can adjust this face like normal?

Also, homogylph seems like a strange choice for the default face. Why was that chosen?

**Comment by yyoncho** [comment] 2020-07-21 17:50
This should be fixed - we should use defface. @muirdm do you have a suggestion for better face to use as a base? IME it looks nice in most of the themes I have tried.

**Comment by ericdallo** [comment] 2020-07-21 17:51
I chose`homogylph` because it looks "different" from the other modeline things emphasizing it, but if you have a better suggestion for the default we can think about changing it.

**Comment by yyoncho** [comment] 2020-07-21 17:54
`success` and `link` might work too

**Comment by ericdallo** [comment] 2020-07-21 17:57
On some themes link seems to add `underline` which can be strange:
![image](https://user-images.githubusercontent.com/7820865/88089404-4ac6d680-cb62-11ea-95b8-a83630bdbcaf.png)
success seems ok:
![image](https://user-images.githubusercontent.com/7820865/88089441-5ca87980-cb62-11ea-9086-a03b05f61c38.png)
but IMHO I think default looks better as homoglyph:
![image](https://user-images.githubusercontent.com/7820865/88089499-75189400-cb62-11ea-89e9-a2f4e2f783ab.png)

**Comment by yyoncho** [comment] 2020-07-21 18:00
Underlining does not look good if there is space in it.

**Comment by yyoncho** [comment] 2020-07-21 18:01
But actually, this is caused by the way we built the modeline because it is fine for Sort Members.

**Comment by ericdallo** [comment] 2020-07-21 18:04
Yeah, I think so

**Comment by muirdm** [comment] 2020-07-21 18:04
I'm no expert, but I would probably have picked `mode-line` or `default`.

**Comment by ericdallo** [comment] 2020-07-21 18:07
`default` seems to break the icon for some reason: 
![image](https://user-images.githubusercontent.com/7820865/88090215-a5acfd80-cb63-11ea-9d67-2c259f665a9f.png)
`mode-line` looks "normal" in my theme ([Dracula](https://github.com/dracula/emacs))
![image](https://user-images.githubusercontent.com/7820865/88090325-cd03ca80-cb63-11ea-8f17-ec12fb1f8eec.png)

**Comment by muirdm** [comment] 2020-07-21 18:14
Haha, martini upgrade.

It is a lot of text showing up in the modeline, and I had no problem noticing it. Personally I don't really want a bright color for so much text (which is why I wanted to customize it). As long as it is a normal face I can customize then consider my criticism about "homoglyph" retracted.

**Closed** 2020-07-21 18:16 UTC

**Comment by seh** [comment] 2020-09-29 21:32
I came here today when I noticed that Aquamacs 3.5 lacks the "homoglyph" face, causing _lsp-mode_ to fail. Not being in the mood to toy with _customize_ today, I wrote the following:
```elisp
(setq lsp-modeline-code-actions-face 'mode-line)
```
