### ISSUE TITLE
Auto-completion doesn't seem to work when `company-minimum-prefix-length` <= 1

### ISSUE THREAD

**Issue by anonimitoraf** [emacs-lsp/lsp-mode#2624] opened 2021-02-19 12:47 UTC
**Describe the bug**
Auto-completion when:
* Set to 0 - doesn't suggest stuff
Expected: `a/so` should suggest `some-variable` and `some-function`
![lsp-mode-company-min-length-0](https://user-images.githubusercontent.com/15933322/108505741-f9571380-730b-11eb-9398-f6b62b37f201.gif)

* Set to 1 - same as when set to 0
![lsp-mode-company-min-length-1](https://user-images.githubusercontent.com/15933322/108505874-2a374880-730c-11eb-89f6-4266d38a1ff5.gif)

* Set to 2 - works
![lsp-mode-company-min-length-2](https://user-images.githubusercontent.com/15933322/108505907-30c5c000-730c-11eb-8f0a-2bf117625c98.gif)

**To Reproduce**
Sample project: https://github.com/anonimitoraf/issue-reproduction-clojure

Open `src/clojure_sandbox/core.clj` and with different values for `company-minimum-prefix-length`, try to auto-complete `(a/so)`

**Expected behavior**
`company-minimum-prefix-length` set to 0 or 1 should suggest auto-completion entries

**Which Language Server did you use**
clojure-lsp

**OS**
5.9.16-1-MANJARO (via `uname -r`)

**Comment by ericdallo** [comment] 2021-02-19 14:43
@kiennq or @yyoncho do you know why this happens?

**Comment by yyoncho** [comment] 2021-02-19 17:05
I did short debug session on that and I was unable to find out the reason. I confirm the issue is happening only with Clojure, it works fine with the other servers I tested with.

**Comment by ericdallo** [comment] 2021-02-19 17:08
@yyoncho odd, the request is made correctly to the server?

**Comment by yyoncho** [comment] 2021-02-19 17:33
I don't see requests at all.

**Comment by ericdallo** [comment] 2021-02-19 18:04
Got it, so indeed lsp-mode is not requesting for some reason, really curious

**Comment by yyoncho** [comment] 2021-02-19 18:05
most likely it is related to prefix calculation, @kiennq knows much better than me on that.

**Comment by anonimitoraf** [comment] 2021-02-20 03:23
Hey @yyoncho @ericdallo thanks for giving this a glance

I can also check it out, any good starting points? Files to look at, for example

**Comment by yyoncho** [comment] 2021-02-20 08:16
@anonimitoraf thank you for the interest but for this particular issue I believe that @kiennq is the best person to investigate because the completion code is not very intuitive due to the complexity of the emacs `completion-at-point` facilities. But still, if you want to give it a try - start from `lsp-completion-at-point`.

**Comment by kiennq** [comment] 2021-02-20 09:22
@anonimitoraf Did it work if you set `lsp-completion-no-cache` to `t`?

**Comment by anonimitoraf** [comment] 2021-02-20 10:31
@kiennq I see. Yes with `lsp-completion-no-cache` set to `t`, `company-min-length` of 1 works :D

Although with `company-min-length` of 0, it only pops up after I've typed a letter or 2.
When I try to open up the completion box manually, it tells me "No completion found"

I'm thinking that while it might be nice to open up the completion box with 0 chars typed, for the sake of "discoverability", it sounds like this could potentially be inefficient (because: LOT of candidates)

---
Side question: Is setting `lsp-completion-no-cache`to `t` all the more inefficient? What happens when it is set to `t`?

**Comment by kiennq** [comment] 2021-02-20 10:49
Also can you post the trace io log here?
Changing `prefix-length` is working in my env though.
I would not recommend setting `lsp-completion-no-cache` since it will not using cache, and will make the typing slower.

> When I try to open up the completion box manually, it tells me "No completion found"

This seems to be `clojure` language server limitation.
Setting min prefix length to `0` is not that different from `1` since `company` will kick in only after you type something (means the length already `>= 1`). Also some character is guarded and may not trigger company (`(` for example), so with min length of `0`, the completion will be trigger likely after word separation characters (spaces) only.
Combine that with language server limitation, it will likely make you see no different at all.

---

Note that, just type `(` and trigger the completion at point (manually, since it will not be triggered automaticially) will make server returns no result. That value will be cached and make the subsequence typing with same prefix at the same position will not query the language server. It's expected behavior.

**Comment by ericdallo** [comment] 2021-02-20 15:02
Yeah, I can confirm server is not returning any results for a min length of `0`, this could be fixed on server side indeed :)

**Comment by ericdallo** [comment] 2021-02-20 16:59
Fixed the completion with `0` length on server side @anonimitoraf :) https://github.com/clojure-lsp/clojure-lsp/commit/fac945d1d452295adeac04f768d1b37fea0f3e70

**Comment by yyoncho** [comment] 2021-02-20 17:04
@ericdallo is there anything to address on the client side after your server fix?

**Comment by ericdallo** [comment] 2021-02-20 17:06
I think the issue with the 1 length not working without change the cache on completion?

**Comment by ericdallo** [comment] 2021-02-20 17:23
I tested with `company-prefix-length` of `1` and it worked when idle as expected

**Comment by anonimitoraf** [comment] 2021-02-21 04:34
@kiennq Ah, I see. Makes sense.

And damn @ericdallo awesome. Thanks so much! I'll have a read through your commits out of curiosity

**Comment by yyoncho** [comment] 2022-10-21 17:18
seems like this issue is already fixed.

**Closed by yyoncho** 2022-10-21 17:18 UTC
Labels: completion
