### ISSUE TITLE
Flycheck does not use the lsp-ui checker in vue files

### ISSUE THREAD

**Issue by bimbiltu** [emacs-lsp/lsp-mode#1288] opened 2020-01-02 16:49 UTC
**Describe the bug**
Flycheck does not seem to include the lsp-ui checker when the cursor is inside a code block of a vue file. When the cursor is outside of a block the checker is included and the UI is updated by flycheck as expected. This seems to work fine with flymake.

Not sure if this is the same as https://github.com/emacs-lsp/lsp-mode/issues/305 as that issue does not have much information and was opened a long time ago.

**To Reproduce**
Note that you will need vue-language-server installed, typically done with `npm install -g vue-language-server`

```bash
git clone https://github.com/bimbiltu/lsp-vue-flycheck-reproducer.git
cd lsp-vue-flycheck-reproducer
emacs -q --load lsp-start-plain.el test.vue
```

In the <script> block change `const` to `constt` and notice that flycheck never runs and the UI is never updated to show this error. If you run `flycheck-verify-setup` while the cursor is inside the <script> block you will see that there are no checkers. Note that flycheck also reports its running on `typescript-mode` rather than `vue-mode`, which I believe is intentional as vue-mode is a wrapper around mmm-mode. When running `flycheck-verify-checker lsp-ui` I see that flycheck reports that the `lsp-ui` checker is not compatible with `typescript-mode`.

If you then edit the file anywhere outside of the script block (such as adding whitespace above or below it) then flycheck will highlight `constt` red as expected. If you run `flycheck-verify-setup` while the cursor is outside the <script> block you will see that the lsp-ui checker is present as expected.

**Expected behavior**
The lsp-ui checker should be used when the cursor is anywhere in a vue file

**Which Language Server did you use**
vls (vue-language-server)

**OS**
macOS catalina 10.15.2

**Comment by yyoncho** [comment] 2020-01-03 17:34
So the problem is that the `lsp-ui` checker is not registered in for typescript-mode since `vue-mode` apparently runs multiple major modes in single file. You could fix that by adding this line in your config:

```
(lsp-ui-flycheck-add-mode 'typescript-mode)
```

I am not 100%  what should be the correct fix or whether this should be fixed in enacs-lsp at all - ATM I think that adding it to the FAQ section is the best solution. Let me know what do you think.

**Comment by bimbiltu** [comment] 2020-01-04 02:24
vue-mode can potentially use many different major modes; [here are the ones included by default](https://github.com/AdamNiederer/vue-mode/blob/master/vue-mode.el#L43-L68) so it's possible that people may need to register the lsp-ui checker with more than just typescript-mode. I'm not super well versed in emacs so I'm not sure what the best solution would be here either.

Adding that line to my config does at least get me up and running with flycheck for now 👍

**Comment by bimbiltu** [comment] 2020-01-05 15:33
I ended up adding this to my config: `(mapc 'lsp-ui-flycheck-add-mode '(typescript-mode js-mode css-mode vue-html-mode))`. This covers vue files with HTML, javascript, typescript, CSS, and SCSS which is all I really work on. Is this safe to do unconditionally or should I only do this when working on a vue file?

**Comment by yyoncho** [comment] 2020-01-05 16:50
I think it is fine as long as you use lsp-mode for errors in these modes. I think that you might need additional configuration if you want to use different backend in these modes. I might be wrong though since I am not flycheck expert.

**Closed** 2020-01-05 18:28 UTC
