### ISSUE TITLE
Enhancement: Run language servers inside docker containers

### ISSUE THREAD

**Issue by delbonis** [emacs-lsp/lsp-mode#942] opened 2019-07-16 14:28 UTC
At work I have to develop on a macOS machine, but parts of our project can only be built (easily) on a Linux machine (C dependencies in a Rust project), so we have a Docker image for portably using build environment instead of setting up a cross-compilation environment.

So the idea I had is to give `lsp-mode` some awareness of docker so you could specify a Docker image containing the language servers needed to properly build the project via a `.dir-locals.el` in the root of the workspace, and instead of invoking (for example) `rls` directly, invoke it with something along the lines of `docker run --interactive --rm $workspace:/mnt/workspace $image rls`.  There'd have to be some work to adjust any absolute paths that the language server might return as they'd be relative to the docker container but those should be pretty straightforward to deal with.

I'm not sure exactly how much work this would be.  Looking through the code I could see it being done in a very hackish way with only some smaller modifications, but I'm sure a better solution exists.

**Comment by yyoncho** [comment] 2019-07-16 15:08
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/921 . Please go through the thread and share your thoughts.

**Closed by yyoncho** 2019-07-16 15:08 UTC
