### ISSUE TITLE
lsp-mode does not work with latest rust-analyzer

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2436] opened 2020-12-23 13:46 UTC
see https://github.com/rust-analyzer/rust-analyzer/pull/6779 . The issue is in the initializationOptions 

```
Failed to deserialize InitializeParams: missing field `changeAnnotationSupport`; {"processId":null,"rootPath":"/home/fred/Workspace/projs/has","clientInfo":{"name":"emacs","version":"GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)\n of 2020-08-28"},"rootUri":"file:///home/fred/Workspace/projs/has","capabilities":{"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"]},"applyEdit":true,"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"declaration":{"linkSupport":true},"definition":{"linkSupport":true},"implementation":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"synchronization":{"willSave":true,"didSave":true,"willSaveWaitUntil":true},"documentSymbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown"],"resolveAdditionalTextEditsSupport":true},"contextSupport":true},"signatureHelp":{"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"hover":{"contentFormat":["markdown","plaintext"]},"foldingRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":true}},"window":{"workDoneProgress":true},"experimental":{"snippetTextEdit":true}},"initializationOptions":{"diagnostics":{"enable":true,"enableExperimental":true,"disabled":[]},"assist":{"importMergeBehaviour":"full","importPrefix":"plain"},"lruCapacity":null,"checkOnSave":{"enable":true,"command":"clippy","extraArgs":[],"allTargets":true,"overrideCommand":[]},"files":{"exclude":[],"watcher":true},"cargo":{"allFeatures":true,"noDefaultFeatures":false,"features":[],"loadOutDirsFromCheck":true},"rustfmt":{"extraArgs":[],"overrideCommand":[]},"inlayHints":{"typeHints":true,"chainingHints":true,"parameterHints":true,"maxLength":15},"completion":{"addCallParenthesis":true,"addCallArgumentSnippets":true,"postfix":{"enable":true}},"callInfo":{"full":true},"procMacro":{"enable":true}},"workDoneToken":"1"}

Process rust-analyzer stderr finished
```

**Comment by yyoncho** [comment] 2020-12-23 13:46
cc @brotzeit @flodiebold

**Comment by yyoncho** [comment] 2020-12-23 13:50
Changed lsp-install-server  to install an older working version of rust analyzer: https://github.com/emacs-lsp/lsp-mode/commit/dc7708639fa5d2650bd18b0f161bbd53e77b25a6

**Comment by dimitarvp** [comment] 2020-12-23 22:58
Reverted `rust-analyzer` from `2020-12-21` to `2020-12-14` and the error is gone and all LSP functionality is working.

**Comment by dimitarvp** [comment] 2020-12-23 23:06
Also this seems related: https://github.com/rust-analyzer/rust-analyzer/issues/6979

**Comment by brotzeit** [comment] 2020-12-23 23:31
https://github.com/brotzeit/rustic/issues/205#issuecomment-749593539

**Comment by covercash2** [comment] 2020-12-23 23:33
https://github.com/rust-analyzer/rust-analyzer/issues/6979#issuecomment-749293020

**Comment by nbfalcon** [comment] 2020-12-24 14:07
This is a bug in `rust-analyzer` (the whole point of capabilities is for servers *not* to fail if they aren't available). We could probably fix this on `lsp-mode`'s side by listing those capabilities as `:json-false`.

**Comment by dimitarvp** [comment] 2020-12-24 14:34
@nbfalcon I realize this is on `rust-analyzer` and not a bug in `lsp-mode`. Apologies if I made it sound otherwise.

They announced this will be fixed in a next release. I'm leaving it to you to judge if you need to cover for servers that try to mandate otherwise optional LS features. Mostly posted this to increase visibility and give searchers a context about what's going on.

**Comment by yyoncho** [comment] 2020-12-24 14:39
> Using Spacemacs so couldn't utilize this fix so had to manually downgrade.

@dimitarvp FYI the automatic install works in spacemacs as well.

**Comment by nbfalcon** [comment] 2020-12-24 14:41
@yyoncho do you think we should wait for this to be fixed upstream, or implement a fix here now?

**Comment by yyoncho** [comment] 2020-12-24 14:43
@nbfalcon ideally, we should have support for that new feature. The fix will be supporting the new feature, right(I havent checked the details on rust analyzer side)?

**Comment by nbfalcon** [comment] 2020-12-24 14:44
I actually thought of just adding those capabilities as `:json-false`. I'd need to look at the spec again to see what was added.

**Comment by yyoncho** [comment] 2020-12-24 15:19
I don't see a reason against adding false as initial step just to get the latest release running (assuming that it will provide fixes and improvements)

**Comment by dimitarvp** [comment] 2020-12-28 11:37
This seems fixed in `rust-analyzer`'s `2020-12-28` release. I can't reproduce the issue with it installed anymore.

**Comment by holykol** [comment] 2020-12-28 21:13
If anyone here is using Arch you  can get fixed version without waiting for it to get out of testing repo:
```
pacman -U https://archive.archlinux.org/packages/r/rust-analyzer/rust-analyzer-20201228-1-x86_64.pkg.tar.zst
```

**Comment by brotzeit** [comment] 2020-12-29 15:49
Ok then let's keep this open another week and close.

**Comment by yyoncho** [comment] 2020-12-29 15:55
FTR https://github.com/emacs-lsp/lsp-mode/issues/2455 will track the work on supporting `changeAnnotationSupport`

**Comment by Karrq** [comment] 2021-01-05 02:06
I can confirm later versions do fix the issue, currently I'm running 2021-01-04 Arch's release and it works properly

**Closed** 2021-01-09 13:39 UTC
Labels: rust, rust-analyzer bug
