### ISSUE TITLE
Inserting emoji in using Elixir LS causes lsp-mode to crash

### ISSUE THREAD

**Issue by jsmestad** [emacs-lsp/lsp-mode#3343] opened 2022-02-05 17:22 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

On macOS using any version of Emacs I have tried (27 through 29), in an Elixir file if you use macOS shortcut: Cmd+Ctrl+Space to use the macOS Emoji dialog to insert an emoji into an Elixir string "Foo" -> "Foo 🦤", the ElixirLS instance will crash with an error.

### Steps to reproduce

On macOS using any version of Emacs I have tried (27 through 29), in an Elixir file if you use macOS shortcut: Cmd+Ctrl+Space to use the macOS Emoji dialog to insert an emoji into an Elixir string "Foo" -> "Foo 🦤", the ElixirLS instance will crash.

### Expected behavior

Inserting an emoji does not crash the language server

### Which Language Server did you use?

elixir-ls

### OS

MacOS

### Error callstack

```emacs-lisp
10:54:00.145 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iodata term

    :erlang.iolist_to_binary([["defmodule MyApp.ContractsTest do", "\n"], ["  use MyApp.DataCase, async: true", "\n"], ["", "\n"], ["  alias MyApp.Contracts", "\n"], ["  alias MyApp.Contracts.Contract", "\n"], ["", "\n"], ["  describe \"get_user_contract/1\" do", "\n"], ["    setup do", "\n"], ["      %{user: build(:user)}", "\n"], ["    end", "\n"], ["", "\n"], ["    test \"returns an error when no historical status is found\", %{user: user} do", "\n"], ["      refute Contracts.get_user_contract(user)", "\n"], ["    end", "\n"], ["", "\n"], ["    test \"pulls the newest data from the database\", %{user: user} do", "\n"], ["      [_older, newer] =", "\n"], ["        build_pair(:contract, mode: :online, user: user) |> Enum.map(&MyApp.Repo.insert!/1)", "\n"], ["", "\n"], ["      assert Contracts.get_user_contract(user).id == newer.id", "\n"], ["    end", "\n"], ["", "\n"], ["    test \"scopes the search to the current user\", %{user: current_user} do", "\n"], ["      %{id: expected_id} =", "\n"], ["        build(:contract, mode: :online, user: current_user) |> MyApp.Repo.insert!()", "\n"], ["", "\n"], ["      _other_contract =", "\n"], ["        build(:contract, mode: :online, user: build(:user)) |> MyApp.Repo.insert!()", "\n"], ["", "\n"], ["      assert Contracts.get_user_contract(current_user).id == expected_id", "\n"], ["    end", "\n"], ["  end", "\n"], ["", "\n"], ["  describe \"get_previous_contract/1\" do", "\n"], ["    setup do", "\n"], ["      user = build(:user)", "\n"], ["      contract = build(:contract, user: user, mode: :online) |> MyApp.Repo.insert!()", "\n"], ["      %{user: user, contract: contract}", "\n"], ["    end", "\n"], ["", "\n"], ["    test \"returns the previous from the unsaved contract\", %{", "\n"], ["      user: user,", "\n"], ["      contract: %{id: previous_id}", "\n"], ["    } do", "\n"], ["      contract = build(:contract, user: user, mode: :online)", "\n"], ["", "\n"], ["      assert is_nil(contract.id)", "\n"], ["      assert Contracts.get_previous_contract(contract).id == previous_id", "\n"], ["    end", ...], [...], ...])
    (language_server 0.9.0) lib/language_server/source_file.ex:246: ElixirLS.LanguageServer.SourceFile.apply_edit/3
    (elixir 1.13.2) lib/map.ex:813: Map.update!/3
    (language_server 0.9.0) lib/language_server/source_file.ex:45: ElixirLS.LanguageServer.SourceFile.apply_content_changes/2
    (language_server 0.9.0) lib/language_server/server.ex:379: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_notification/2
    (elixir 1.13.2) lib/map.ex:854: Map.get_and_update/3
    (elixir 1.13.2) lib/map.ex:896: Map.get_and_update!/3
    (language_server 0.9.0) lib/language_server/server.ex:377: ElixirLS.LanguageServer.Server.handle_notification/2
Last message: {:"$gen_cast", {:receive_packet, %{"jsonrpc" => "2.0", "method" => "textDocument/didChange", "params" => %{"contentChanges" => [%{"range" => %{"end" => %{"character" => 41, "line" => 243}, "start" => %{"character" => 40, "line" => 243}}, "rangeLength" => 1, "text" => "\""}], "textDocument" => %{"uri" => "file:///Users/justinsmestad/code/myapp/app/test/my_app/contracts_test.exs", "version" => 343}}}}}
State: %ElixirLS.LanguageServer.Server{analysis_ready?: true, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.2128688936.3778543617.99195>, build_running?: false, client_capabilities: %{"textDocument" => %{"callHierarchy" => %{"dynamicRegistration" => false}, "codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dataSupport" => true, "dynamicRegistration" => true, "isPreferredSupport" => true, "resolveSupport" => %{"properties" => ["edit", "command"]}}, "completion" => %{"completionItem" => %{"deprecatedSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "insertReplaceSupport" => true, "insertTextModeSupport" => %{"valueSet" => [1, 2]}, "resolveAdditionalTextEditsSupport" => true, "resolveSupport" => %{"properties" => ["documentation", "details", "additionalTextEdits", "command"]}, "snippetSupport" => true}, "contextSupport" => true}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentLink" => %{"dynamicRegistration" => true, "tooltipSupport" => true}, "documentSymbol" => %{"hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "foldingRange" => %{"dynamicRegistration" => true}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"]}, "implementation" => %{"linkSupport" => true}, "linkedEditingRange" => %{"dynamicRegistration" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}, "versionSupport" => true}, "rangeFormatting" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true, "prepareSupport" => true}, "signatureHelp" => %{"signatureInformation" => %{"parameterInformation" => %{"labelOffsetSupport" => true}}}, "synchronization" => %{"didSave" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"showDocument" => %{"support" => true}, "showMessage" => nil, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "didChangeWatchedFiles" => %{"dynamicRegistration" => true}, "executeCommand" => %{"dynamicRegistration" => false}, "fileOperations" => %{"didCreate" => false, "didDelete" => false, "didRename" => false, "willCreate" => false, "willDelete" => false, "willRename" => false}, "symbol" => %{"symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"documentChanges" => true, "resourceOperations" => ["create", "rename", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [%Mix.Task.Compiler.Diagnostic{compiler_name: "ElixirLS Dialyzer", details: {:warn_return_no_exit, {'test/support/fixtures/oauth_fixtures.ex', 32, {MyApp.OauthFixtures, :access_token, 2}}, {:no_return, [:only_normal, :access_token, 2]}}, file: "/Users/justinsmestad/code/myapp/app/test/support/fixtures/oauth_fixtures.ex", message: "Function access_token/2 has no local return.", position: 32, severity: :warning}, %Mix.Task.Compiler.Diagnostic{compiler_name: "ElixirLS Dialyzer", details: {:warn_return_no_exit, {'test/support/fixtures/oauth_fixtures.ex', 48, {MyApp.OauthFixtures, :stale_access_token, 2}}, {:no_return, [:only_normal, :stale_access_token, 2]}}, file: "/Users/justinsmestad/code/myapp/app/test/support/fixtures/oauth_fixtures.ex", message: "Function stale_access_token/2 has no local return.", position: 48, severity: :warning}, %Mix.Task.Compiler.Diagnostic{compiler_name: "ElixirLS Dialyzer", details: {:warn_matching, {'test/support/test_helpers.ex', 34, {MyApp.TestHelpers, :set_contract!, 1}}, {:pattern_match, ['pattern {\'error\', _reason@1}', '{\'ok\',\#{\'broadcast\':=\'true\', \'contract\':=\#{\'__meta__\':=\#{\'__struct__\':=\'Elixir.Ecto.Schema.Metadata\', \'context\':=_, \'prefix\':=\'nil\' | binary(), \'schema\':=atom(), \'source\':=binary(), \'state\':=\'built\' | \'deleted\' | \'loaded\'}, \'__struct__\':=\'Elixir.MyApp.Contracts.Contract\', \'afk\':=\'false\' | \'nil\' | \'true\', \'auto_respond\':=\'false\' | \'nil\' | \'true\', \'duration\':=_, \'expires_at\':=\'nil\' | \#{\'__struct__\':=\'Elixir.DateTime\', \'calendar\':=atom(), \'day\':=pos_integer(), \'hour\':=non_neg_integer(), \'microsecond\':={non_neg_integer(),non_neg_integer()}, \'minute\':=non_neg_integer(), \'month\':=pos_integer(), \'second\':=non_neg_integer(), \'std_offset\' (truncated)
** (exit) exited in: GenServer.call(ElixirLS.LanguageServer.JsonRpc, {:packet, %{"id" => 912, "jsonrpc" => "2.0", "method" => "textDocument/formatting", "params" => %{"options" => %{"insertSpaces" => true, "tabSize" => 2}, "textDocument" => %{"uri" => "file:///Users/justinsmestad/code/myapp/app/test/my_app/contracts_test.exs"}}}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.2) lib/gen_server.ex:1019: GenServer.call/3
    (elixir 1.13.2) lib/stream.ex:441: anonymous fn/4 in Stream.each/2
    (elixir 1.13.2) lib/stream.ex:1559: Stream.do_element_resource/6
    (elixir 1.13.2) lib/stream.ex:1719: Enumerable.Stream.do_each/4
    (elixir 1.13.2) lib/stream.ex:649: Stream.run/1
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
```

### Anything else?

I reported this to Elixir LS originally, but it does not happen in other editors so they suggested it is an lsp-mode issue. See ticket https://github.com/elixir-lsp/elixir-ls/issues/667

**Comment by yyoncho** [comment] 2022-02-05 17:25
duplicate of https://github.com/emacs-lsp/lsp-mode/issues/2080 (there is a fix in the bug, I have to benchmark it and merge it)

**Closed by yyoncho** 2022-02-05 17:25 UTC
Labels: bug
