### ISSUE TITLE
link-color issue in react tutorial

### ISSUE THREAD

**Issue by thisch** [emacs-lsp/lsp-mode#2608] opened 2021-02-13 12:42 UTC
In the react tutorial there is a hyperlink in a "Note:" section, that is unfortunately colored with the same color as the color of its surrounding text, see

![image](https://user-images.githubusercontent.com/206581/107850158-9d1e5c00-6e00-11eb-952b-a434fa6146c7.png)

This is the corresponding source

```markdown
>Note: in order to avoid [this issue](https://github.com/eclipse-theia/theia/issues/6720#issuecomment-563488535), you have to add a `jsconfig.json` in the top of the folder:
```

**Comment by yyoncho** [comment] 2021-02-13 13:36
Thank you for the report, I think that the issue is fixed in typescript-language-server. I will remove the line after verifying that.

**Comment by thisch** [comment] 2021-02-13 15:44
I didn't run into any issue (except one when running `npx  ...`) when doing the tutorial.

**Closed** 2021-02-19 19:43 UTC
