### ISSUE TITLE
Docs rendering in plain text instead of Markdown

### ISSUE THREAD

**Issue by ema2159** [emacs-lsp/lsp-mode#3866] opened 2022-12-19 02:11 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When using lsp-mode with rust, some of the elements using lsp-ui-doc render in plain text instead of markdown. This wasn't occurring until I updated lsp-mode, though I hadn't update it in a while

### Steps to reproduce

Start lsp-mode in a rust project. When hovering some of the elements, they will not be rendered properly, while some will. An example is shown below:
![image](https://user-images.githubusercontent.com/17773218/208334367-2b0830cd-c1b6-4f3f-9c29-2868f99891ed.png)

### Expected behavior

The docs should be rendered properly with the correct formatting.

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by MoSheikh** [comment] 2022-12-19 05:19
I'm getting the same issue but for the `ts-ls` server.

**Comment by XO39** [comment] 2022-12-19 05:42
Looks like this is not specific to `rust-mode` only as I'm getting the same problem with `go-mode` (`gopls` server) after updating 2-3 days ago.

**Comment by jcs090218** [comment] 2022-12-19 05:51
Related issue in https://github.com/emacs-lsp/lsp-ui/issues/742.

**Comment by psibi** [comment] 2022-12-19 06:36
Not sure if it's related to Emacs 29 as I'm able to reproduce it in 28.2 itself.

**Comment by jcs090218** [comment] 2022-12-19 06:44
> Not sure if it's related to Emacs 29 as I'm able to reproduce it in 28.2 itself.

The title is misleading. The conclusions is about the recent commit in https://github.com/emacs-lsp/lsp-mode/commit/e2a1b5f682ae00206491a80b4d28e8d932c2960f.

See comment https://github.com/emacs-lsp/lsp-ui/issues/742#issuecomment-1357098613 for clarification.

**Comment by jcs090218** [comment] 2022-12-19 11:52
Should be fixed with #3867, therefore closing this issue.

**Closed by jcs090218** 2022-12-19 11:52 UTC
Labels: bug
