### ISSUE TITLE
Completing variable name in PHP inserts extra '$'

### ISSUE THREAD

**Issue by Kazimazi** [emacs-lsp/lsp-mode#865] opened 2019-05-31 07:50 UTC
**Describe the bug**
Choosing a variable name from the completion menu puts extra `$` at the beginning of name.
[Video](https://streamable.com/6c7yp)

**To Reproduce**
Create variable `$color = "red";` and try to complete it `$co`.

**Which Language Server did you use**
Intelephense PHP language server.

**Comment by yyoncho** [comment] 2019-05-31 07:52
This is company-lsp bug. 

(cc @tigersoldier )

**Comment by yyoncho** [comment] 2019-06-01 07:29
@Kazimazi unable to reproduce using lsp-start-plain.el file (you have to install php-mode additionally).

```
 emacs  -q -l ~/lsp-mode/scripts/lsp-start-plain.el
```

IMO the issue is caused by company setting or you are not using the latest version of all components.

**Comment by Kazimazi** [comment] 2019-06-02 13:28
I wonder why... I have the newest of everything. I'll try a minimal config when I have time.

**Comment by Kazimazi** [comment] 2019-06-05 10:44
I've found the reason I have this issue. I have `evil-collection` so I get various key binds like cycle selections [here](https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-company.el). I don't exactly know why it duplicates `$` yet. Might solve it later on.

**Comment by yyoncho** [comment] 2019-06-05 10:50
The issue is that lsp-mode and snippets, in general, does not work with tng frontend so I guess if you set evil-collection-company-use-tng to nil the issue will be fixed. 

See https://github.com/company-mode/company-mode/issues/891

**Closed by yyoncho** 2019-06-05 10:50 UTC
Labels: Unable to reproduce
