### ISSUE TITLE
Automatic and irreversible switch to `*Warnings*` buffer when pyls (Python language server) returns certain errors

### ISSUE THREAD

**Issue by gcv** [emacs-lsp/lsp-mode#914] opened 2019-07-01 14:41 UTC
**Describe the bug**

The following source file causes `lsp-mode` to switch to the `*Warnings*` buffer when the cursor is moved on the line containing `self.study_name` and makes it impossible to go back to the source buffer unless the pyls connection is killed:

```python
class TestClass:

    def initialize_optuna(self):
        try:
            train_env = Alpha(
                [lambda: Bravo(self.feature_df)])
            model = self.Model(self.Policy, train_env, nminibatches=1)
            self.study_name = f'{model.__class__.__name__}__{model.act_model.__class__.__name__}__{self.reward_strategy}'
        except:
            self.study_name = f'UnknownModel__UnknownPolicy__{self.reward_strategy}'
```

**To Reproduce**

I use Tramp remote lsp-mode integration, but I suspect the error will occur on local pyls installations also.

Make a root project containing the source file above (I called it `test.py`). Connect to `pyls` with `lsp-mode` (vanilla configuration). Position the cursor on the `study_name` identifier on line 8. It instantly dumps me into the `*Warnings*` buffer.

**Expected behavior**

Ideally, the error goes away altogether, but that might be a pyls problem. At minimum, `lsp-mode` should not autodump me back in the `*Warnings*` buffer.

**Which Language Server did you use**

python-language-server 0.27.0, used through `lsp-mode`'s Tramp remote connection. `pip list` output is attached to make the environment reproducible.

**OS**

Emacs 26.2 on macOS, pyls runs on a Linux docker container:

```
$ uname -a
Linux mlc3 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
```

**Error callstack**

The `*Warnings*` and `*lsp-log*` buffer contents are attached. The error seems to be related to pyls blowing up with `'FStringStart' object has no attribute 'children'` error.

[lsp-log.txt](https://github.com/emacs-lsp/lsp-mode/files/3346092/lsp-log.txt)
[pip-list.txt](https://github.com/emacs-lsp/lsp-mode/files/3346093/pip-list.txt)
[warnings.txt](https://github.com/emacs-lsp/lsp-mode/files/3346094/warnings.txt)

**Comment by yyoncho** [comment] 2019-07-01 15:27
Thanks for the detailed bug report, can you share your pyls configuration(the remote one)?

**Comment by gcv** [comment] 2019-07-01 16:47
You mean the lsp-mode one?

```
            (lsp-register-client
             (make-lsp-client :new-connection (lsp-tramp-connection "pyls")
                              :major-modes '(python-mode)
                              :remote? t
                              :server-id 'pyls-remote))
```

I don't have any special configuration for pyls on the remote side. The `pyls` binary is in `/usr/local/bin`.

**Comment by yyoncho** [comment] 2019-07-02 04:15
I am unable to reproduce it locally, but the issue seems to be duplicate of https://github.com/palantir/python-language-server/issues/424

**Comment by gcv** [comment] 2019-07-02 15:07
Indeed, the problem arises from the complexity of the LSP stack. With Python, enabling LSP means installing a dozen or more heavy dependencies, including Jedi, all of which need to work correctly for lsp-mode to work.

My larger purpose in opening this ticket is to discuss lsp-mode error handling, and how much can be done to mitigate back-end instability. That pyls ticket has been ignored for 9 months now, so no reason to believe anything will change soon — so I believe lsp-mode needs to deal with such errors more gracefully.

In this particular case, the `*Warnings*` buffer switch at the point of detecting the remote error is pretty bad, for two reasons. First and most importantly, the cursor remains at the breaking position in the source file buffer. So switching from `*Warnings*` back to the source instantly causes the error to occur again, and again switches to `*Warnings*`. This is highly disruptive, much more so than just not showing the relevant tooltip or documentation pop-up. Second, lsp-mode mostly works as advertised in this code base. An isolated error relating to one line of code should not break the entire system.

Would it be feasible to change lsp-mode to detect erroring one-offs like this from the server and mark them in some way? i.e., put a warning underline for the source which causes the back-end to break and let the user investigate at leisure, but get on with work?

**Comment by yyoncho** [comment] 2019-07-02 18:29
> Would it be feasible to change lsp-mode to detect erroring one-offs like this from the server and mark them in some way? 

I agree - I would propose downgrading these errors from `display-warning` which steals the focus to using lsp--error which displays only a message in the minibuffer.

**Comment by yyoncho** [comment] 2019-07-03 04:29
@gcv ah... I just checked the warnings buffer and you are hitting an issue related to using language server over tramp. The issue is that over tramp emacs does not have separate stderr and stdin and when pyls uses stderr the errors break the parser. The solution to this error is to use a wrapper script on the remote host to redirect the stderr to file. Here it is the script:

```
cat /dev/stdin | tee /tmp/pyls-logs | pyls $@ 2>/tmp/pyls-error | tee -a /tmp/pyls-logs
```

Please put it in the path on the remote machine and mark it as an executable and update the pyls remote configuration to point to it. I think that this will solve your issue.

**Comment by gcv** [comment] 2019-07-03 15:15
Thanks, that worked. That's quite a gotcha, and well worth documenting in the tramp section of the README!

1. Can this wrapping be performed by lsp-mode automatically in remote mode?
2. The LSP logs files grow very very quickly. It would be helpful to do something to keep their size down to at most a few megabytes.

**Comment by yyoncho** [comment] 2019-07-03 16:16
> Can this wrapping be performed by lsp-mode automatically in remote mode?

Probably yes, it should be tested. You may consider testing and providing PR. 

> The LSP logs files grow very very quickly. It would be helpful to do something to keep their size down to at most a few megabytes

You may keep only that part, or even use /dev/null 
```
pyls $@ 2>/tmp/pyls-error 
```

**Comment by gcv** [comment] 2019-07-03 18:39
I'm currently testing the behavior of just changing the `lsp-tramp-connection` call. Seems to work so far.

```
(make-lsp-client :new-connection (lsp-tramp-connection "pyls 2>/dev/null")
   ...)
```

**Comment by gcv** [comment] 2019-07-04 23:31
Documentation PR: https://github.com/emacs-lsp/lsp-mode/pull/919

**Comment by yyoncho** [comment] 2019-07-09 04:48
PR at https://github.com/emacs-lsp/lsp-mode/pull/929, can you help with testing it?

**Comment by gcv** [comment] 2019-07-11 13:34
Delayed response due to travel schedule... I left a comment on that PR.

**Closed** 2019-07-20 04:21 UTC
