### ISSUE TITLE
Performance issues with CSS server

### ISSUE THREAD

**Issue by resultingCorrespondence** [emacs-lsp/lsp-mode#847] opened 2019-05-22 04:43 UTC
**Describe the bug**
Frequent lag is experience while using completion from the CSS server.

**To Reproduce**
Here is my lsp-mode, lsp-ui, and company-lsp config (all packages were updated from Melpa today):
```emacs-lisp
(use-package lsp-mode
  :ensure t
  :defer t
  :commands lsp
  :hook ((python-mode). lsp))

(use-package lsp-ui
  :after lsp-mode
  :ensure t
  :defer t
  :commands lsp-ui-mode
  :config
  (setq lsp-ui-sideline-enable nil))

(use-package company-lsp
  :after lsp-mode
  :ensure t
  :defer t)

```

**Expected behavior**
Less lag when typing.

**Which Language Server did you use**
VSCodes CSS server

**OS**
macOS

**Error callstack**
I don't have the callstack, but here is the profiler report:
```- timer-event-handler                                             975  29%
 - apply                                                          972  29%
  - company-idle-begin                                            930  27%
   - company-auto-begin                                           904  27%
    - company--perform                                            904  27%
     - company--begin-new                                         904  27%
      - company-calculate-candidates                              903  27%
       - company--fetch-candidates                                903  27%
        - sit-for                                                 894  26%
         - read-event                                              65   1%
          - #<compiled 0x1ff999916be1>                             63   1%
             lsp--parser-read                                      31   0%
           - lsp--parser-on-message                                24   0%
            - lsp--read-json                                       13   0%
             - json-read-from-string                               13   0%
                #<compiled 0x1ff999e8e165>                          9   0%
              - json-read                                           4   0%
               - json-read-object                                   4   0%
                - json-read                                         4   0%
                 - json-read-object                                 4   0%
                  - json-read                                       4   0%
                   - json-read-array                                4   0%
                      json-read                                     4   0%
            - #<compiled 0x1ff99b6b82e5>                           11   0%
             - #<compiled 0x1ff99957e0e5>                          11   0%
              - #<compiled 0x1ff99957cce5>                         11   0%
               - company-lsp--on-completion                        11   0%
                - mapcar                                            4   0%
                 - #<compiled 0x1ff998189229>                       4   0%
                    company-lsp--make-candidate                     4   0%
                - company-lsp--filter-candidates                    4   0%
                 - mapcar                                           4   0%
                  - #<compiled 0x1ff9996e5d35>                      4   0%
                   - company-lsp-match-candidate-flex                  4   0%
                      company-lsp--candidate-filter-text                  1   0%
                - lsp--sort-completions                             3   0%
                 - -sort                                            3   0%
                  - sort                                            3   0%
                     #<compiled 0x1ff9992ae421>                     1   0%
          - timer-event-handler                                     2   0%
           - apply                                                  2   0%
            - #<compiled 0x1ff99b0da3f1>                            2   0%
             - lsp--document-highlight                              2   0%
              - lsp-request-async                                   2   0%
               - lsp--send-request-async                            2   0%
                  lsp--send-no-wait                                 1   0%
        - #<compiled 0x1ff99a5953e5>                                9   0%
         - company-lsp--candidates-async                            9   0%
          - lsp--send-request-async                                 5   0%
           - lsp--make-message                                      3   0%
            - json-encode                                           3   0%
             - json-encode-list                                     3   0%
              - json-encode-plist                                   3   0%
                 json-encode-key                                    2   0%
               - json-encode                                        1   0%
                - json-encode-list                                  1   0%
                 - json-encode-plist                                1   0%
                  - json-encode                                     1   0%
                   - json-encode-list                               1   0%
                    - json-encode-plist                             1   0%
                     - json-encode-key                              1   0%
                      - json-read-from-string                       1   0%
                         generate-new-buffer                        1   0%
             lsp--send-no-wait                                      2   0%
          - company-lsp--cancel-outstanding-request                  3   0%
           - lsp--cancel-request                                    3   0%
            - lsp-notify                                            3   0%
             - lsp--send-notification                               3   0%
              - mapcar                                              3   0%
               - #<compiled 0x1ff993a69bf1>                         3   0%
                  lsp--send-no-wait                                 3   0%
          - company-lsp--make-completion-request                    1   0%
           - company-lsp--get-completion-context                    1   0%
            - company-lsp--get-context-trigger-characters                  1   0%
             - company-lsp--trigger-characters                      1   0%
              - lsp--capability                                     1   0%
               - lsp--server-capabilities                           1   0%
                - apply                                             1   0%
                   ht-merge                                         1   0%
      - company-call-backend                                        1   0%
       - company--force-sync                                        1   0%
        - apply                                                     1   0%
         - company-call-backend-raw                                 1   0%
            apply                                                   1   0%
   - company-post-command                                          26   0%
    - company-call-frontends                                       26   0%
     - company-pseudo-tooltip-unless-just-one-frontend                 26   0%
      - company-pseudo-tooltip-frontend                            26   0%
       - company-pseudo-tooltip-show-at-point                      24   0%
        - company-pseudo-tooltip-show                              23   0%
         - company--create-lines                                    7   0%
          - company-fill-propertize                                 5   0%
           - company-call-backend                                   4   0%
            - company--force-sync                                   4   0%
             - apply                                                4   0%
              - company-call-backend-raw                            4   0%
               - apply                                              4   0%
                - company-lsp                                       4   0%
                 - company-lsp--compute-flex-match                  4   0%
                  - company-lsp--completion-prefix                  4   0%
                   - company-lsp--trigger-characters                  2   0%
                    - lsp--capability                               2   0%
                     - lsp--server-capabilities                     2   0%
                      - apply                                       2   0%
                         ht-merge                                   2   0%
                     company-grab-symbol-cons                       1   0%
           - company--pre-render                                    1   0%
            - company-call-backend                                  1   0%
             - company--force-sync                                  1   0%
                apply                                               1   0%
          - company--clean-string                                   1   0%
             replace-regexp-in-string                               1   0%
          - company-call-backend                                    1   0%
           - company--force-sync                                    1   0%
            - apply                                                 1   0%
             - company-call-backend-raw                             1   0%
              - apply                                               1   0%
                 company-lsp                                        1   0%
           company-buffer-lines                                     3   0%
         - company--pseudo-tooltip-height                           2   0%
          - company--row                                            2   0%
             company--col-row                                       2   0%
         - apply                                                    2   0%
          - company--replacement-string                             2   0%
           - font-lock-append-text-property                         1   0%
              font-lock--add-text-property                          1   0%
          company--col-row                                          1   0%
       - company-pseudo-tooltip-guard                               2   0%
          beginning-of-visual-line                                  2   0%
  - #<compiled 0x1ff99a2973e5>                                     16   0%
   - lsp--document-highlight                                       14   0%
    - lsp-request-async                                            14   0%
     - lsp--send-request-async                                     14   0%
        lsp--send-no-wait                                          11   0%
      - lsp--make-message                                           2   0%
       - json-encode                                                2   0%
        - json-encode-list                                          2   0%
         - json-encode-plist                                        2   0%
          - json-encode                                             1   0%
           - json-encode-list                                       1   0%
            - json-encode-plist                                     1   0%
             - json-encode-key                                      1   0%
              - json-read-from-string                               1   0%
                 generate-new-buffer                                1   0%
            json-encode-key                                         1   0%
      - lsp--find-workspaces-for                                    1   0%
       - lsp--capability                                            1   0%
        - lsp--server-capabilities                                  1   0%
         - apply                                                    1   0%
            ht-merge                                                1   0%
   - lsp--capability                                                2   0%
    - lsp--server-capabilities                                      2   0%
     - apply                                                        2   0%
        ht-merge                                                    2   0%
  - #<compiled 0x436b9887>                                         12   0%
   - eldoc-print-current-symbol-info                               12   0%
    - #<compiled 0x1ff99991db65>                                    9   0%
     - apply                                                        9   0%
      - lsp-eldoc-function                                          9   0%
       - run-hook-wrapped                                           9   0%
        - #<compiled 0x1ff99909c351>                                9   0%
         - lsp-hover                                                9   0%
          - lsp-request-async                                       9   0%
           - lsp--send-request-async                                9   0%
            - lsp--make-message                                     3   0%
             - json-encode                                          3   0%
              - json-encode-list                                    3   0%
               - json-encode-plist                                  3   0%
                - json-encode                                       3   0%
                 - json-encode-list                                 3   0%
                  - json-encode-plist                               2   0%
                   - json-encode                                    2   0%
                    - json-encode-list                              2   0%
                       json-plist-p                                 1   0%
                     - json-encode-plist                            1   0%
                      - json-encode                                 1   0%
                         json-encode-number                         1   0%
            - lsp--flush-delayed-changes                            3   0%
             - -each                                                3   0%
              - #<compiled 0x1ff9996f969d>                          3   0%
               - lsp-notify                                         3   0%
                - lsp--send-notification                            3   0%
                 - mapcar                                           3   0%
                  - #<compiled 0x1ff99a333be5>                      3   0%
                     lsp--send-no-wait                              2   0%
                   - lsp--make-message                              1   0%
                    - json-encode                                   1   0%
                     - json-encode-list                             1   0%
                      - json-encode-plist                           1   0%
                       - json-encode-key                            1   0%
                        - json-read-from-string                     1   0%
                           generate-new-buffer                      1   0%
              lsp--send-no-wait                                     3   0%
  - #<compiled 0x1ff99aefccf1>                                      6   0%
   - lsp-ui-doc--display                                            6   0%
      lsp-ui-doc--move-frame                                        4   0%
  - beacon--dec                                                     2   0%
   - beacon--ov-at-point                                            2   0%
      seq-filter                                                    1   0%
  - which-key--update                                               1   0%
     which-key--this-command-keys                                   1   0%
  - #<compiled 0x1ff998d61bd5>                                      1   0%
     flymake--log-1                                                 1   0%
 - timer-activate                                                   2   0%
  - timer--activate                                                 2   0%
     timer--time-less-p                                             2   0%
 - timer-inc-time                                                   1   0%
    timer-relative-time                                             1   0%
- company-post-command                                            950  28%
 - company--perform                                               939  28%
  - company--continue                                             935  28%
   - company-calculate-candidates                                 923  27%
    - company--fetch-candidates                                   923  27%
     - sit-for                                                    921  27%
      - read-event                                                475  14%
       - #<compiled 0x1ff999916be1>                               475  14%
        - lsp--parser-on-message                                  457  13%
         - lsp--read-json                                         430  12%
          - json-read-from-string                                 430  12%
           - json-read                                            427  12%
            - json-read-object                                    427  12%
             - json-read                                          427  12%
              - json-read-object                                  427  12%
               - json-read                                        427  12%
                - json-read-array                                 427  12%
                 - json-read                                      426  12%
                  - json-read-object                              422  12%
                   - json-read                                    360  10%
                    - json-read-object                            302   9%
                     - json-read                                  162   4%
                      - json-read-object                          145   4%
                       - json-read                                 82   2%
                        - json-read-object                         77   2%
                           json-new-object                         53   1%
                         - json-read                               12   0%
                            json-read-number                        8   0%
                           json-add-to-object                       1   0%
                         json-new-object                           56   1%
                       json-new-object                            129   3%
                      json-read-string                              2   0%
                      json-read-number                              2   0%
                     json-new-object                               37   1%
             #<compiled 0x1ff99af979f1>                             3   0%
         - #<compiled 0x1ff999cabff1>                              17   0%
          - #<compiled 0x1ff999cab7f1>                             17   0%
           - #<compiled 0x1ff99af536f1>                            11   0%
            - company-lsp--on-completion                           11   0%
             - company-lsp--filter-candidates                       6   0%
              - mapcar                                              6   0%
               - #<compiled 0x1ff99ae57df1>                         6   0%
                  company-lsp-match-candidate-flex                  6   0%
             - mapcar                                               5   0%
              - #<compiled 0x1ff99ae575f1>                          5   0%
                 company-lsp--make-candidate                        5   0%
           - #<compiled 0x1ff999caaff1>                             6   0%
            - lsp-ui-doc--callback                                  6   0%
               lsp-ui-doc--hide-frame                               6   0%
         - lsp--on-notification                                    10   0%
          - lsp--on-diagnostics                                    10   0%
           - find-buffer-visiting                                  10   0%
            - file-truename                                        10   0%
             - file-truename                                        4   0%
              - file-truename                                       3   0%
               - file-truename                                      2   0%
                  file-truename                                     1   0%
             - file-name-case-insensitive-p                         1   0%
              - ucs-normalize-hfs-nfd-pre-write-conversion                  1   0%
               - ucs-normalize-HFS-NFD-region                       1   0%
                  ucs-normalize-region                              1   0%
          lsp--parser-read                                         16   0%
     - #<compiled 0x1ff99af48af1>                                   2   0%
      - company-lsp--candidates-async                               2   0%
       - lsp--send-request-async                                    2   0%
          lsp--send-no-wait                                         2   0%
   - company-cancel                                                12   0%
    - company-call-frontends                                       12   0%
     - company-echo-metadata-frontend                              12   0%
      - company-echo-hide                                          12   0%
         company-echo-show                                         12   0%
  - company-call-frontends                                          4   0%
   - company-pseudo-tooltip-unless-just-one-frontend                  4   0%
    - company-pseudo-tooltip-frontend                               4   0%
     - company-pseudo-tooltip-edit                                  4   0%
      - company--create-lines                                       4   0%
       - company-fill-propertize                                    3   0%
        - company--pre-render                                       1   0%
         - company-call-backend                                     1   0%
          - company--force-sync                                     1   0%
             apply                                                  1   0%
        - company-call-backend                                      1   0%
         - company--force-sync                                      1   0%
          - apply                                                   1   0%
           - company-call-backend-raw                               1   0%
            - apply                                                 1   0%
             - company-lsp                                          1   0%
              - company-lsp--compute-flex-match                     1   0%
               - company-lsp--completion-prefix                     1   0%
                - company-lsp--trigger-characters                   1   0%
                 - lsp--capability                                  1   0%
                  - lsp--server-capabilities                        1   0%
                   - apply                                          1   0%
                      ht-merge                                      1   0%
        - company-safe-substring                                    1   0%
           generate-new-buffer                                      1   0%
       - company-call-backend                                       1   0%
        - company--force-sync                                       1   0%
         - apply                                                    1   0%
          - company-call-backend-raw                                1   0%
           - apply                                                  1   0%
            - company-lsp                                           1   0%
               lsp--annotate                                        1   0%
 - company-call-frontends                                          11   0%
  - company-pseudo-tooltip-unless-just-one-frontend                 11   0%
   - company-pseudo-tooltip-frontend                               11   0%
    - company--pseudo-tooltip-height                                7   0%
     - company--row                                                 6   0%
      - company--col-row                                            6   0%
       - posn-at-point                                              2   0%
        - eval                                                      1   0%
         - --filter                                                 1   0%
          - let                                                     1   0%
           - --each                                                 1   0%
            - let                                                   1   0%
             - while                                                1   0%
                let                                                 1   0%
        - jit-lock-function                                         1   0%
         - jit-lock-fontify-now                                     1   0%
          - jit-lock--run-functions                                 1   0%
           - run-hook-wrapped                                       1   0%
            - #<compiled 0x1ff9996c5af1>                            1   0%
             - font-lock-fontify-region                             1   0%
              - css--fontify-region                                 1   0%
               - font-lock-default-fontify-region                   1   0%
                  font-lock-fontify-keywords-region                  1   0%
         company--posn-col-row                                      1   0%
     - window-screen-lines                                          1   0%
      - default-line-height                                         1   0%
         default-font-height                                        1   0%
    - company-pseudo-tooltip-guard                                  4   0%
       beginning-of-visual-line                                     2   0%
       end-of-visual-line                                           2   0%
- ...                                                             890  26%
   Automatic GC                                                   890  26%
+ command-execute                                                 262   7%
+ #<compiled 0x1ff999916be1>                                       86   2%
+ lsp-ui-doc--make-request                                         84   2%
+ redisplay_internal (C function)                                  82   2%
+ beacon--post-command                                              2   0%
  internal-echo-keystrokes-prefix                                   1   0%
  display-line-numbers-update-width                                 1   0%
+ lsp--highlight                                                    1   0%
```

**Comment by yyoncho** [comment] 2019-05-22 05:00
From what I can see:

1. Increase the `gc-cons-threshold` e. g. `(setq gc-cons-threshold 100000000)`. This will prevent: 

>  Automatic GC                                                   890  26%

2. As you can see there is no lsp-mode related function and most of the time under company-post-command is spend in waiting for the response and in json parsing. Can you post the report with emacs27 since this is the only way to avoid that issue?

**Comment by resultingCorrespondence** [comment] 2019-05-22 05:12
1. Increasing the garbage collection threshold seems to have solved the problem! There's occasional lag (I'm guessing this is when garbage collection is occurring), but it is much better now.

2. This was done on emacs27

Thanks for the help!

**Comment by yyoncho** [comment] 2019-05-22 06:02
> This was done on emacs27

This means that the emacs version that you are using is not compiled with the native json support. You may verify that by running `(fboundp 'json-parse-string)`. I would recommend filing a feature request against the maintainer of emacs-snapshot that you are installing (assuming that you are installing a package) or you could manually build it from sources. This will yield ~4 times speedup.

PS: can you update the reddit post with our findings?

I am closing the issue since it looks like the issue is solved, I will mention our findings in the readme. Probably a lot of users have hit that issue too.

**Closed by yyoncho** 2019-05-22 06:02 UTC

**Comment by resultingCorrespondence** [comment] 2019-05-22 13:56
You're correct. It looks like it was compiled without native json parsing. I'll look into compiling it myself, but upping the gc threshold was enough to make this usable regardless.

I updated the reddit thread! Thanks again for all your help!

**Comment by dgutov** [comment] 2019-05-22 15:32
@yyoncho Have you tried

```
(let ((gc-cons-threshold most-positive-fixnum))
  ...)
```

around strategic portions of the code? It showed a significant improvement in one project of mine, without asking the user to change that value globally.

**Comment by yyoncho** [comment] 2019-05-22 15:45
@dgutov thanks for pointing this out, I will try it.
