### ISSUE TITLE
💡should be displayed in the UI in the default configuration

### ISSUE THREAD

**Issue by matklad** [emacs-lsp/lsp-mode#1772] opened 2020-06-09 12:48 UTC
Hi!

Today it occurred to me that, in default configuration, lsp-mode does not indicate the presence of code action (usually signified with an 💡 icon in IDE):

![image](https://user-images.githubusercontent.com/1711539/84148429-471e3b00-aa5f-11ea-864f-eaaf9cbd04d5.png)

I want to argue moderately strongly that, in the default configuration, it makes sense to provide some sort of visual indication here. I understand the desire to keep most features opt-in via lsp ui, but the raison d'être of code actions is to let you know that you can apply some transformation you don't know is possible :) 

Not sure what's the Emacs way to expose this, but maybe drawing

```
💡(s-l a a) Unwrap Block  (and 3 more)
```

In the mini buffer would work?

**Comment by yyoncho** [comment] 2020-06-09 13:05
duplicate of https://github.com/emacs-lsp/lsp-mode/issues/1237

**Closed by yyoncho** 2020-06-09 13:05 UTC

**Comment by yyoncho** [comment] 2020-06-09 13:08
As a side note, your flymake version is old(we cannot have explicit dep on the correct version because flymake requires emacs 26 while we want to support emacs 25).
