### ISSUE TITLE
executable-find returns path for typescript-server, but lsp does not find it.

### ISSUE THREAD

**Issue by lshoravi** [emacs-lsp/lsp-mode#1380] opened 2020-02-04 10:53 UTC
On version lsp-mode 20200203 from melpa
**Describe the bug**
(executable-find "typescript-language-server") returns "/usr/bin/typescript-language-server", but lsp doesn't recognize it, and opts to install it anew. When trying to install it (by choosing ts-ls in the prompt), it fails with "Unable to find a way to install typescript".

**To Reproduce**
This is reproducable in the scratch buffer:
```
emacs -q
M-: (package-initialize)
M-: (require 'package)
M-: (require 'lsp)
M-x js-jsx-mode
M-: (executable-find "typescript-language-server") => "/usr/bin/typescript-language-server"
M-x lsp
```

**Expected behavior**
lsp either finds the language server, or correctly installs the server anew.

**Which Language Server did you use**
Typescript-server, as installed in the instructions by npm.

**OS**
Manjaro

**Error callstack**
toggle-debug-on-error on doing M-x lsp:
```
(cl-assertion-failed ((seq-every-p (apply-partially #'stringp) command) "Invalid command list"))
  cl--assertion-failed((seq-every-p (apply-partially #'stringp) command) "Invalid command list" nil nil)
  lsp-resolve-final-function(#f(compiled-function () #<bytecode 0x15731038ce01>))
  #f(compiled-function () #<bytecode 0x15731038e19d>)()
  lsp--server-binary-present\?(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x15731038e185>) :test\? #f(compiled-function () #<bytecode 0x15731038e19d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x15731038e1a9> :request-handlers #<hash-table equal 0/65 0x15731038e481> :response-handlers #<hash-table eql 0/65 0x15731038e4a1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x15731038e8c1> :action-handlers #<hash-table equal 0/65 0x15731038ecc1> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -3 :server-id jsts-ls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x15731038e4c1> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x15731038ce15>) :download-in-progress? nil :buffers nil))
  #f(compiled-function (d1) #<bytecode 0x1573103d923d>)(lsp--server-binary-present\?)
  -all\?(#f(compiled-function (d1) #<bytecode 0x1573103d923d>) (lsp--matching-clients\? lsp--server-binary-present\?))
  #f(compiled-function (x) #<bytecode 0x1573103d8f61>)(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x15731038e185>) :test\? #f(compiled-function () #<bytecode 0x15731038e19d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x15731038e1a9> :request-handlers #<hash-table equal 0/65 0x15731038e481> :response-handlers #<hash-table eql 0/65 0x15731038e4a1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x15731038e8c1> :action-handlers #<hash-table equal 0/65 0x15731038ecc1> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -3 :server-id jsts-ls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x15731038e4c1> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x15731038ce15>) :download-in-progress? nil :buffers nil))
  -filter(#f(compiled-function (x) #<bytecode 0x1573103d8f61>) (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...))
  lsp--filter-clients(#f(compiled-function (x) #<bytecode 0x1573103d8f61>))
  lsp(nil)
  funcall-interactively(lsp nil)
  call-interactively(lsp record nil)
  command-execute(lsp record)
  execute-extended-command(nil "lsp" "lsp")
  funcall-interactively(execute-extended-command nil "lsp" "lsp")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
There is no lsp-log to show.

**Comment by yyoncho** [comment] 2020-02-04 11:33
Unable to reproduce with clean install:

> emacs -q -l lsp-start-plain.el

**Comment by jbaum98** [comment] 2020-02-10 20:43
I'm also experiencing this issue, and I can reproduce this bug even with `emacs -Q`.

**Comment by jbaum98** [comment] 2020-02-10 20:58
My issue was that I installed `typescript-language-server`, but according to [this part](https://github.com/emacs-lsp/lsp-mode/blob/6bdb62c1e265c9e45d0085a2036e732c61f8133e/lsp-clients.el#L224-L232) you also need to install the `typescript` npm package. That fixed the issue for me.

**Comment by yyoncho** [comment] 2020-02-11 05:45
Closing based on @jbaum98 comment. @lshoravi please reopen if you are able to hit the issue using lsp-start-plain.el.

**Closed by yyoncho** 2020-02-11 05:45 UTC
Labels: Unable to reproduce, need-info

**Comment by jbaum98** [comment] 2020-02-11 05:54
I think this should probably be documented somewhere; it took me a while before I found the write spot in the code.

**Comment by yyoncho** [comment] 2020-02-11 05:55
@jbaum98 which part?

**Comment by jbaum98** [comment] 2020-02-11 05:59
That you need to install typescript in addition to the language server. I just wanted to use it to check JavaScript, so I didn't realize I had to install typescript, even though in hindsight it seems pretty clear.

**Comment by yyoncho** [comment] 2020-02-11 06:05
@jbaum98 this is documented in the readme.

**Comment by jbaum98** [comment] 2020-02-11 06:16
That is true! That'll teach to skim the readme too fast. Sorry for my mistake.

**Comment by tbtommyb** [comment] 2020-03-28 18:51
I am finding this on emacs 28 despite having installed typescript. I should be checking `(executable-find "tsserver")` returns a path, right?

**Comment by yyoncho** [comment] 2020-03-28 19:36
> I am finding this on emacs 28 despite having installed typescript. I should be checking `(executable-find "tsserver")` returns a path, right?

yes.

**Comment by tbtommyb** [comment] 2020-03-28 22:45
That returns a correct path to `tsserver`. I'd be grateful for any deugging pointers you could give.

**Comment by yyoncho** [comment] 2020-03-29 05:18
`(executable-find "typescript-language-server")` must return a path as well.

**Comment by tbtommyb** [comment] 2020-03-29 12:27
Yes, both do. In ~/.nvm/versions/node/v10.15.3/bin` if that is relevant. Does the fact I'm using nvm matter? It's the same node version as in the project directory.

**Comment by yyoncho** [comment] 2020-03-29 14:34
@tbtommyb please share what do you see in messages log and in `*lsp-log*`.

**Comment by tbtommyb** [comment] 2020-04-20 14:20
Sorry for the delay in replying. In messages:

```
LSP :: Download ts-ls started.
LSP :: Server ts-ls install process failed with the following error message: Unable to find a way to install typescript.
Check `*lsp-install*' and `*lsp-log*' buffer.
```
I don't have `*lsp-log*` for some reason.

**Comment by lshoravi** [comment] 2020-04-21 12:34
Just tried my hand at this again and this fixed it for me:

```
sudo npm remove -g javascript-typescript-langserver
sudo npm i -g typescript-language-server; sudo npm i -g typescript
```

In emacs:

```
package-list-packages
```

and then install updates

**Comment by hideuk** [comment] 2022-10-19 21:05
> Just tried my hand at this again and this fixed it for me:
> 
> ```
> sudo npm remove -g javascript-typescript-langserver
> sudo npm i -g typescript-language-server; sudo npm i -g typescript
> ```
> 
> In emacs:
> 
> ```
> package-list-packages
> ```
> 
> and then install updates

thanks, that works for me, for some reason, i have installed javascript-typescript-langserver before
