### ISSUE TITLE
Moving cursor is very slow

### ISSUE THREAD

**Issue by vn-ki** [emacs-lsp/lsp-mode#837] opened 2019-05-17 17:23 UTC
**Describe the bug**

Cursor feels sluggish and stops at times when moving around files. I use spacemacs with evil-mode, in case that matters.

**To Reproduce**
- Navigating in a very small project (python and go)
- Cursor starts feeling sluggish and stops at times

**Expected behavior**

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)

- lsp-python
- lsp-golang

**OS**
Which os do you use?

Linux

**Profiler**
<details>
<summary>
Profiler output
</summary>

```
- lsp-ui-doc--make-request                                        971  34%
 - lsp-ui-doc--hide-frame                                         681  24%
  - lsp-workspace-root                                            641  22%
   - f-ancestor-of?                                               414  14%
    - f-same?                                                     394  14%
     - f-canonical                                                353  12%
      - file-truename                                             347  12%
       - file-truename                                            278   9%
        - file-truename                                           216   7%
         - file-truename                                          182   6%
          - file-truename                                         136   4%
           - file-truename                                         90   3%
            - file-truename                                        57   2%
               file-truename                                       27   0%
       f-exists?                                                   27   0%
       f-expand                                                     3   0%
    + f-full                                                       20   0%
   + f-canonical                                                  227   8%
    lsp-ui-doc--get-frame                                           7   0%
  + #<compiled 0x1d1aba9>                                           6   0%
 - lsp--send-request-async                                        257   9%
  - lsp--make-message                                             254   9%
   - json-encode                                                  254   9%
    - json-encode-list                                            254   9%
     - json-encode-plist                                          254   9%
      - json-encode                                               176   6%
       - json-encode-list                                         172   6%
        - json-encode-plist                                       172   6%
         - json-encode                                            115   4%
          - json-encode-list                                      115   4%
           - json-encode-plist                                    111   3%
            - json-encode-key                                      92   3%
             - json-read-from-string                               75   2%
              + #<compiled 0x36cc489>                              65   2%
              + generate-new-buffer                                10   0%
               json-encode                                          4   0%
            + json-encode                                          19   0%
         + json-encode-key                                         57   2%
         json-encode-string                                         4   0%
      - json-encode-key                                            78   2%
       - json-read-from-string                                     72   2%
        + #<compiled 0x1d1a289>                                    66   2%
          generate-new-buffer                                       6   0%
    lsp--send-no-wait                                               3   0%
 + lsp--capability                                                  7   0%
 + lsp--buffer-uri                                                  6   0%
 + symbol-at-point                                                  3   0%
+ redisplay_internal (C function)                                 621  22%
+ timer-event-handler                                             497  17%
+ command-execute                                                 334  11%
+ #<compiled 0x2d42b15>                                           267   9%
+ eldoc-pre-command-refresh-echo-area                              29   1%
+ sp--save-pre-command-state                                       12   0%
+ winner-save-old-configurations                                   11   0%
+ lsp--highlight                                                   10   0%
+ evil-repeat-post-hook                                            10   0%
+ lsp-ui-sideline                                                   6   0%
+ evil-repeat-pre-hook                                              6   0%
+ flycheck-hide-error-buffer                                        6   0%
+ hl-paren-initiate-highlight                                       4   0%
  yas--post-command-handler                                         3   0%
+ evil--jump-hook                                                   3   0%
+ #<compiled 0x2a6dfb9>                                             3   0%
  company-post-command                                              3   0%
+ evil-escape-pre-command-hook                                      3   0%
+ flycheck-pos-tip-hide-messages                                    3   0%
  undefined                                                         3   0%
+ ...                                                               0   0%

```
</details>

**Comment by yyoncho** [comment] 2019-05-17 17:29
Can you set lsp-ui-doc-enable to nil, close and reopen the file and report back whether the issue has been solved?

**Comment by vn-ki** [comment] 2019-05-17 17:34
Yes, I can confirm that solves the sluggishness. Thanks for the quick reply and fix.

The doc was kind of a useful thing. Guess I can live without it. Is it possible to have it activate with a keybinding.

**Comment by yyoncho** [comment] 2019-05-17 17:38
We still need to fix that. I just wanted to confirm that this is what is causing the sluggishness on your system.

**Comment by vn-ki** [comment] 2019-05-17 17:41
@yyoncho In case it's important, in go files, it shows `LSP:: No identifier found` in the message in certain places, like at closing brackets.

**Comment by yyoncho** [comment] 2019-05-17 17:44
> To show it manually add a keybinding to the function lsp-ui-doc-show

You may use `K` in normal state for the standard help.

> @yyoncho In case it's important, in go files, it shows LSP:: No identifier found in the message in certain places, like at closing brackets.

go language servers break the lsp protocol by returning an error instead of returning nil. We may start eating the error istead of showing warning.

**Comment by yyoncho** [comment] 2019-05-18 18:43
Fixed with https://github.com/emacs-lsp/lsp-ui/commit/ffb104b6e16b6c6ef17b906aec9ffb0f9e372a94

**Closed by yyoncho** 2019-05-18 18:43 UTC

**Comment by danlamanna** [comment] 2021-05-19 04:41
I can reproduce this issue perfectly with the following setup:
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-18
```

**Comment by yyoncho** [comment] 2021-05-19 04:46
> I can reproduce this issue perfectly with the following setup:
> 
> ```
> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-18
> ```
> 
> Setting `lsp-ui-doc-enable` to `nil` fixes it.

there is nothing we can do without a profiler report.

**Comment by danlamanna** [comment] 2021-05-19 16:10
I started the CPU profiler and just held down up arrow, which froze for several seconds. After the cursor caught up I ran `M-x profiler-stop`. These were the results, it looks like maybe they're muddied by `counsel-M-x`.

```
                                                                        296  67% - command-execute
                                                                        296  67%  - funcall-interactively
                                                                        296  67%   - counsel-M-x
                                                                        233  53%    - ivy-read
                                                                        223  50%     - read-from-minibuffer
                                                                        148  33%      - ivy--queue-exhibit
                                                                        148  33%       - ivy--exhibit
                                                                        136  31%        - ivy--update-minibuffer
                                                                         73  16%         - ivy--filter
                                                                         73  16%          - ivy--re-filter
                                                                         68  15%           - cl-remove
                                                                         55  12%            - cl-delete
                                                                         52  11%               #<compiled 0x12793b6e6948feaa>
                                                                         61  13%         - ivy--format
                                                                         52  11%          - ivy-rich--counsel-M-x-transformer
                                                                         52  11%           - ivy-rich-format
                                                                         52  11%            - #<compiled -0x1c2b3aab100c1b89>
                                                                         52  11%             - ivy-rich-format-column
                                                                         44  10%              - ivy-rich-counsel-function-docstring
                                                                         44  10%               - documentation
                                                                         30   6%                - substitute-command-keys
                                                                         23   5%                 - #<compiled -0x1c8aca5090b8fd3b>
                                                                          3   0%                  - kill-buffer
                                                                          3   0%                   - replace-buffer-in-windows
                                                                          3   0%                    - unrecord-window-buffer
                                                                          3   0%                       assq-delete-all
                                                                          4   0%                 - substitute-command-keys
                                                                          4   0%                    #<compiled -0x1c8accd16e95653b>
                                                                          6   1%          - ivy--wnd-cands-to-str
                                                                          3   0%             mapcar
                                                                          3   0%           - +ivy-format-function-line-or-arrow
                                                                          3   0%            - if
                                                                          3   0%             - ivy-format-function-line
                                                                          3   0%              - ivy--format-function-generic
                                                                          3   0%               - #<compiled -0x8f43221be6d0d35>
                                                                          3   0%                - #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_98>
                                                                          3   0%                 - ivy--add-face
                                                                          3   0%                    colir-blend-face-background
                                                                          3   0%          - cl-subseq
                                                                          3   0%             seq-subseq
                                                                         12   2%        - ivy--insert-minibuffer
                                                                          3   0%           ivy--minibuffer-cleanup
                                                                          3   0%      - minibuffer-setup
                                                                          3   0%       - ivy--minibuffer-setup
                                                                          3   0%        - #<lambda 0xafa9f79cd1eb20>
                                                                          3   0%         - with-ivy-window
                                                                          3   0%          - with-selected-window
                                                                          3   0%           - let
                                                                          3   0%            - save-current-buffer
                                                                          3   0%             - unwind-protect
                                                                          3   0%              - progn
                                                                          3   0%               - select-window
                                                                          3   0%                - apply
                                                                          3   0%                   ad-Advice-select-window
                                                                          1   0%      - minibuffer-inactive-mode
                                                                          1   0%       - better-jumper-mode-cmhh
                                                                          1   0%        - add-hook
                                                                          1   0%           #<compiled 0x14b115bd5e67d5ce>
                                                                          7   1%     - ivy--reset-state
                                                                          3   0%        all-completions
                                                                          3   0%     - ivy-call
                                                                          3   0%      - counsel-M-x-action
                                                                          3   0%       - command-execute
                                                                          3   0%          funcall-interactively
                                                                         63  14%    - counsel--M-x-externs
                                                                         40   9%     - amx-update
                                                                         32   7%      - amx-rebuild-cache
                                                                          7   1%         #<compiled 0xeb93d3a199b4e0>
                                                                         23   5%     - amx-detect-new-commands
                                                                         20   4%        #<compiled -0x252f922c10ada75>
                                                                         37   8% - timer-event-handler
                                                                         37   8%  - apply
                                                                         35   7%   - amx-idle-update
                                                                         35   7%    - amx-update-if-needed
                                                                         35   7%     - amx-update
                                                                         35   7%      - amx-rebuild-cache
                                                                         22   5%         #<compiled 0xeb93d3a199b4e0>
                                                                          2   0%     #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_10>
                                                                         32   7% - lsp-ui-doc--make-request
                                                                         32   7%  - if
                                                                         32   7%   - progn
                                                                         32   7%    - let
                                                                         29   6%     - if
                                                                         20   4%      - lsp-ui-doc--hide-frame
                                                                         20   4%       - if
                                                                         19   4%        - progn
                                                                          7   1%         - if
                                                                          7   1%          - let
                                                                          7   1%             save-current-buffer
                                                                          1   0%        - lsp-ui-doc--get-frame
                                                                          1   0%           let
                                                                          4   0%      - if
                                                                          4   0%       - lsp-ui-doc--hide-frame
                                                                          4   0%        - if
                                                                          4   0%           progn
                                                                          3   0%     - or
                                                                          3   0%      - and
                                                                          3   0%       - symbol-at-point
                                                                          3   0%        - thing-at-point
                                                                          3   0%           bounds-of-thing-at-point
                                                                         26   5% - redisplay_internal (C function)
                                                                         16   3%  - jit-lock-function
                                                                         16   3%   - jit-lock-fontify-now
                                                                         16   3%    - jit-lock--run-functions
                                                                         16   3%     - #<compiled 0x1f23332369b9663e>
                                                                         13   2%      - highlight-indent-guides--guide-region
                                                                          4   0%       - font-lock-fontify-region
                                                                          4   0%          font-lock-default-fontify-region
                                                                          3   0%         syntax-ppss
                                                                          3   0%       - highlight-indent-guides--get-prev-guides
                                                                          3   0%          syntax-ppss
                                                                          3   0%         highlight-indent-guides--get-guides
                                                                          3   0%      - font-lock-fontify-region
                                                                          3   0%       - font-lock-default-fontify-region
                                                                          3   0%        - font-lock-fontify-keywords-region
                                                                          3   0%           #<compiled -0x6f977d773cdd887>
                                                                          7   1%  - eval
                                                                          7   1%   - doom-modeline-format--main
                                                                          7   1%    - list
                                                                          7   1%     - propertize
                                                                          7   1%      - list
                                                                          7   1%       - list
                                                                          7   1%        - list
                                                                          7   1%         - *
                                                                          4   0%          - let
                                                                          4   0%           - doom-modeline--font-width
                                                                          4   0%            - let
                                                                          4   0%             - face-all-attributes
                                                                          4   0%              - #<compiled 0xb5a4784f531a9ca>
                                                                          4   0%                 face-attribute
                                                                          3   0%          - string-width
                                                                          3   0%           - format-mode-line
                                                                          3   0%            - eval
                                                                          3   0%               doom-modeline-segment--major-mode
                                                                          3   0%  - xwidget-webkit-adjust-size-in-frame
                                                                          3   0%     walk-windows
                                                                         13   2% - sp--save-pre-command-state
                                                                         13   2%  - sp-point-in-string
                                                                         12   2%   - sp--syntax-ppss
                                                                         12   2%      syntax-ppss
                                                                         11   2%   posframe-run-hidehandler
                                                                          6   1% - lsp-ui-sideline
                                                                          6   1%  - if
                                                                          6   1%   - let*
                                                                          3   0%    - setq
                                                                          3   0%       run-with-idle-timer
                                                                          4   0%   winner-save-old-configurations
                                                                          4   0% - evil-repeat-pre-hook
                                                                          4   0%  - evil-repeat-type
                                                                          4   0%   - evil-get-command-property
                                                                          4   0%    - evil-has-command-property-p
                                                                          4   0%       evil-get-command-properties
                                                                          3   0%   gcmh-register-idle-gc
                                                                          3   0%   evil-escape-pre-command-hook
                                                                          3   0%   doom-first-input-hook-init-on-pre-command-hook-h
                                                                          0   0% - ...
                                                                          0   0%    Automatic GC
```

**Comment by yyoncho** [comment] 2021-05-19 16:28
> These were the results, it looks like maybe they're muddied by `counsel-M-x`.

Yes, can you assign profiler-report to shortcut to avoid that? Also, test if the slow down goes away after M-x lsp-disconnect.

**Comment by danlamanna** [comment] 2021-05-19 16:35
```
                                                                         23  48% - lsp-ui-doc--make-request
                                                                         23  48%  - if
                                                                         23  48%   - progn
                                                                         23  48%    - let
                                                                         23  48%     - if
                                                                          9  19%      - if
                                                                          9  19%       - lsp-ui-doc--hide-frame
                                                                          9  19%        - if
                                                                          9  19%           progn
                                                                          8  17%      - lsp-ui-doc--hide-frame
                                                                          5  10%       - if
                                                                          5  10%        - progn
                                                                          4   8%         - if
                                                                          4   8%            let
                                                                          8  17% - timer-event-handler
                                                                          8  17%  - apply
                                                                          8  17%     #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_10>
                                                                          6  12%   winner-save-old-configurations
                                                                          4   8% - #<lambda 0x886c35a0f37e5a2>
                                                                          4   8%  - while
                                                                          4   8%   - if
                                                                          4   8%    - let*
                                                                          4   8%     - if
                                                                          4   8%      - progn
                                                                          4   8%       - lsp--parser-on-message
                                                                          4   8%        - condition-case
                                                                          4   8%         - let
                                                                          4   8%          - let*
                                                                          4   8%           - let*
                                                                          4   8%            - lsp--get-message-type
                                                                          4   8%             - if
                                                                          4   8%                if
                                                                          3   6% - redisplay_internal (C function)
                                                                          3   6%    mode-line-default-help-echo
                                                                          3   6% - sp--save-pre-command-state
                                                                          3   6%  - sp-point-in-string
                                                                          3   6%   - sp--syntax-ppss
                                                                          3   6%      syntax-ppss
                                                                          0   0% - ...
                                                                          0   0%    Automatic GC
```

The slowdown does go away after running `lsp-disconnect`.

**Comment by yyoncho** [comment] 2021-05-19 16:37
@danlamanna can you report that in lsp-ui repo? I think that winner has to ignore lsp-ui changes as well.
