### ISSUE TITLE
Request automatically setup Kotlin like lsp-java does and debug for kotlin

### ISSUE THREAD

**Issue by cuhabaho** [emacs-lsp/lsp-mode#988] opened 2019-08-27 01:46 UTC
I having been using lsp-mode for awhile now and i believe that setting up kotlin is a bit quite difficult and take lot of step. So my suggestion is that if it is possible, it should automatically setup itself. Furthermore, there is no dap for kotlin yet, I just hope it will be there soon if possible because without debugging, coding is quite tough to find bug. Thanks.

**Comment by yyoncho** [comment] 2019-09-03 19:06
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/506 . Usually, the automatic installer are implemented by someone that uses the language server, so if you want to give it a try, feel free to ping me.

**Closed by yyoncho** 2019-09-03 19:06 UTC
