### ISSUE TITLE
LSP doen't work on macOS with M1 chip (arm)

### ISSUE THREAD

**Issue by otavioschwanck** [emacs-lsp/lsp-mode#2707] opened 2021-03-11 22:33 UTC
Before logging the bug, please make sure that:

**Describe the bug**
LSP doens't start on m1 mac.  Tried a lot of different LSPs.

On *Messages*:
def-edebug-elem-spec: Edebug spec has to be a list: [[&rest (symbolp bindat-type &optional ":pack-val" def-form)] &optional ":unpack-val" def-form]

**To Reproduce**
run M-x lsp

**Expected behavior**
Start LSP.

**Which Language Server did you use**
solargraph, html-ls and javascript, all the same error

**OS**
macOS 2020 (m1 chip)

**Error callstack**
```
Debugger entered--Lisp error: (error "Edebug spec has to be a list: [[&rest (symbolp bin...")
  signal(error ("Edebug spec has to be a list: [[&rest (symbolp bin..."))
  error("Edebug spec has to be a list: %S" [[&rest (symbolp bindat-type &optional ":pack-val" def-form)] &optional ":unpack-val" def-form])
  def-edebug-elem-spec(bindat-struct [[&rest (symbolp bindat-type &optional ":pack-val" def-form)] &optional ":unpack-val" def-form])
  byte-code("\300\301\302\303#\304\301\305\306#\210\307\310\311\310\312\313#\314#\210\315\310\313\316\313\317%\210\315\310\313\320\313\321%\210\315\310\313\322\313\323%\210\315\310\313\324\313..." [function-put bindat--pcase lisp-indent-function 1 put edebug-form-spec pcase defalias bindat--type cl-generic-define (op head &rest args) nil "Return the code for the operation OP of the Bindat..." cl-generic-define-method (op (_ (eql byte))) #f(compiled-function (op _) #<bytecode -0x19623561274bf3ed>) (op (_ (eql uint)) n) #f(compiled-function (op _ n) #<bytecode -0x1ba6d966536ae528>) (op (_ (eql uintr)) n) #f(compiled-function (op _ n) #<bytecode -0x1ba6d9665307a528>) (op (_ (eql str)) len) #f(compiled-function (op _ len) #<bytecode -0x126dd320678991f5>) (op (_ (eql strz)) len) #f(compiled-function (op _ len) #<bytecode -0x126dd320434991f5>) (op (_ (eql bits)) len) #f(compiled-function (op _ len) #<bytecode -0x126dd32042098935>) (_op (_ (eql fill)) len) #f(compiled-function (op _ len) #<bytecode 0xa74f2397f7ea540>) (_op (_ (eql align)) len) #f(compiled-function (op _ len) #<bytecode -0x1119025ac6633532>) (op (_ (eql type)) exp) #f(compiled-function (op _ exp) #<bytecode -0xd71b0a6e0267b48>) (op (_ (eql vec)) count &rest type) #f(compiled-function 
  require(bindat)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315..." [require bindat cl-generic cl-lib compile dash ewoc f filenotify files ht imenu inline json lv markdown-mode network-stream pcase rx s seq spinner subr-x tree-widget url-parse url-util widget xref minibuffer yasnippet nil t lsp-protocol] 4)
  #<subr autoload-do-load>((autoload "lsp-mode" ("/Users/otavio/.emacs.d/.local/autoloads.28.0.50.el..." . 638702) t nil) lsp nil)
  apply(#<subr autoload-do-load> ((autoload "lsp-mode" ("/Users/otavio/.emacs.d/.local/autoloads.28.0.50.el..." . 638702) t nil) lsp))
  autoload-do-load((autoload "lsp-mode" ("/Users/otavio/.emacs.d/.local/autoloads.28.0.50.el..." . 638702) t nil) lsp)
  command-execute(lsp record)
  counsel-M-x-action("lsp")
  #f(compiled-function (x) #<bytecode -0x16754871832f4800>)("lsp")
  funcall(#f(compiled-function (x) #<bytecode -0x16754871832f4800>) "lsp")
  (if ivy-marked-candidates (ivy--call-marked action) (funcall action x))
  (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore))
  (prog1 (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore)) (if (or (eq ivy-exit 'done) (minibuffer-window-active-p (selected-window)) (null (active-minibuffer-window))) nil (select-window (active-minibuffer-window))))
  (cond ((null action) current) (t (select-window (ivy--get-window ivy-last)) (set-buffer (progn (or (progn (and (memq ... cl-struct-ivy-state-tags) t)) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 13))) (prog1 (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore)) (if (or (eq ivy-exit 'done) (minibuffer-window-active-p (selected-window)) (null (active-minibuffer-window))) nil (select-window (active-minibuffer-window))))))
  (let* ((action (if (functionp ivy-inhibit-action) ivy-inhibit-action (and (not ivy-inhibit-action) (ivy--get-action ivy-last)))) (current (progn (or (progn (and (memq ... cl-struct-ivy-state-tags) t)) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 23))) (x (ivy--call-cand current)) (res (cond ((null action) current) (t (select-window (ivy--get-window ivy-last)) (set-buffer (progn (or ... ...) (aref ivy-last 13))) (prog1 (unwind-protect (if ivy-marked-candidates ... ...) (ivy-recursive-restore)) (if (or ... ... ...) nil (select-window ...))))))) (if ivy-inhibit-action res current))
  ivy-call()
  (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not (window-minibuffer-p))) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil (let (...) (save-current-buffer ...))) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil (remove-hook 'minibuffer-setup-hook setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (let* ((hist ...) (minibuffer-completion-table collection) (minibuffer-completion-predicate predicate) (ivy-height ...) (resize-mini-windows ...)) (if (and ivy-auto-select-single-candidate ivy--all-candidates ...) (progn ... ...) (condition-case err ... ...)) (if (eq ivy-exit ...) (progn ...)))) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or (plist-get extra-props :session) (if (or ... ... ...) nil caller)))) (if session (progn (progn (or (progn ...) (signal ... ...)) (let* (...) (aset v 27 ...))) (ivy--alist-set 'ivy--sessions session ivy-last)))) (ivy--cleanup)) (ivy-call))
  (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not (window-minibuffer-p))) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil (let ... ...)) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil (remove-hook ... setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (let* (... ... ... ... ...) (if ... ... ...) (if ... ...))) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or (plist-get extra-props :session) (if ... nil caller)))) (if session (progn (progn (or ... ...) (let* ... ...)) (ivy--alist-set 'ivy--sessions session ivy-last)))) (ivy--cleanup)) (ivy-call)))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :multi-action :unwind :re-builder :matcher :dynamic-collection :extra-props :caller :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :requir..." (car --cl-keys--)))))) (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not ...)) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil ...) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil ... ...)) (unwind-protect (progn (add-hook ... setup-hook) (let* ... ... ...)) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or ... ...))) (if session (progn (progn ... ...) (ivy--alist-set ... session ivy-last)))) (ivy--cleanup)) (ivy-call))))
  (let* ((predicate (car (cdr (plist-member --cl-rest-- ':predicate)))) (require-match (car (cdr (plist-member --cl-rest-- ':require-match)))) (initial-input (car (cdr (plist-member --cl-rest-- ':initial-input)))) (history (car (cdr (plist-member --cl-rest-- ':history)))) (preselect (car (cdr (plist-member --cl-rest-- ':preselect)))) (def (car (cdr (plist-member --cl-rest-- ':def)))) (keymap (car (cdr (plist-member --cl-rest-- ':keymap)))) (update-fn (car (cdr (plist-member --cl-rest-- ':update-fn)))) (sort (car (cdr (plist-member --cl-rest-- ':sort)))) (action (car (cdr (plist-member --cl-rest-- ':action)))) (multi-action (car (cdr (plist-member --cl-rest-- ':multi-action)))) (unwind (car (cdr (plist-member --cl-rest-- ':unwind)))) (re-builder (car (cdr (plist-member --cl-rest-- ':re-builder)))) (matcher (car (cdr (plist-member --cl-rest-- ':matcher)))) (dynamic-collection (car (cdr (plist-member --cl-rest-- ':dynamic-collection)))) (extra-props (car (cdr (plist-member --cl-rest-- ':extra-props)))) (caller (car (cdr (plist-member --cl-rest-- ':caller))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :requir..." (car --cl-keys--)))))) (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last ...) (progn ...)))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn ...) #'... update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun ...) setup-hook) (setq setup-hook #'...) (unwind-protect (progn ... ...) (remove-hook ... setup-hook))) (let ((session ...)) (if session (progn ... ...))) (ivy--cleanup)) (ivy-call)))))
  (closure (cl-struct-ivy-state-tags t) (prompt collection &rest --cl-rest--) "Read a string in the minibuffer, with completion.\n..." (let* ((predicate (car (cdr (plist-member --cl-rest-- ...)))) (require-match (car (cdr (plist-member --cl-rest-- ...)))) (initial-input (car (cdr (plist-member --cl-rest-- ...)))) (history (car (cdr (plist-member --cl-rest-- ...)))) (preselect (car (cdr (plist-member --cl-rest-- ...)))) (def (car (cdr (plist-member --cl-rest-- ...)))) (keymap (car (cdr (plist-member --cl-rest-- ...)))) (update-fn (car (cdr (plist-member --cl-rest-- ...)))) (sort (car (cdr (plist-member --cl-rest-- ...)))) (action (car (cdr (plist-member --cl-rest-- ...)))) (multi-action (car (cdr (plist-member --cl-rest-- ...)))) (unwind (car (cdr (plist-member --cl-rest-- ...)))) (re-builder (car (cdr (plist-member --cl-rest-- ...)))) (matcher (car (cdr (plist-member --cl-rest-- ...)))) (dynamic-collection (car (cdr (plist-member --cl-rest-- ...)))) (extra-props (car (cdr (plist-member --cl-rest-- ...)))) (caller (car (cdr (plist-member --cl-rest-- ...))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond (... ...) (... ...) (t ...)))) (progn (let ((init-fn ...)) (if init-fn (progn ...))) (if (equal overriding-local-map '...) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last ...) (ivy--display-function ...)) (setq update-fn (or update-fn ...)) (setq unwind (or unwind ...)) (setq ivy-last (make-ivy-state :prompt ... :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn ... :sort sort :action ... :multi-action multi-action :frame ... :window ... :buffer ... :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn ... :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ... ... ...) (let ... ...) (ivy--cleanup)) (ivy-call))))))("M-x " ("toggle-debug-on-error" "lsp" "toggle-truncate-lines" "js2-mode" "org-mode" "otavio/rails-reset-all" "rspec-mode" "lsp-install-server" "projectile-discover-projects-in-directory" "load-theme" "projectile-run-shell" "lsp!" "vterm" "json-mode" "rbenv-use" "+vterm/toggle" "counsel-fonts" "vterm-module-compile" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deft" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" ...) :predicate #f(compiled-function (x) #<bytecode -0x1433cfbba07a4f72>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t)
  apply((closure (cl-struct-ivy-state-tags t) (prompt collection &rest --cl-rest--) "Read a string in the minibuffer, with completion.\n..." (let* ((predicate (car (cdr (plist-member --cl-rest-- ...)))) (require-match (car (cdr (plist-member --cl-rest-- ...)))) (initial-input (car (cdr (plist-member --cl-rest-- ...)))) (history (car (cdr (plist-member --cl-rest-- ...)))) (preselect (car (cdr (plist-member --cl-rest-- ...)))) (def (car (cdr (plist-member --cl-rest-- ...)))) (keymap (car (cdr (plist-member --cl-rest-- ...)))) (update-fn (car (cdr (plist-member --cl-rest-- ...)))) (sort (car (cdr (plist-member --cl-rest-- ...)))) (action (car (cdr (plist-member --cl-rest-- ...)))) (multi-action (car (cdr (plist-member --cl-rest-- ...)))) (unwind (car (cdr (plist-member --cl-rest-- ...)))) (re-builder (car (cdr (plist-member --cl-rest-- ...)))) (matcher (car (cdr (plist-member --cl-rest-- ...)))) (dynamic-collection (car (cdr (plist-member --cl-rest-- ...)))) (extra-props (car (cdr (plist-member --cl-rest-- ...)))) (caller (car (cdr (plist-member --cl-rest-- ...))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond (... ...) (... ...) (t ...)))) (progn (let ((init-fn ...)) (if init-fn (progn ...))) (if (equal overriding-local-map '...) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last ...) (ivy--display-function ...)) (setq update-fn (or update-fn ...)) (setq unwind (or unwind ...)) (setq ivy-last (make-ivy-state :prompt ... :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn ... :sort sort :action ... :multi-action multi-action :frame ... :window ... :buffer ... :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn ... :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ... ... ...) (let ... ...) (ivy--cleanup)) (ivy-call)))))) ("M-x " ("toggle-debug-on-error" "lsp" "toggle-truncate-lines" "js2-mode" "org-mode" "otavio/rails-reset-all" "rspec-mode" "lsp-install-server" "projectile-discover-projects-in-directory" "load-theme" "projectile-run-shell" "lsp!" "vterm" "json-mode" "rbenv-use" "+vterm/toggle" "counsel-fonts" "vterm-module-compile" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deft" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" ...) :predicate #f(compiled-function (x) #<bytecode -0x1433cfbba07a4f72>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t))
  ivy-read("M-x " ("toggle-debug-on-error" "lsp" "toggle-truncate-lines" "js2-mode" "org-mode" "otavio/rails-reset-all" "rspec-mode" "lsp-install-server" "projectile-discover-projects-in-directory" "load-theme" "projectile-run-shell" "lsp!" "vterm" "json-mode" "rbenv-use" "+vterm/toggle" "counsel-fonts" "vterm-module-compile" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deft" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" ...) :predicate #f(compiled-function (x) #<bytecode -0x1433cfbba07a4f72>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

EDIT:

I Think, this fixes
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b24c21e82ca0819f06ea5708274ce9091b3bc6d2

**Comment by leungbk** [comment] 2021-03-13 23:55
We had someone with the same issue the other day. Did updating to the latest rev of Emacs 28 solve your issue?

**Comment by yyoncho** [comment] 2021-03-14 07:09
as @leungbk  duplicate of https://github.com/emacs-lsp/lsp-mode/issues/2685

**Closed by yyoncho** 2021-03-14 07:09 UTC
