### ISSUE TITLE
Opening Vue file, cannot read property config of null

### ISSUE THREAD

**Issue by nobody-famous** [emacs-lsp/lsp-mode#739] opened 2019-03-28 00:56 UTC
**Describe the bug**
Error from the Language Server: Request initialize failed with message: Cannot read property 'config' of null (Internal Error)

**To Reproduce**
Added these lines to my init.el file,
(require 'lsp-mode)
(add-hook 'vue-mode-hook #'lsp)

Opening a Vue file causes the error to appear.

**Expected behavior**
To load the file correctly.

**Which Language Server did you use**
I'm using the Vue server.

**OS**
Windows 10

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

``` emacs-lisp
(setq lsp-print-io t)
```
For information about GNU Emacs and the GNU system, type C-h C-a.
Debug on Error enabled globally
Making completion list...
>>> vls:15584 status:starting(async)
Content-Length: 1922

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 37356,
    "rootPath": "c:/Users/rich/work/hellervb/php/",
    "rootUri": "file:///c:/Users/rich/work/hellervb/php/",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "executeCommand": {
          "dynamicRegistration": false
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "declaration": {
          "linkSupport": true
        },
        "definition": {
          "linkSupport": true
        },
        "implementation": {
          "linkSupport": true
        },
        "typeDefinition": {
          "linkSupport": true
        },
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          },
          "hierarchicalDocumentSymbolSupport": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": {
              "labelOffsetSupport": true
            }
          }
        }
      }
    },
    "initializationOptions": null
  },
  "id": 1
}
LSP :: Connected to [vls:15584 status:starting].
<<<< vls:15584 status:starting
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "Request initialize failed with message: Cannot read property 'config' of null"
  }
}
Error from the Language Server: Request initialize failed with message: Cannot read property ’config’ of null (Internal Error)

**Comment by yyoncho** [comment] 2019-03-28 05:42
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/727 . Take a look at the second comment, there is a solution but we need someone(vue user) to narrow it down and prepare a PR.

**Closed by yyoncho** 2019-03-28 05:42 UTC

**Comment by Qquanwei** [comment] 2019-05-15 07:46
I Have the same error

**Comment by yyoncho** [comment] 2019-05-15 07:49
@Qquanwei make sure that you are using the latest version of lsp related packages and if the issue is still there please collect the logs and provide a project + steps to reproduce.

**Comment by zwpdbh** [comment] 2019-05-22 07:33
Same error:
LSP :: Connected to [vls:217618 status:starting].
LSP :: Request initialize failed with message: Cannot read property 'config' of null

**Comment by yyoncho** [comment] 2019-05-22 07:34
@zwpdbh can you provide client-server logs + lsp-mode version that you are using + sample project to reproduce the issue?

**Comment by zwpdbh** [comment] 2019-05-22 07:37
Sorry, I am a newer to emacs.
So, how to print out the client-server logs.
lsp-mode           20190521.1509 dependency            LSP mode

**Comment by yyoncho** [comment] 2019-05-22 07:40
@zwpdbh if you are using the latest lsp-mode version then there is no need from logs. Can you provide a sample project to reproduce the issue(I have no vls knowledge).

**Comment by zwpdbh** [comment] 2019-05-22 07:46
The lsp-mode works very well with python, C/C++ and js. It is just has this error for vls.  I got assigned a task to do some development on other people's code. Currently, I don't have a sample project. I will provide one once I have a sample.  

Thanks for developing lsp-mode.

**Comment by yyoncho** [comment] 2019-05-22 07:48
@zwpdbh you are hitting https://github.com/vuejs/vetur/issues/977 but we should be able to fix it client side.

**Comment by zwpdbh** [comment] 2019-05-22 07:49
@yyoncho Thanks for reply so quickly! Such a great community :).  I love Emacs.

**Comment by yyoncho** [comment] 2019-05-22 19:00
@Qquanwei @zwpdbh https://github.com/emacs-lsp/lsp-mode/commit/0e3cee842243f9875a88735d9c04e46c2703efba should fix your issues.

**Comment by garyo** [comment] 2019-10-17 16:35
I'm trying to use this with `eglot` and running into the same issue. I had it working with older vls, but now things have changed and I'm not sure what the magic config data to pass is. Even when I pass a simple config object I get errors further along.
