### ISSUE TITLE
cl-assertion-failed ((functionp fetcher) for "go to definition"

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-lsp/lsp-mode#898] opened 2019-06-18 18:54 UTC
**Describe the bug**
With clangd, <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp-find-definition</kbd> results in results in this assertion.

**To Reproduce**
1. Make sure `clangd` is installed
2. Create `/tmp/foo/test.cpp` with this content
   ```c++
   void foo() {}

   int main() {
       foo();
   }

   ```
3. run `emacs -Q --eval "(package-initialize)" /tmp/foo/test.cpp`
4. run <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp</kbd> in Emacs *(you should see a message about clangd being started)*
5. Put caret over the `foo()` call, and call <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp-find-definition</kbd>.

**Expected behavior**
Emacs jumps to `void foo() {}` text.

**Which Language Server did you use**
`clangd` for C++ language

**OS**
Archlinux

**Error callstack**
```emacs-lisp
Debugger entered--Lisp error: (cl-assertion-failed ((functionp fetcher) nil))
  cl--assertion-failed((functionp fetcher))
  xref--show-xref-buffer((#<xref-item xref-item-155c3a848edc>) ((window . #<window 3 on test.cpp>) (display-action)))
  xref--show-xrefs((#<xref-item xref-item-155c3a848edc>) nil)
  lsp-find-locations("textDocument/definition" nil :display-action nil)
  lsp-find-definition()
  funcall-interactively(lsp-find-definition)
  call-interactively(lsp-find-definition record nil)
  command-execute(lsp-find-definition record)
  execute-extended-command(nil "lsp-find-definition")
  smex-read-and-run(("toggle-debug-on-error" "lsp-find-definition" "lsp" "load-file" "byte-compile-file" "byte-recompile-directory" "grep" "find-tag" "text-mode" "flycheck-mode" "server-start" "markdown-mode" "ar" "visit-tags-table" "re-builder" "csharp-mode" "eval-region" "smartparens-mode" "smerge-vc-next-conflict" "omnisharp-mode" "add-change-log-entry" "load-theme" "tags-search" "next-conflict" "yas-prev-field" "yas-reload-all" "emacs-lisp-mode" "show-smartparens-mode" "magit-add-change-log-entry" "magit" "sort-lines" "smerge-mode" "disable-theme" "c-sort-includes" "package-list-packages" "set-selective-display" "vc-dir" "sh-mode" "version" "ido-mode" "xml-mode" "vala-mode" "package-delete" "profiler-start" "yas-minor-mode" "latin-to-gothic" "show-paren-mode" "electric-pair-mode" "xref-find-definitions" "global-symbol-overlay-mode" ...))
  smex()
  funcall-interactively(smex)
  call-interactively(smex nil nil)
  command-execute(smex)
```

**Comment by yyoncho** [comment] 2019-06-18 19:20
Can you reproduce it using https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?

**Comment by Hi-Angel** [comment] 2019-06-18 19:36
> Can you reproduce it using https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?

Thank you, yes, here's the stacktrace from there:

```emacs-lisp
Debugger entered--Lisp error: (cl-assertion-failed ((functionp fetcher) nil))
  cl--assertion-failed((functionp fetcher))
  xref--show-xref-buffer((#<xref-item xref-item-1580b06f23f8>) ((window . #<window 3 on test.cpp>) (display-action)))
  xref--show-xrefs((#<xref-item xref-item-1580b06f23f8>) nil)
  (if loc (xref--show-xrefs (lsp--locations-to-xref-items (if (sequencep loc) loc (list loc))) display-action) (message "Not found for: %s" (thing-at-point 'symbol t)))
  (let ((loc (lsp-request method (append (list :textDocument (or nil (list :uri ...)) :position (or nil (save-restriction ... ...))) extra)))) (if loc (xref--show-xrefs (lsp--locations-to-xref-items (if (sequencep loc) loc (list loc))) display-action) (message "Not found for: %s" (thing-at-point 'symbol t))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:display-action :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:display-action)" (car --cl-keys--)))))) (let ((loc (lsp-request method (append (list :textDocument (or nil ...) :position (or nil ...)) extra)))) (if loc (xref--show-xrefs (lsp--locations-to-xref-items (if (sequencep loc) loc (list loc))) display-action) (message "Not found for: %s" (thing-at-point 'symbol t)))))
  (let* ((display-action (car (cdr (plist-member --cl-rest-- ':display-action))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:display-action)" (car --cl-keys--)))))) (let ((loc (lsp-request method (append (list :textDocument ... :position ...) extra)))) (if loc (xref--show-xrefs (lsp--locations-to-xref-items (if (sequencep loc) loc (list loc))) display-action) (message "Not found for: %s" (thing-at-point 'symbol t))))))
  lsp-find-locations("textDocument/definition" nil :display-action nil)
  (progn (if (lsp--capability "definitionProvider") nil (signal 'lsp-capability-not-supported (list "definitionProvider"))) (lsp-find-locations "textDocument/definition" nil :display-action display-action))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:display-action :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:display-action)" (car --cl-keys--)))))) (progn (if (lsp--capability "definitionProvider") nil (signal 'lsp-capability-not-supported (list "definitionProvider"))) (lsp-find-locations "textDocument/definition" nil :display-action display-action)))
  (let* ((display-action (car (cdr (plist-member --cl-rest-- ':display-action))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:display-action)" (car --cl-keys--)))))) (progn (if (lsp--capability "definitionProvider") nil (signal 'lsp-capability-not-supported (list "definitionProvider"))) (lsp-find-locations "textDocument/definition" nil :display-action display-action))))
  lsp-find-definition()
  funcall-interactively(lsp-find-definition)
  call-interactively(lsp-find-definition record nil)
  command-execute(lsp-find-definition record)
  execute-extended-command(nil "lsp-find-definition" nil)
  funcall-interactively(execute-extended-command nil "lsp-find-definition" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by yyoncho** [comment] 2019-06-18 19:42
I assume that you have started it via `emacs -q -l lsp-start-plain.el`, right?

**Comment by Hi-Angel** [comment] 2019-06-18 19:45
> I assume that you have started it via `emacs -q -l lsp-start-plain.el`, right?

With big `-Q` though. But I just retested as you wrote, it results in the same.

**Comment by yyoncho** [comment] 2019-06-18 19:49
Which version of emacs do you use?

**Comment by Hi-Angel** [comment] 2019-06-18 19:50
It's from git, 27.0.50 of 2019-06-16

Since I'm running git version, I decided to give a try to REmacs that is based on older Emacs code. The `lsp-find-definition` doesn't work there too, the error is different though.

**Comment by yyoncho** [comment] 2019-06-18 19:54
I thi

**Comment by Hi-Angel** [comment] 2019-06-18 19:58
Thank you! I can try bisecting too if it's a known problem.

**Comment by yyoncho** [comment] 2019-06-18 20:07
Fyi remacs does not work out of the box since JSON.c is not synched with GNU emacs version and you should disable native JSON parsing .

**Comment by yyoncho** [comment] 2019-06-19 04:19
I tested with the latest emacs and I am unable to repro the issue. IMO it is already fixed, probably by 

```
83095a89f6 * Fix regressions in xref-find-definitions and ...-other-window
```

or 

```
5f5555da87 * Unbreak saving xref--original-window, etc
``` 

(cc @dgutov).

**Comment by Hi-Angel** [comment] 2019-06-19 06:55
Well, this is odd :( I just rebuilt Emacs from latest upstream, and doing `src/emacs -q -l lsp-start-plain.el` from the build directory results in the same for me.

Anyway, thank you! I'll try to figure out it later myself then.

**Comment by dgutov** [comment] 2019-06-19 08:46
> 5f5555da87 * Unbreak saving xref--original-window, etc

Probably this one, yes.

@Hi-Angel What's the revision that you are using?

**Comment by Hi-Angel** [comment] 2019-06-19 09:15
> > 5f5555da87 * Unbreak saving xref--original-window, etc
> 
> Probably this one, yes.
> 
> @Hi-Angel What's the revision that you are using?

The last one that I re-tested from a build directory was at [ef23c8be70d2cdc51b7f117ab3b4ad2f16b4ecdc](https://github.com/emacs-mirror/emacs/commit/ef23c8be70d2cdc51b7f117ab3b4ad2f16b4ecdc).

**Comment by Hi-Angel** [comment] 2019-06-19 11:08
Could please someone, for whom everything works fine, test the following:

1. evaluate this version of [xref--show-xrefs](https://github.com/emacs-mirror/emacs/blob/2419fa3937f07f8e2e4a79f77fe367a9979cb578/lisp/progmodes/xref.el#L905)
    ```emacs-lisp
    (defun xref--show-xrefs (fetcher display-action)
      (setq global-fetcher fetcher)
      (xref--push-markers)
      (funcall xref-show-xrefs-function fetcher
               `((window . ,(selected-window))
                 (display-action . ,display-action))))
    ```
2. Repeat the report steps.
3. Do <kbd>M</kbd><kbd>S</kbd>-<kbd>e</kbd> `(functionp global-fetcher)`, and tell if it's `t` or `nil`?

**Comment by dgutov** [comment] 2019-06-19 11:09
Ah, sorry. I have read the backtrace properly now. The problem is in `lsp-mode`.

@yyoncho I'm sorry to say but `xref--show-xrefs` has been changed in Emacs 27 to accept a function as its first argument. It's a private function, so we can do that.

You're doing something wrong here anyway: instead of just defining the required backend methods and letting xref call them, you've written your own commands. That might be helpful in certain cases, but I don't see how it's necessary here.

**Comment by yyoncho** [comment] 2019-06-19 12:03
We have created the lsp-find-* methods due to the fact that lsp-mode does not support picking up the identifier at the point - see https://github.com/emacs-lsp/lsp-mode/issues/466 . Also, there are methods which xref does not support as far as I know (e. g. there is no xref-find-implementations).

> @yyoncho I'm sorry to say but xref--show-xrefs has been changed in Emacs 27 to accept a function as its first argument. It's a private function, so we can do that.

I agree, we did that as a workaround. On the other hand `xref-show-definitions-function` is public and these changes break `helm-xref` and `ivy-xref` and maybe other packages. (See https://github.com/brotzeit/helm-xref/blob/master/helm-xref.el#L117 )

**Comment by dgutov** [comment] 2019-06-19 12:50
> lsp-mode does not support picking up the identifier at the point

That seems to mean that you can't properly support `xref-prompt-for-identifier`. That is unfortunate. Is there a corresponding feature request for LSP already?

You can tell the users to bind it to nil. Or your wrappers can call the original commands instead of the private function (then the prompt won't be used anyway). And the backend methods can ignore the first argument.

> there are methods which xref does not support as far as I know (e. g. there is no xref-find-implementations)

There are different options for solving this, but most would start with filing a bug report.

> these changes break helm-xref and ivy-xref

See https://github.com/alexmurray/ivy-xref/pull/20/. Someone should update helm-xref accordingly. The breakage is unfortunate, but it still seems like the best option.

**Comment by dgutov** [comment] 2019-06-19 13:00
> And the backend methods can ignore the first argument.

Or they can check and make sure that it's the same identifier that is under point. And otherwise apologize and tell the user to change the value of `xref-show-definitions-function`. This particular behavior can vary by command or even by language server (if some do provide support for entering the identifier explicitly).

**Comment by yyoncho** [comment] 2019-06-19 17:54
@dgutov 
> Is there a corresponding feature request for LSP already?

AFAIK no. I doubt that such a feature request will be addressed since the protocol is primary focused on vscode needs.

> Or your wrappers can call the original commands instead of the private function (then the prompt won't be used anyway)

That is a good idea, thanks. Since we need to find a solution about the methods that do not have xref equivalents I am planning to do something like this 

```
(defun lsp-find-implementations ()
  (interactive)

  (let ((lsp-method-to-execute "implementations"))
    (xref-find-definitions nil)))
```
and then use `lsp-method-to-execute` in the backend. We will need that workaround even if the issue is fixed in emacs 27 since we support emacs 25. What do you think? 

> Or they can check and make sure that it's the same identifier that is under point. 

There is no way to do that correctly using lsp as of now and we generally avoid approximations like thing-at-point

**Comment by dgutov** [comment] 2019-06-19 19:15
> I doubt that such a feature request will be addressed since the protocol is primary focused on vscode needs.

Maybe they would suddenly become inspired and decide to add such feature to VS Code :-)

Or suggest some alternative approach.

> and then use lsp-method-to-execute in the backend

Yup, sounds good to me.

> we generally avoid approximations like thing-at-point

Wasn't there some thing like server capability/trigger characters? Though it probably doesn't fully describe the grammar.

**Comment by yyoncho** [comment] 2019-06-23 06:34
@dgutov it turns out that the approach 
```
  (let ((lsp-method-to-execute "implementations"))
    (xref-find-definitions nil)))
```

does not work well since when there are no implementations I get a misleading error that there are no definitions instead of implementations. I was thinking about using directly `xref-show-xrefs-function` and using some heuristics to check whether to pass fetcher or list of xrefs, what do you think?

**Comment by dgutov** [comment] 2019-06-24 13:14
That should work, sure.

Or if you're feeling lazy and maybe willing to tackle a similar compatibility problem later, you could call `xref--find-xrefs` instead (I think its signature hasn't changed since Xref was introduced).

**Comment by yyoncho** [comment] 2019-06-24 20:06
@dgutov 

Thanks for the pointer. I will use `xref--find-xrefs` to close that issue and then are you open on discussing changes in `xref.el` to cover lsp-mode use cases using Emacs public API?

**Comment by dgutov** [comment] 2019-06-25 09:43
Sure, always open.

**Closed** 2019-06-28 06:18 UTC

**Comment by yyoncho** [comment] 2019-06-28 06:27
@dgutov 

 xref--find-xrefs solution had the same problem described in https://github.com/emacs-lsp/lsp-mode/issues/898#issuecomment-504724646 so I patched the code to check whether there is xref--create-fetcher and use xrefs or fetcher.

About the long term solution, it seems like something simple like making xref--show-xrefs public will do the job for us. What we need is the ability to bypass the identifier selection and ability to define custom methods(e. g. find implementations).

**Comment by dgutov** [comment] 2019-06-28 13:02
It can hardly be the same error, considering you pass KIND to `xref--find-xrefs` as one of the arguments. And the name of that symbol is used in the error message. Though now I see a different issue: it can be problematic if `xref-backend-identifier-at-point` returns nil for your backend.

`xref--show-xrefs` can be made public, but if you look at its definition, does it really offer much over `(funcall xref-show-xrefs-function ...`?

**Comment by dgutov** [comment] 2019-06-28 13:05
FTR, I'd rather have a more detailed discussion about "implementations", "type definitions", and so on. In particular, to improve documentation to say whether any of them should be included in the list of definitions. And whether definitions are also references. And so on.

**Comment by yyoncho** [comment] 2019-06-28 13:22
I meant that if I call xref--find-xrefs with kind=definitions I will end up with the same error. Of course, I could call it with type=implementations and implement implementations backend but I thought that I will have to write too much code depending on internal which will potentially change after we extend the 27 public API.

 > In particular, to improve documentation to say whether any of them should be included in the list of definitions.

Do you mean showing implementations as part of definitions result?

**Comment by dgutov** [comment] 2019-06-28 13:29
> Of course, I could call it with type=implementations and implement implementations backend

That's the idea, yes.

> I will have to write too much code depending on internal which will potentially change

Why would the usefulness of this backend command diminish later? Even if some things change, you could call it yourself anyway. But having a backend method like that would fit nicely in the overall design.

> Do you mean showing implementations as part of definitions result?

Yes. Irrespective of a particular backend, we should have a meaningful guideline on whether this should happen.

**Comment by muirrn** [comment] 2019-06-28 17:46
I'm seeing this error for `lsp-find-type-definition` in Emacs 27. Is there something I can do to work around it for now?

```
Debugger entered--Lisp error: (cl-assertion-failed ((functionp fetcher) nil))
  cl--assertion-failed((functionp fetcher))
  xref--show-xref-buffer((#<xref-item xref-item-1ffdedd42df8>) ((window . #<window 8 on track_heatmap.go>) (display-action)))
  xref--show-xrefs((#<xref-item xref-item-1ffdedd42df8>) nil)
  lsp-find-locations("textDocument/typeDefinition" nil :display-action nil)
  lsp-find-type-definition()
  funcall-interactively(lsp-find-type-definition)
  call-interactively(lsp-find-type-definition nil nil)
  command-execute(lsp-find-type-definition)
  recursive-edit()
  debug(error (cl-assertion-failed ((functionp fetcher) nil)))
  cl--assertion-failed((functionp fetcher))
  xref--show-xref-buffer((#<xref-item xref-item-1ffdede3f4e4>) ((window . #<window 6>) (display-action)))
  xref--show-xrefs((#<xref-item xref-item-1ffdede3f4e4>) nil)
  lsp-find-locations("textDocument/typeDefinition" nil :display-action nil)
  lsp-find-type-definition()
  funcall-interactively(lsp-find-type-definition)
  call-interactively(lsp-find-type-definition nil nil)
  command-execute(lsp-find-type-definition)
```

**Comment by yyoncho** [comment] 2019-06-28 18:01
@muirrn do you have https://github.com/emacs-lsp/lsp-mode/commit/4709ef307e89983e8d7f48245a25dc0e7ff47f81 ?

**Comment by muirrn** [comment] 2019-06-28 18:08
> do you have 4709ef3 ?

No. That fixed the error, but now it doesn't jump me to the type definition (I get a buffer with a list of 1 results).

**Comment by yyoncho** [comment] 2019-06-28 18:50
@muirrn fixed with e1d8b3796479a17155a8c034b81896dbad469907

**Comment by dgutov** [comment] 2019-06-28 19:19
@yyoncho Does the latest change apply to references as well?

**Comment by yyoncho** [comment] 2019-06-28 19:22
Yes, we are using `lsp-find-locations` in all `lsp-find-*` methods. Do you have something in mind?

**Comment by dgutov** [comment] 2019-06-28 19:36
Well, just for the record, changing this was the intention of https://github.com/emacs-mirror/emacs/commit/49a363c875c66f3d937a7d33e1a1451227a1887d#diff-70d6ffadd6eef3fbb0ff1012d68a14b5. It's too bad you have to go around the default behaviors.

So the idea is, it's fine to jump to the location right away when it's jump-to-definition. In other cases, the user is most likely expecting to see a list of results, even if it's just one. I think lsp-ui-peek has a related customization.

**Comment by Hi-Angel** [comment] 2019-06-28 19:43
> In other cases, the user is most likely expecting to see a list of results, even if it's just one

I can imagine only one usecase when it's something a user would expect: executing a command to show references. For anything else I'd expect the jump; and the case where there are multiple possible candidates is an exception, which requires showing the buffer with list.

**Comment by Hi-Angel** [comment] 2019-06-28 19:48
In retrospective, though, I think it would be nice to call `lsp-find-something` functions either `lsp-goto-something` or `lsp-show-someting`. This would fend off possible discussions about what exactly the function should do.

**Comment by yyoncho** [comment] 2019-06-28 20:00
@dgutov I see. I am fine with emacs core driving the user experience and lsp-mode complying with it when we are talking about the built-in stuff like xref which I believe will happen once lsp-mode integration is fixed. I second @Hi-Angel opinion that showing one result make sense only for references. I would expect to jump right away for implementations/type definitions, etc.

**Comment by dgutov** [comment] 2019-06-28 22:19
*shrug* Implementations and type-definitions are commands not familiar to me. So you could very well be right about those. Maybe `lsp-mode` should call `xref-show-definitions-function` for those.

Regarding separate commands, that could help, but that doesn't solve the question of what `M-.` should do. Or the default bindings for the other navigations.

**Comment by yyoncho** [comment] 2019-06-29 05:56
@dgutov pushed https://github.com/emacs-lsp/lsp-mode/commit/194e5623602e3545757fe299fe2ec79b7a95d9b8 which now uses xref-show-definitions-function and xref-show-xrefs-function .

> Regarding separate commands, that could help, but that doesn't solve the question of what M-. should do. Or the default bindings for the other navigations. 

I wonder whether to remap xref-find-definitions to lsp-find-definitions in lsp-mode-map. About the bindings - we leave that up to the users, lsp-mode-map is empty.

**Comment by dgutov** [comment] 2019-06-29 22:16
@yyoncho I don't understand the hesitation. The original bindings don't work with your xref backend anyway, right? So rebinding them makes sense.

On the other hand, I would seriously consider removing the backend, considering it's not used as intended by the xref API, for extra clarity.

**Comment by yyoncho** [comment] 2019-06-30 10:36
> @yyoncho I don't understand the hesitation. The original bindings don't work with your xref backend anyway, right? So rebinding them makes sense.
> 
> On the other hand, I would seriously consider removing the backend, considering it's not used as intended by the xref API, for extra clarity.

I agree. I haven't got the time to work on that.
