### ISSUE TITLE
lsp-erlang won't start when visiting a path that includes space characters

### ISSUE THREAD

**Issue by stormwatch** [emacs-lsp/lsp-mode#1657] opened 2020-05-05 07:33 UTC
# Description
After loading an Erlang file with lsp-mode enabled and erlang_ls installed, the minibuffer will show
> unexpected error while initialize

with the mode-line displaying:
> status:starting

indefinitely

# Steps to reproduce
1. Install https://github.com/erlang-ls/erlang_ls
2. Visit an Erlang file. For example:
```erlang
-module(first).
-export([double/1,mult/2,area/3]).

mult(X,Y) ->
    X*Y.

double(X) ->
    mult(2,X).

area(A,B,C) ->
    S = (A+B+C)/2,
    math:sqrt(S*(S-A)*(S-B)*(S-C)).
```
3. Run `lsp`

# Details
The erlang_ls binary is being invoked:
```
[I] ➜ ps x|grep erlang
  26170 ?        S      0:00 /usr/lib64/erlang/erts-10.7.1/bin/epmd -daemon
  77885 ?        Ssl    0:04 /usr/local/bin/erlang_ls -B -- -root /usr/lib64/erlang -progname erl -- -home /home/eze -- -boot no_dot_erlang -noshell -connect_all false -run escript start -- -extra /usr/local/bin/erlang_ls --transport stdio
```

## OS
Fedora 32

### \*lsp-log\*
> Command "erlang_ls --transport stdio" is present on the path.
> Command "erlang_ls --transport stdio" is present on the path.
> Found the following clients for /usr/local/src/cursos/Erlang/2020 Thompson/first.erl: (server-id erlang-ls, priority -1)
> The following clients were selected based on priority: (server-id erlang-ls, priority -1)
> Command "erlang_ls --transport stdio" is present on the path.
> Command "erlang_ls --transport stdio" is present on the path.
> Found the following clients for /usr/local/src/cursos/Erlang/2020 Thompson/first.erl: (server-id erlang-ls, priority -1)
> The following clients were selected based on priority: (server-id erlang-ls, priority -1)

### `lsp-workspace-show-log`
A sample [\*lsp-log: erlang-ls:55758\*](https://github.com/emacs-lsp/lsp-mode/files/4579230/lsp-log.erlang-ls.log)

**\*erlang-ls::stderr\*** remains empty.

**Comment by stormwatch** [comment] 2020-05-05 07:41
May I summon @robertoaloi and @alanz?

**Comment by robertoaloi** [comment] 2020-05-05 09:06
Out of curiosity, could you try running the server in a path which does not contain a space (as in `2020 Thompson`)?

**Comment by stormwatch** [comment] 2020-05-05 18:47
> Out of curiosity, could you try running the server in a path which does not contain a space (as in `2020 Thompson`)?

If the path doesn't contain spaces lsp starts fine. I'll rename the issue accordingly

**Comment by yyoncho** [comment] 2020-05-05 18:49
@alanz with latest findings seems like the issue is on the server? Or lsp-mode is not passing the paths correctly?

**Comment by alanz** [comment] 2020-05-05 19:03
Closing in favour of https://github.com/erlang-ls/erlang_ls/issues/725

**Closed by alanz** 2020-05-05 19:03 UTC
