### ISSUE TITLE
lsp-rename garbles names instead of renaming if the file contains unicode characters

### ISSUE THREAD

**Issue by lorenzhs** [emacs-lsp/lsp-mode#980] opened 2019-08-21 14:03 UTC
**Describe the bug**
In files containing non-ASCII characters (I tested with the character `ü`), lsp-rename fails to correctly apply the language server's response.

**To Reproduce**
Using emacs 26.1 and lsp-rename from the master branch, try renaming the class in `foo_before.hpp` of the gist linked below.

**Expected behavior**
Should rename the class without garbling the name. I ran `M-x lsp-rename something_else`, point was at the end of `my_class_name` in line 3. The result was `soys_hingcease`.

**Which Language Server did you use**
clangd, both `clangd version 8.0.1-3+b1 (tags/RELEASE_801/final)` and `clangd version 9.0.0-+rc2-1~exp1 (tags/RELEASE_900/rc2)` from the Debian packages `clangd-8` (in sid) and `clangd-9` (in experimental) show the same behaviour. I'd wager that it's not their fault, as they return the correct replacements, but `lsp-mode` applies them incorrectly.

**OS**
Debian unstable (amd64)

**Error callstack**
No errors, the language server (clangd) seems to work correctly: https://gist.github.com/lorenzhs/6c863855426850ddcb0d9d9862c2f887  - gist also contains a before/after of the input file. The issue is reproducible using `lsp-start-plain.el` (see the second log in the gist).

See also the comments on #864

**Comment by yyoncho** [comment] 2019-08-21 17:32
I reproduced the issue, here it is a workaround you could use until the proper fix is in.

```
  (defun lsp--apply-text-edits (edits)
  "Apply the edits described in the TextEdit[] object.
This method is used if we do not have `buffer-replace-content'."
  (unless (seq-empty-p edits)
    (atomic-change-group
      (run-hooks 'lsp-before-apply-edits-hook)
      (let* ((change-group (when (functionp 'undo-amalgamate-change-group)
                             (prepare-change-group)))
             (howmany (length edits))
             (reporter (make-progress-reporter
                        (lsp--info "Applying %s edits to `%s'..."
                                   howmany (current-buffer))
                        0 howmany))
             (done 0)
             (apply-edit 'lsp--apply-text-edit))
        (unwind-protect
            (->> edits
                 (nreverse)
                 (seq-sort #'lsp--text-edit-sort-predicate)
                 (mapc (lambda (edit)
                         (progress-reporter-update reporter (cl-incf done))
                         (funcall apply-edit edit))))
          (when (functionp 'undo-amalgamate-change-group)
            (with-no-warnings (undo-amalgamate-change-group change-group)))
          (progress-reporter-done reporter))))))
```

**Comment by yyoncho** [comment] 2019-08-22 05:15
So the issue is that `buffer-replace-string` does not work when there are unicode characters in emacs26.1(it works fine with 26.2/27)

CC @Eli-Zaretskii to comment/confirm.

Steps to reproduce:

Have buffer:
```
// ü

struct my_test_class {
  my_test_class() {}
};

```

Script to run
``` elisp
(with-temp-buffer
  (insert "something_else")
  (let ((temp (current-buffer)))
    (with-current-buffer "hello.cpp"
      (save-excursion
        (save-restriction
          (narrow-to-region 14 27)
          (replace-buffer-contents temp))))))
```

This yields:
```
// ü

struct soys_hingcease {
  my_test_class() {}
};

```
instead of
```
// ü

struct something_else {
  my_test_class() {}
};

```
Here it is docker file which can be used to run emacs instance 26.1
```
FROM debian:unstable

RUN echo deb http://deb.debian.org/debian experimental main >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get -t experimental install emacs -y
```

**Closed** 2019-08-22 06:52 UTC
Labels: upstream, workaround

**Comment by Eli-Zaretskii** [comment] 2019-08-22 14:00
I can indeed reproduce in Emacs 26.1, but not in 26.2 or later.

Quite a few bugs and misfeatures in `replace-buffer-contents` were fixed post-26.1, so I suggest to upgrade (especially since 26.3 will be out VSN).

**Comment by lorenzhs** [comment] 2019-08-22 14:29
Yeah, the Debian package is still stuck at 26.1. Seeing as that took a long time to land because of copyright questions, I might just build from source instead of waiting.

**Comment by yyoncho** [comment] 2019-08-23 12:57
@Eli-Zaretskii thank you!
