### ISSUE TITLE
autocomplete not working in F#

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/lsp-mode#3371] opened 2022-02-25 11:14 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Hi,

I wanna to tinker with F# so I tried installing packages for lspp F# and start with simple program but was unable to get autocomplete working.

I include several output which  may be needed for debugging. Please let me know if you need another.

[files.zip](https://github.com/emacs-lsp/lsp-mode/files/8140582/files.zip)

### Steps to reproduce

- Create new F# project with dotnet cli tool (https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line)
- Open file src/Library.fs 
- Try to type some keyword to trigger autocomplete.

### Expected behavior

suggestions list appears

### Which Language Server did you use?

fsac

### OS

Linux

### Error callstack

```emacs-lisp
fsac:15852 initialized successfully in folders: (/home/serezlan/Workspace/fsharp/training/FSharpSample)
Mark set
Company: An error occurred in auto-begin
Company: backend company-capf error "No Typecheck results" with args (candidates names)
Company: An error occurred in auto-begin
Company: backend company-capf error "No Typecheck results" with args (candidates modu)
Company: An error occurred in auto-begin
Company: backend company-capf error "No Typecheck results" with args (candidates prin)
Company: An error occurred in auto-begin
Company: backend company-capf error "No Typecheck results" with args (candidates print)
```

### Anything else?

- Linux 
- dotnet 6.0.101
- emacs 28

**Comment by razzmatazz** [comment] 2022-02-28 05:45
I believe the issue is that there is an issue with fsac when running under .net 6 vs 5:
- https://github.com/fsharp/FsAutoComplete/issues/866

I.e. this is not a problem with with lsp-mode.

Could you try installing .net 5 instead and test fsharp sample? And if things work with .net5 could you add your voice to https://github.com/fsharp/FsAutoComplete/issues/866 ? :)

**Comment by razzmatazz** [comment] 2022-02-28 05:47
you could also try to downgrade your project to "net5.0" first, to see if this fixes your porblem..

**Comment by yyoncho** [comment] 2022-10-05 18:35
@mattgallagher92 M-x company-diag?

**Comment by razzmatazz** [comment] 2022-10-05 19:16
> @razzmatazz is this still an issue? I'm not getting autocomplete either. That said, I'm an Emacs noob trying to set up F# support from a bare-bones vanilla Emacs setup, so it's possible that I'm doing something unexpected. With my cursor after `System.Dat` in an F# buffer, I've tried: `M-x package-install RET company`, `M-x company-mode`, `M-x company-complete` and get the message "No completion found".
> 
> Like serezlan, I'm running dotnet 6 (6.0.109) on Linux (Ubuntu 22.04), with Emacs 28 (28.2).

mhm.. I work on doom emacs, so thats definitely not a vanilla..

- what things do you see with `M-x lsp-toggle-trace-io` enabled? are the any requests issued to the server?
- do you have `lsp-mode` enabled on your buffer? try `M-x lsp-mode` should it not be enabled automatically 
- also, does the server start for you at all?

**Comment by mattgallagher92** [comment] 2022-10-06 09:13
Thank you both. I've tried again today and&mdash;rather unexpectedly&mdash;my setup is working! I don't think that I did anything different from when I posted my previous comment, so perhaps the things I've done since posting it have helped (powered my computer off at the end of each day; restarted Emacs a few times; switched config to Doom Emacs yesterday and back again today to test after your comments).

I'm pretty sure that lsp-mode was enabled because navigation was working in a way that I don't think it would without lsp-mode. And I remember seeing warnings about unknown notifications from the lsp server.

Anyway, the upshot is that I don't need any further help regarding this issue. Thank you for your time :slightly_smiling_face:

**Comment by mattgallagher92** [comment] 2022-10-06 09:41
@razzmatazz it's interesting to hear that you work on Doom Emacs. The reason I've been trying to set up F# support in vanilla Emacs is that I've not got it working in Doom Emacs. I was trying to learn how to set it up from vanilla Emacs with the hope that I could then either configure the additional things I like about Doom Emacs (evil, Magit, projectile and much more) within vanilla Emacs or transfer the knowledge I gained via this setup to try to configure F# support within Doom Emacs in an alternative way.

Based on my experience with vanilla Emacs setup, it seems likely that I didn't have the lsp support working properly within Doom Emacs. I've tried again to get it working in Doom Emacs but haven't had any success. I'll raise a separate issue within Doom Emacs.

**Comment by mattgallagher92** [comment] 2022-10-06 10:45
Thanks :slightly_smiling_face:  The Doom Emacs issue template prompted me to upgrade to the latest version of Doom Emacs. After a `doom upgrade`, LSP support is working with `lsp` and `(fsharp +lsp)` in ./doom.d/init.el :partying_face:

I'm very excited to be able to try this out! Thanks for your support :smile:

**Comment by razzmatazz** [comment] 2022-10-06 10:46
> Thanks slightly_smiling_face The Doom Emacs issue template prompted me to upgrade to the latest version of Doom Emacs. After a `doom upgrade`, LSP support is working with `lsp` and `(fsharp +lsp)` in ./doom.d/init.el partying_face
> 
> I'm very excited to be able to try this out! Thanks for your support smile

this is great!

I am closing this issue unless @serezlan objects

**Closed by razzmatazz** 2022-10-06 10:46 UTC
Labels: bug
