### ISSUE TITLE
lsp-rename has been broken

### ISSUE THREAD

**Issue by bradprob** [emacs-lsp/lsp-mode#864] opened 2019-05-30 19:41 UTC
**Describe the bug**
lsp-rname remove extra characters.

**To Reproduce**
In a C++ project just execute lsp-rename on a class name.

**Expected behavior**
Expected that only the class name was named.

**Which Language Server did you use**
C++

**OS**
Debian

**Error callstack**
No error

**Comment by yyoncho** [comment] 2019-05-30 20:20
What is the actual behaviour?

**Comment by bradprob** [comment] 2019-05-30 21:40
lsp-rename changes:
```
class foo : bar {
public:
int baz;
...
```
to
```
class quuxlic:
int baz;
```

Though after restarting Emacs it behaves normal!!!

**Comment by yyoncho** [comment] 2019-05-31 16:51
Which language serve did you use? Can you attach client server communication?

**Comment by bradprob** [comment] 2019-05-31 22:03
clangd.
```
I[23:59:00.822] <-- textDocument/didChange
I[23:59:00.824] <-- textDocument/didChange
I[23:59:00.826] <-- textDocument/didChange
I[23:59:00.829] <-- textDocument/didChange
I[23:59:00.831] <-- textDocument/didChange
I[23:59:00.834] <-- textDocument/didChange
I[23:59:00.837] <-- textDocument/didChange
I[23:59:00.839] <-- textDocument/didChange
I[23:59:00.841] <-- textDocument/didChange
I[23:59:00.843] <-- textDocument/didChange
I[23:59:00.845] <-- textDocument/didChange
I[23:59:00.846] <-- textDocument/didChange
I[23:59:00.848] <-- textDocument/didChange
I[23:59:00.849] <-- textDocument/didChange
I[23:59:00.851] <-- textDocument/didChange
I[23:59:00.853] <-- textDocument/didChange
I[23:59:00.855] <-- textDocument/didChange
I[23:59:00.856] <-- textDocument/didChange
I[23:59:00.858] <-- textDocument/didChange
I[23:59:00.859] <-- textDocument/hover(31)
I[23:59:00.859] Updating file /home/xxx/c++/project/src/file.hpp with command [/home/xxx/c++/project/build/debug] /usr/bin/c++ -I../../thirdparty/catch -I../../thirdparty/xxx -I../../thirdparty/spdlog -I../../src -g -Wall -Wextra -Wunreachable-code -g -c -std=gnu++17 /home/xxx/c++/project/src/fiel.hpp -resource-dir=/usr/lib/llvm-9/lib/clang/9.0.0
I[23:59:00.902] --> textDocument/publishDiagnostics
I[23:59:00.903] --> reply:textDocument/hover(31) 43 ms
I[23:59:01.172] <-- textDocument/documentHighlight(32)
I[23:59:01.173] --> reply:textDocument/documentHighlight(32) 0 ms
I[23:59:10.982] <-- textDocument/hover(33)
I[23:59:10.982] --> reply:textDocument/hover(33) 0 ms
```

**Comment by yyoncho** [comment] 2019-06-01 06:34
I tried it locally with clangd and few more language servers and my conclusion is that rename works. I am closing it as unable to reproduce.

Please reopen it after providing exact steps providing steps to reproduce using the latest clangd/lsp-mode including the client-server communication, source file and so on. You can collect client/server communication after setting lsp-print-io to `t` and inspecting `*lsp-log: clangd:pid*` buffer. You may also do investigation on your side since all the information on the rename operation is present in the log.

**Closed by yyoncho** 2019-06-01 06:34 UTC

**Comment by lorenzhs** [comment] 2019-08-21 08:13
I also have this issue. It is reliably triggered by having a comment with an umlaut in the file. Probably other non-ASCII characters will do the trick as well. You can find the `*lsp-log: clangd:pid*` buffer's contents and the before/after file here: https://gist.github.com/lorenzhs/6c863855426850ddcb0d9d9862c2f887 - there relevant bit is the `// ü` comment.

**Comment by yyoncho** [comment] 2019-08-21 09:02
@lorenzhs I was unable to reproduce it with clangd 8 and the logs seems to be ok - the rename returns the correct result but then it seems like that the update is applied incorrectly. Can you try to reproduce it with `emacs -q -l lsp-start-plain.el` where start plain comes from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?

How did you install clangd 9-rc2 ?

**Comment by lorenzhs** [comment] 2019-08-21 09:35
That fails with `Debugger entered--Lisp error: (error "Package ‘lsp-mode-’ is unavailable")`.

I installed it using apt from the Debian experimental repos. But it doesn't work using clangd-8 from Debian unstable (`clangd version 8.0.1-3+b1 (tags/RELEASE_801/final)`, as opposed to `clangd version 9.0.0-+rc2-1~exp1 (tags/RELEASE_900/rc2)` earlier), either.

**Comment by yyoncho** [comment] 2019-08-21 09:43
> That fails with Debugger entered--Lisp error: (error "Package ‘lsp-mode-’ is unavailable").

If you are using emacs 26.2 can you change the melpa/elpa urls from https to http?

> I installed it using apt from the Debian experimental repos. 

Ok, I will try to reproduce it using docker debian unstable image. Also, afaik there are some new features in clagnd (e. g. type/call hierarchy, I will add support for them too).

**Comment by lorenzhs** [comment] 2019-08-21 10:54
I'm using emacs 26.1. The issue is fully reproducible using lsp-start-plain.el and clangd-8 from the eponymous package in Debian unstable. See https://gist.github.com/lorenzhs/6c863855426850ddcb0d9d9862c2f887#file-lsp-log-clangd-8-with-lsp-start-plain for the log.

**Comment by yyoncho** [comment] 2019-08-21 13:20
@lorenzhs that is really odd - I will try to reproduce it with docker image. Can you open another issue in the project(I think your issue is unrelated to the current one)?

**Comment by lorenzhs** [comment] 2019-08-21 14:03
Thanks, I did and linked this thread.
