### ISSUE TITLE
ts-ls: Wrong lsp-clients-typescript-server-path

### ISSUE THREAD

**Issue by eginhard** [emacs-lsp/lsp-mode#4254] opened 2023-12-09 19:40 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

https://github.com/emacs-lsp/lsp-mode/pull/4202 made some changes to handle a deprecated argument in the language server. This included changing `lsp-clients-typescript-server-path()` to return:
https://github.com/emacs-lsp/lsp-mode/blob/01bd566c0508993202b08071ed7037c9fc4e3329/clients/lsp-javascript.el#L803
For me this evaluates to `~/.emacs.d/var/lsp/server/npm/typescript/bin/node_modules/typescript/lib`, while `tsserver.js` is actually in `~/.emacs.d/var/lsp/server/npm/typescript/lib/node_modules/typescript/lib`. So I guess the line above should be:
```elisp
(f-join (f-parent (f-parent (lsp-package-path 'typescript))) "lib" "node_modules" "typescript" "lib"))))
```

### Steps to reproduce

1. Open a `.js` file with `ts-ls`, the following error appears: `LSP :: Error from the Language Server: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace or that a valid `tsserver.path` is specified. Exiting. (Internal Error)`

### Expected behavior

`ts-ls` starts normally

### Which Language Server did you use?

lsp-javascript/ts-ls

### OS

Linux

**Comment by hamaker** [comment] 2023-12-19 11:48
I'm having this issue as well. Reverting the change from #4202 to line 803 as mentioned by @eginhard resolved it.

**Comment by yyoncho** [comment] 2023-12-19 15:21
@kiennq - seems like it is a regression?

**Comment by ncaq** [comment] 2024-01-23 15:09
I am having a rather hard time getting lsp to work in a TypeScript project in a subdirectory due to this problem.
Also, the original PR does not work in environments that do not use node_modules such as yarn PnP, and I expect that some people will have trouble with that.

**Comment by idhowardgj94** [comment] 2024-02-05 13:00
> I'm having this issue as well. Reverting the change from #4202 to line 803 resolved it.

same issue here, and resolved by follow @hamaker's suggestion.

I guess that new code didn't include all kind of npm install path.

For my case, I'm using nvm, and my global install path is in `~/.nvm/`

And I can use `M-x lsp-install-server` command, and that `tsc` & `tsserver` bin install inside `~/.emacs.d/.cache/lsp/npm/typescript/bin`

didn't really deep into what's going on here, though, hope someone can solve this problem :)

**Comment by stradicat** [comment] 2024-03-05 19:58
I'm getting the same problem; also:
`Typescript specified through user setting ignored due to invalid path ..completely_wrong_path..`

Deleting `~/.emacs.d/.cache/lsp/npm/typescript*` and installing `typescript` and `typescript-language-server` globally mitigated the problem; the language server isn't being picked up under `~/.emacs.d/.cache/lsp`, although `eslint` and other _node_-based servers are correctly detected.

**Comment by hyperair** [comment] 2024-03-06 05:56
On my machine, my emacs.d cache folder looks like this:

```
~/.emacs.d/.cache/lsp/npm/typescript
├── bin
│   ├── tsc -> ../lib/node_modules/typescript/bin/tsc
│   └── tsserver -> ../lib/node_modules/typescript/bin/tsserver
└── lib
    └── node_modules
        └── typescript

5 directories, 2 files
```

Similar to the issue description, the elisp statement linked there evaluates to `~/.emacs.d/.cache/lsp/npm/typescript/bin/node_modules/typescript/lib` which doesn't exist.


The fix in https://github.com/emacs-lsp/lsp-mode/pull/4284 works for me, and as a quick workaround without having to locally edit my elpa files, adding a node_modules symlink in the path that lsp-mode is erroneously looking in also works:

```
$ cd ~/.emacs.d/.cache/lsp/npm/typescript/bin && ln -s ../lib/node_modules
```

**Comment by ncaq** [comment] 2024-03-14 22:52
My problem was solved by the PR I sent out last month, does this solve yours?
[fix: remove direct references to the node_modules directory by ncaq · Pull Request #4333 · emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode/pull/4333)

**Comment by jcs090218** [comment] 2024-03-16 07:17
Can someone give this a test? 🤔 Thanks!

**Comment by ghferrari** [comment] 2024-03-20 09:28
Thanks @ncaq - your PR seems to fix the problem for me.

**Comment by jcs090218** [comment] 2024-03-23 03:08
This doesn't look right. If you are on windows, the path looks like: 🤔 

```
~/.emacs.d/.cache/lsp/npm/typescript/node_modules/typescript/lib
```

**Comment by jcs090218** [comment] 2024-03-24 00:24
Can someone test #4389? It should work on both Unix-like and Windows systems. 🤔

**Comment by kiennq** [comment] 2024-03-24 11:02
> Can someone test #4389? It should work on both Unix-like and Windows systems. 🤔

It looks good to me.

**Comment by jcs090218** [comment] 2024-03-24 18:20
Completed in #4389.

**Closed by jcs090218** 2024-03-24 18:21 UTC
Labels: bug

**Comment by ncaq** [comment] 2024-03-27 08:25
I'm referencing the node_modules directory from the lsp root, so the problem isn't solved in environments with node_modules in subdirectories, etc. that my PR solved. should this be a separate issue?

**Comment by ncaq** [comment] 2024-03-27 09:18
Perhaps you are under the mistaken impression that my PR is simply to change the PATH specification of the original issue contributor, while my PR is to stop referring to the PATH directly...
Well, I'll make sure it works on Windows.

**Comment by ncaq** [comment] 2024-03-27 09:46
I have checked it works on Windows and found that it certainly does not work on Windows, even with the content of my PR, so I would like to correct it.

**Comment by ncaq** [comment] 2024-03-27 13:49
@jcs090218 
The problem was not completely resolved in my environment, but your point about it not working on Windows was correct, so I have corrected my submitted PR with reference to your correction as well.
I would be happy to review it for you.
[fix: remove direct references to the node_modules directory by ncaq · Pull Request #4333 · emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode/pull/4333)

**Comment by jcs090218** [comment] 2024-03-27 22:28
> I'm referencing the node_modules directory from the lsp root, so the problem isn't solved in environments with node_modules in subdirectories, etc. that my PR solved. should this be a separate issue?

It's better to be in separate issues. 👍 The title is a bit misleading. 🤔
