### ISSUE TITLE
[Feature Request] Support for haxe language

### ISSUE THREAD

**Issue by mundusnine** [emacs-lsp/lsp-mode#661] opened 2019-02-20 22:21 UTC
Following could be used to integrate the haxe language
https://github.com/vshaxe/haxe-languageserver

**Comment by yyoncho** [comment] 2019-02-21 18:01
@mundusnine I checked the language server - it seems like provides a lot of extension methods and requires a relatively high amount of work in order to make it work(I am judging based on the size of the client)  . Based on this it seems like the issue could be addressed only by Haxe user. Do you want to give it a try?

**Comment by mundusnine** [comment] 2019-02-22 18:27
For now, I don't really have the time. But I will put it in my stack for the futur. @fullofcaffeine also wanted this feature maybe he would be interested.

**Comment by Gama11** [comment] 2019-04-30 12:44
The size of the client might be a bit deceptive, we implement some things like task providers, custom tree views etc that aren't really necessary for the language server. People have gotten it to work with Neovim (https://github.com/vshaxe/vshaxe/issues/328) and Sublime Text before.

**Comment by zaethan** [comment] 2019-05-21 22:23
I was able to make it (somewhat) work, by adding this to my config:

``` 
  (defgroup lsp-haxe nil
    "LSP support fer Haxe"
    :group 'lsp-mode
    :link '(url-link "https://github.com/vshaxe/vshaxe"))

  ;; haxe lsp is executed via node
  (defcustom lsp-clients-haxe-executable "node"
    "haxe lsp is executed via node"
    :group 'lsp-haxe
    :risky t
    :type 'file)

  ;; arguments for node to start the haxe lsp
  (defcustom lsp-clients-haxe-args '("/mnt/RamDisk/vshaxe/server/bin/server.js")
    "arguments for node to start the haxe lsp"
    :group 'lsp-haxe
    :risky t
    :type 'file)

  (defun lsp-clients--haxe-command ()
    "Haxe LS startup command"
    `(,lsp-clients-haxe-executable ,@lsp-clients-haxe-args))

  ;; adapted from go / https://github.com/emacs-lsp/lsp-mode/pull/668/files
  (defcustom lsp-clients-haxe-arguments ["build.hxml"]
    "https://github.com/vshaxe/vshaxe/issues/328#issuecomment-472053630."
    :type 'string
    :group 'lsp-clients-haxe)

  (defun lsp-clients-haxe--make-init-options()
    "Init options for the haxe lsp"
    `(:displayArguments ,lsp-clients-haxe-arguments))

  ;; https://github.com/yyoncho/lsp-mode/commit/72186e1adc089d772c87ed8f287eb3333b66bfa7
   (defcustom lsp-clients-haxe-settings (list :haxe.executable "haxe")
    "Lsp clients configuration settings."
    :group 'lsp-haxe
    :risky t
    :type '(repeat string))

  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection
                                     'lsp-clients--haxe-command)
                    :major-modes '(haxe-mode)
;                    :initialization-options 'lsp-clients-haxe--make-init-options
                    :initialized-fn (lambda (workspace)
                                      (with-lsp-workspace workspace
                                        (lsp--set-configuration lsp-clients-haxe-settings)))
                    :priority -1
                    :server-id 'haxe))

  (setq lsp-print-io t)

  (require 'lsp-mode)
  (add-hook 'haxe-mode-hook #'lsp)
```

The first four "defines" where derived from the clangd section in lsp-clients.el and simply describe how the server should be started. (For building the Server I simply followed these instructions: https://github.com/vshaxe/vshaxe/wiki/Installation#from-source.)

I added the `defcustom lsp-clients-haxe-arguments`, as the Thread linked by @Gama11 mentioned that the server needed _displayArguments: ["build.hxml"]_ in its _initializationOptions_. I ended up not using it (commented out in make_lsp_client) and it didn't break...

Something that was absolutely needed was the `defcustom lsp-clients-haxe-settings` and the `:initialized-fn`part. Without this the server would be started, but didn't respond to anything after initializing.

So far so good:
![grafik](https://user-images.githubusercontent.com/39460066/58132678-3fa4ad80-7c22-11e9-89b1-f6de396039a1.png)

It suggests autocompletions and shows the documentation in the top-right corner and suggests to remove unused imports.

But it does some weird things too, I do not know, whether this is caused by the server or the client, but since this is about using the server in emacs, I post this here.
* after opening my testfile and typing a single letter, emacs will hang for about half a minute with 100% load on one of the cpu cores. After that this won't happen again (until I close emacs).
* `Remove all unused imports/usings` is always shown, but it doesn't do anything. Even when I intentionally add useless imports.
* completion works... somewhat.
    * If I type in `imp` for `import` it suggests that completion. When I hit enter, nothing happens... except for the completion window disappearing.
    * If I type `db.r` for `db.request()`, it suggests exactly that. Hitting enter turns it into `drequest`. It somehow removed the b and the dot... Completing `db.re` results in `request` (removed the d too), completing `db.req` begins removing the indentation...
    * If I type in `import sys.io.F` it suggests `File`. This time, when I hit enter, it correctly autocompletes.
* upon startup I get some warnings:
```
Warning (lsp-mode): Unknown method: haxe/progressStart
Warning (lsp-mode): Unknown method: haxe/progressStop
Warning (lsp-mode): Unknown method: haxe/progressStart
Warning (lsp-mode): Unknown method: haxe/progressStop
Warning (lsp-mode): Unknown method: haxe/progressStart
Warning (lsp-mode): Unknown method: haxe/progressStop
```
* Based on where my cursor is, I get `LSP :: Error :: No completion point was found.` in the minibuffer. In my small example file, it appears when the line starts with some keyword (import, class, var) or the cursor is inside a comment.

As I said I don't know what is caused by the server and what is caused by the client. Especially since the client works fine with other servers and the server seems to work with the neovim and sublime text clients...
I just updated emacs lsp -mode earlier this day and the server was built from the github sources with 4.0.0-rc.2

**Comment by yyoncho** [comment] 2019-05-22 07:07
Thanks for doing the initial investigation! You may post a PR and I will try to help on fixing the issues when I got some free time. Also, it will be useful for us if you provide a sample haxe project.

Most of the issues are related to `lsp-mode` not being adjusted to haxe ls. 

> after opening my testfile and typing a single letter, emacs will hang for about half a minute with 100% load on one of the cpu cores. After that this won't happen again (until I close emacs).

I need perf report to be able to diagnose it. Or you could to toggle-debug-on-quit and press C-g when it hangs and report the callstack.

> upon startup I get some warnings:

You need to register :notification-handlers for the notifications that are not part of the spec, check lsp-rust.el. 

> Remove all unused imports/usings is always shown, but it doesn't do anything. Even when I intentionally add useless imports.

Probably we need to register completion handler, see typescript server for example (request-handlers).

> completion works... somewhat.

This is probably a bug in company-lsp but I need more information on that(e. g. the client-server communication).

**Comment by zaethan** [comment] 2019-05-23 21:55
To avoid errors introduced in the git version of the language server, I now decided to use the version available from the vscode marketplace. I also use the haxe 4.0.0-rc2 version from their website instead of compiling haxe from the git repository. And I set up a special emacs config containing mostly parts that are actually needed for haxe-lsp.
This alone seems to have fixed some of the issues:
* Emacs does not hang anymore. 
* Autocomplete does not remove parts of what I typed. (`db.re` turns into `db.request`)

I also registered notification handlers to remove the warnings about the processStart/Stop messages (one handler actually which just calls lsp-log... I just ignore the other message).

However, `imp` for `import`, still does not work correctly. And it still always suggests to remove unused imports. I will try to produce some nice logs for that, in which I minimize unrelated actions... (the logs I have so far are quite long and flooded with unrelated actions...)

About imports: If I use for example `Sqlite.open("...");` without importing Sqlite first, it suggests to either `import sys.db.Sqlite` or change the usage to `sys.db.Sqlite.open("...")`. Both of these functions work as expected.

As for a pull request, I guess I should put the necessary configuration in a new file lsp-haxe.el. Or would lsp-clients.el be a better choice?
Also, the path of the server.js is still hardcoded... I guess I should probably use a defcustom for that.
As for a sample project, I am actually just using an almost empty file named Test.hx and then just write whatever I want to test out... normally it ends up looking like this, but I never save it...
```
import sys.db.Sqlite;

class Tast {
	
	var con = Sqlite.open("test.db");
	
	var test:String;
	
	var tist = Sqlite.request("...");
}
```

Would it be a good idea, to include some archive with the emacs configuration I use for testing this, as well as the haxe ls (the vscode extension) and the haxe comiler binary (4.0.0-rc2 from haxe.org)? I would also put some test file in there...

**Comment by yyoncho** [comment] 2019-05-24 06:21
> However, `imp` for `import`, still does not work correctly.

I will take a look at that once you post a PR.

> And it still always suggests to remove unused imports. I will try to produce some nice logs for that, in which I minimize unrelated actions... (the logs I have so far are quite long and flooded with unrelated actions...)

ATM this is the expected behaviour. I will check why the action is not applied.

> As for a pull request, I guess I should put the necessary configuration in a new file lsp-haxe.el. Or would lsp-clients.el be a better choice?

It is up to you. 

> Also, the path of the server.js is still hardcoded... I guess I should probably use a defcustom for that.

Yes.

> As for a sample project, I am actually just using an almost empty file named Test.hx and then just write whatever I want to test out... normally it ends up looking like this, but I never save it...

Cool. 
 
> Would it be a good idea, to include some archive with the emacs configuration I use for testing this, as well as the haxe ls (the vscode extension) and the haxe comiler binary (4.0.0-rc2 from haxe.org)? I would also put some test file in there...

You could do that but you should also include instructions in the lsp-mode README what is the best way to obtain the server.

**Comment by Jumblemuddle** [comment] 2019-06-01 17:51
I was able to get this mostly working thanks to code from [856](https://github.com/emacs-lsp/lsp-mode/pull/856), but I'm unable to complete snippets by name (see https://github.com/vshaxe/vshaxe/issues/351).

**Comment by Jumblemuddle** [comment] 2019-06-01 17:54
Per https://github.com/vshaxe/vshaxe/issues/351, it looks like there is no server-side filtering, so this is probably a [Company LSP](https://github.com/tigersoldier/company-lsp) issue.

**Comment by yyoncho** [comment] 2019-06-01 18:28
@Jumblemuddle the latest version of company-lsp provides client-side filtering. There is haxe issue related inserting, described in https://github.com/emacs-lsp/lsp-mode/pull/856#issuecomment-495940138 which should be resolved upstream. You may inspect the filtering process via M-x trace-function company-lsp--filter-candidates RET .

**Comment by yyoncho** [comment] 2019-06-01 18:59
![Uploading Selection_142.png…]()

**Comment by Jumblemuddle** [comment] 2019-06-01 22:48
@yyoncho, I do actually have the Haxe LSP built with the modifications from https://github.com/vshaxe/vshaxe/issues/350 to include the range. Are you saying I should be able to complete these entries with that?

**Comment by yyoncho** [comment] 2019-06-02 05:10
@Jumblemuddle No, what I am saying is that if you are using latest company-lsp it should filter the completion items client side.  vshaxe/vshaxe#350 is about being able to insert them. My comment was an answer to 

> Per vshaxe/vshaxe#351, it looks like there is no server-side filtering, so this is probably a Company LSP issue.

**Comment by Jumblemuddle** [comment] 2019-06-02 12:14
@yyoncho, oh, gotcha.
I am using the latest company-lsp, so I just need to figure out why it always filters out everything but functions.

**Comment by yyoncho** [comment] 2019-06-02 14:36
@Jumblemuddle it is haxe bug - so the snippets are available only when you press `.` . By default, company-lsp does not cache the items that are retrieved initially. You may avoid it by doing


``` (setq company-lsp-cache-candidates t) ``` and the snippets will work.

You may reproduce it in vscode too - e. g. type `"xx".fo` press escape to remove the snippet and then press `C-SPC` to trigger completion.

**Comment by Jumblemuddle** [comment] 2019-06-02 19:15
Thanks, @yyoncho! Works like a charm
I'm not entirely clear on the difference, but `(company-lsp-cache-candidates 'auto)` worked as well.

**Comment by Gama11** [comment] 2019-06-17 16:48
>You may reproduce it in vscode too - e. g. type "xx".fo press escape to remove the snippet and then press C-SPC to trigger completion.

Nice catch, this should be fixed now.

**Comment by yyoncho** [comment] 2019-09-15 11:09
The initial support is in.

**Closed by yyoncho** 2019-09-15 11:09 UTC
Labels: enhancement, help wanted

**Comment by alexjgriffith** [comment] 2020-05-07 22:46
Trying this out with heaps.io

It works for built in libraries but flymake does not recognize the libs in build.hxml

``` 
LSP :: Type not found : hxd.res.DefaultFont;
```
Results from the heaps.io hashlink example

``` haxe
import hxd.res.DefaultFont;
import h2d.Text;

class Main extends hxd.App {
  override function init() {
    var tf = new h2d.Text(DefaultFont.get(), s2d);
    tf.text = "Hello World!";
  }

  static function main() {
    new Main();
  }
}

```

From the heaps.io tutorial my build.hxml looks like
```
-lib heaps
-lib hlsdl
-hl hello.hl
-main Main
```
