### ISSUE TITLE
Completion error

### ISSUE THREAD

**Issue by taigacute** [emacs-lsp/lsp-mode#1536] opened 2020-03-25 04:19 UTC
It will show completion items when input `(` or `{`, Seems like this commit `2472231de1bebbd3236a3a3c8ba0cbfe58364faf` caused . please check @kiennq  @yyoncho 
![image](https://user-images.githubusercontent.com/41671631/77501302-a1612400-6e92-11ea-989b-1c195e9154f3.png)

**Comment by kiennq** [comment] 2020-03-25 04:43
I can probably add a flag to disable this behavior.

@taigacute Did you find the new behavior too obstructive?
The language server did return something and we display it though. Sometimes it may be good in case the language server can provide type a head prediction

**Comment by taigacute** [comment] 2020-03-25 04:49
@kiennq  Yes, it hinders input, normal behavior should not be displayed, for example  If show completion items after input `{` then can't use `enter` to make a newline.

**Comment by kiennq** [comment] 2020-03-25 11:07
@taigacute @yyoncho I wonder what should be expected behavior here:
- We can try to frequently showing the completion items as now
- Or revert the change and require user to manually request completions in case of #1527 
- Or a hybrid solution of letting the `lsp-client` to somehow specify the logic for choosing to query the completion candidates or not.

WDYT?

**Comment by yyoncho** [comment] 2020-03-25 11:18
I think we should investigate how VScode handles #1527 . 1) seems to cause usability issues since it is preventing `RET`.

**Comment by taigacute** [comment] 2020-03-25 11:18
@kiennq  The correct behavior is doesn't show any completion items after `( {`.  The gif show the problem which caused the inability to use carriage returns to wrap lines after `{`,This is the current behavior in vim,
![test1](https://user-images.githubusercontent.com/41671631/77531147-6defbb00-6ecd-11ea-953b-176c9a3c36b1.gif)

**Comment by kiennq** [comment] 2020-03-25 12:47
> The correct behavior is doesn't show any completion items after `( {`.

That maybe  expectation in `go`, however, for other one the expectation may different.
For example, in the case of #1527, the completions are expected after `/**`.
Or for `c++20`, with this code `struct X { int a; int b; }; X x {<|>};` (where `<|>` is cursor position), the completion are expected to show `.a` and `.b`.

Also, as a side note, `company-mode` bind `RET` to determine the item when there's pop up, that's why the `RET` key is stolen.

**Comment by taigacute** [comment] 2020-03-25 12:50
Hmm,This carriage return behavior is consistent in vim and vscode. By the way, pop-up completion like this will invalidate the `{` behavior of smartparens.

**Comment by kiennq** [comment] 2020-03-27 06:59
It's pretty bad, indeed.
However, as I said before, this is depend on the language expectation.
How about the solution like this:
- partly revert 2472231de, so the prefix length is no longer calculated by distance to the previous white space, thus avoid accidentally completions request like this.
- Add a new slot to `lsp--client` (`check-trigger-completion-fn`) to customize the condition to trigger completion candidates for each client. With `nil`, fallback to logic before  2472231de

@yyoncho

**Comment by taigacute** [comment] 2020-03-27 15:23
Also on rust,It's really annoying.
![image](https://user-images.githubusercontent.com/41671631/77771632-e39c8800-7081-11ea-8bbd-5c8f526c09ad.png)

**Comment by yyoncho** [comment] 2020-03-27 15:38
> Add a new slot to lsp--client (check-trigger-completion-fn) to customize the condition to trigger completion candidates for each client. With nil, fallback to logic before 2472231

I believe that we do not want this even for scala because it will trigger completion in `{}` as well. I am about sticking to the protocol - the completion should appear if you type trigger character or if you have hit the prefix lenght(configurable client side).

**Comment by kiennq** [comment] 2020-03-27 18:38
> I am about sticking to the protocol - the completion should appear if you type trigger character

Is `\**` is trigger character in scala? I doubt so.



> or if you have hit the prefix lenght(configurable client side).

I think this is great idea. We can do additional filtering after getting candidates and can determine prefix length correctly.
Just a case that's not working well with this is when we manually trigger the completion, we may not   differentiable from *manual triggered - should not doing length based filtering* and  *auto triggered - should do length based filtering*.
Also enable getting completions frequently make Emacs become slower, since I'm not on native json supported build yet, it makes my Emacs a tad slower.




> I believe that we do not want this even for scala because it will trigger completion in `{}` as well

As for this, scala client can use a customized logic to also trigger completions when detect `\**`. That would make `{}` not trigger completions while still resolving original bug.
WDYT?

**Comment by yyoncho** [comment] 2020-03-27 19:43
This is comment in the scala scala implementation PR:

> Enable to fire textDocument/completion on type * by setting triggerCharacters on initialize.

So if our handling of triggerCharacters is correct we won't need any adjustment.

**Comment by kiennq** [comment] 2020-03-28 01:14
Oh, I didn't know that, then just enable completion on comment part is enough, I will partly revert the previous commit

**Closed** 2020-03-28 06:19 UTC
