### ISSUE TITLE
Need lsp mode that regionally smart 

### ISSUE THREAD

**Issue by fetatefog** [emacs-lsp/lsp-mode#786] opened 2019-04-22 12:16 UTC
```
<html>
    <head>
         <style type="text/css">
          /**CSS here*/
         </style>
         
         <script type="text/javascript">
         /**JS here*/
         </script>                          
    </head>
    

    <body>    
              <input style =""/>
    </body>
</html>
```

I am curious if it is possible to make lsp switching between each mode automatically in order to make completion or suggestion. Imagine my above code, if my cursor is in between *script* tag, then it should auto complete JS while if it is inside *style* tag or in between quote of style value, then it should auto complete as CSS but if it is not in between Style or Script tag, then it should auto complete as html in this example because it is inside html code.

**Comment by yyoncho** [comment] 2019-04-22 12:18
duplicate of https://github.com/emacs-lsp/lsp-mode/issues/667

**Closed by yyoncho** 2019-04-22 12:18 UTC

**Comment by fetatefog** [comment] 2019-04-28 14:25
@yyoncho, this info might be helpful,
https://github.com/fxbois/web-mode/issues/1058
