### ISSUE TITLE
Angular imports are not getting recognised

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-mode#1459] opened 2020-02-27 15:40 UTC
**Describe the bug**
Angular imports are not getting recognised 

**To Reproduce**
 dotspacemacs-configuration-layers
   '(
     (typescript :variables
                 typescript-backend 'lsp
                 ;; tide-tsserver-executable "/usr/local/bin/tsserver"
                 typescript-fmt-tool 'typescript-formatter
                 typescript-linter 'tslint
                  ))

 (setq lsp-clients-angular-language-server-command
        '("node"
          "/usr/local/lib/node_modules/@angular/language-server"
          "--ngProbeLocations"
          "/usr/local/lib/node_modules"
          "--tsProbeLocations"
          "/usr/local/lib/node_modules"
          "--stdio"))
  )
**Expected behavior**
Import should get recognised.

**Which Language Server did you use**
lsp for Angular

**OS**
Mac OS X
Emacs - 26.2 (Spacemacs)

```

**Comment by yyoncho** [comment] 2020-02-27 16:30
Please provide steps to reproduce that require zero angular/js knowledge, including a sample project, and so on.

**Comment by gnumonk** [comment] 2020-02-27 16:52
Steps to reproduce -
1) Emacs with Spacemacs (Emacs v26.2 and Spacemacs 300.2).
2) Following configuration in .spacemacs
dotspacemacs-configuration-layers
   '(
     (typescript :variables
                 typescript-backend 'lsp
                 ;; tide-tsserver-executable "/usr/local/bin/tsserver"
                 typescript-fmt-tool 'typescript-formatter
                 typescript-linter 'tslint
                  ))

(setq lsp-clients-angular-language-server-command
        '("node"
          "/usr/local/lib/node_modules/@angular/language-server"
          "--ngProbeLocations"
          "/usr/local/lib/node_modules"
          "--tsProbeLocations"
          "/usr/local/lib/node_modules"
          "--stdio"))

3) Create Angular project
MacBook-Pro ~/Documents $ ng new my-first-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE my-first-app/README.md (1027 bytes)
CREATE my-first-app/.editorconfig (246 bytes)
CREATE my-first-app/.gitignore (631 bytes)
CREATE my-first-app/angular.json (3615 bytes)
CREATE my-first-app/package.json (1289 bytes)
CREATE my-first-app/tsconfig.json (543 bytes)
CREATE my-first-app/tslint.json (1953 bytes)
CREATE my-first-app/browserslist (429 bytes)
CREATE my-first-app/karma.conf.js (1024 bytes)
CREATE my-first-app/tsconfig.app.json (210 bytes)
CREATE my-first-app/tsconfig.spec.json (270 bytes)
CREATE my-first-app/src/favicon.ico (948 bytes)
CREATE my-first-app/src/index.html (296 bytes)
CREATE my-first-app/src/main.ts (372 bytes)
CREATE my-first-app/src/polyfills.ts (2835 bytes)
CREATE my-first-app/src/styles.css (80 bytes)
CREATE my-first-app/src/test.ts (753 bytes)
CREATE my-first-app/src/assets/.gitkeep (0 bytes)
CREATE my-first-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-first-app/src/environments/environment.ts (662 bytes)
CREATE my-first-app/src/app/app-routing.module.ts (246 bytes)
CREATE my-first-app/src/app/app.module.ts (393 bytes)
CREATE my-first-app/src/app/app.component.css (0 bytes)
CREATE my-first-app/src/app/app.component.html (25755 bytes)
CREATE my-first-app/src/app/app.component.spec.ts (1077 bytes)
CREATE my-first-app/src/app/app.component.ts (216 bytes)
CREATE my-first-app/e2e/protractor.conf.js (808 bytes)
CREATE my-first-app/e2e/tsconfig.json (214 bytes)
CREATE my-first-app/e2e/src/app.e2e-spec.ts (645 bytes)
CREATE my-first-app/e2e/src/app.po.ts (301 bytes)

5) Open project in emacs  and navigate to main.ts, lsp will be connected
but @anglar/core and other import will says "not recongnize";

**Comment by yyoncho** [comment] 2020-02-27 18:20
It works fine after you do npm install in the root of the project.

**Comment by yyoncho** [comment] 2020-02-27 18:23
![output-2020-02-27-20:21:10](https://user-images.githubusercontent.com/13259670/75474085-05312380-599f-11ea-8376-3b29d83b9a13.gif)

**Comment by gnumonk** [comment] 2020-02-28 01:53
Thanks, it is working after using npm install locally.

BTW,  can you please let me know how autocomplete is working in your case?
for me, after "import" no autocompletion is happening.

it would be good if you can share the .spacemacs which you are using for
Angular?

**Comment by yyoncho** [comment] 2020-02-28 05:45
I  don't use angular. 

See https://github.com/emacs-lsp/lsp-mode/issues/1451 I am closing the issue since it is solved, the completion misbehaviour will be tracked by #1451

**Closed by yyoncho** 2020-02-28 05:45 UTC
Labels: need-info
