### ISSUE TITLE
Extra lines when looking at types in lsp-metals

### ISSUE THREAD

**Issue by sorenbug** [emacs-lsp/lsp-mode#987] opened 2019-08-25 16:58 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/7751296/63653199-8a046180-c71e-11e9-87e4-a05fa8f3e6c9.png)

There are these extra lines that wrap.

**To Reproduce**
Use the Victor Mono font(?) and open a Scala project where you can check types.

**Expected behavior**
The definitions don't wrap lines.

**Which Language Server did you use**
lsp-metals

**OS**
NixOS
`Linux hydrogen 4.19.63 #1-NixOS SMP Wed Jul 31 05:27:12 UTC 2019 x86_64 GNU/Linux`

**Comment by yyoncho** [comment] 2019-08-25 17:26
Duplicate of: https://github.com/emacs-lsp/lsp-ui/issues/285

**Closed by yyoncho** 2019-08-25 17:26 UTC
