### ISSUE TITLE
rust-analyzer: mode line progress display broken with powerline

### ISSUE THREAD

**Issue by birkenfeld** [emacs-lsp/lsp-mode#3557] opened 2022-06-07 17:06 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When starting rust-analyzer for the first opened buffer in a project, it loads all the dependencies. During that, the display is confusing:

![bug](https://user-images.githubusercontent.com/144359/172439891-23e7e61c-40c7-4d93-ad55-898c3f25d905.png)

i.e. the "6923/33" part. The first part of the number before slash goes up to 100, the second part to the number after slash. I.e. the intended display is "69% 23/33".

**This only happens with Powerline active, not in the "plain" environment.** Is it a problem in powerline or in how lsp-mode puts strings into the mode-line variables?

### Steps to reproduce

Open any new project using rust-analyzer.

### Expected behavior

Showing `69% 23/33`.

### Which Language Server did you use?

rust-analyzer ad6810e90 2022-06-06 stable

### OS

Linux

**Comment by yyoncho** [comment] 2022-06-07 17:18
> **This only happens with Powerline active, not in the "plain" environment.** Is it a problem in powerline or in how lsp-mode puts strings into the mode-line variables?

if it works with vanilla, then the issue is with powerline this marking it as closed.

**Closed by yyoncho** 2022-06-07 17:18 UTC
Labels: bug
