### ISSUE TITLE
Support on-demand workspace/didChangeWorkspaceFolders notification after initialization

### ISSUE THREAD

**Issue by wyuenho** [emacs-lsp/lsp-mode#1775] opened 2020-06-10 06:05 UTC
**Describe the bug**
Currently, due to persistent session and the LSP initialize message signature, all the workspace folders ever created by LSP for all the projects that a multi-root LSP server activates on, e.g. eslint, will be sent to the server for indexing when that server is initialized. Furthermore, if the server supports file watches, (eslint again), and some project consists of thousands of files, this server start up process will consume too much memory unnecessarily, slow down start up, and prompt the user for file watch threshold reached.

**To Reproduce**
1. Configure lsp-mode by adding `lsp-deferred` to `js-mode-hook`
2. Configure lsp-eslint per the [wiki page](https://github.com/emacs-lsp/lsp-mode/wiki/LSP-ESlint-integration)
3. Delete the `.lsp-session-v1` file
4. Open some Typescript or Javascript repos with eslint configured
5. M-x lsp-describe-session shows the eslint process is running for all of these JS repos
6. Restart emacs
7. Open a JS file in any of repos
8. M-x lsp-describe-session shows eslint is running for all of the repos, not just the repo of the opened file.

**Expected behavior**
LSP should not notify multi-root servers the full list of workspace folders on initialization. When a file belonging to a different workspace folder is opened, it is only then should LSP notify the multi-root server applicable with the `workspace/didChangeWorkspaceFolders` message.

**Which Language Server did you use**
lsp-eslint

**Comment by yyoncho** [comment] 2020-06-15 06:46
The following piece of code should be sufficient to achieve what you want:

```
  (with-eval-after-load 'lsp-mode
    (eval '(setf (lsp-session-server-id->folders (lsp-session)) (ht))))
```

**Comment by wyuenho** [comment] 2020-06-15 11:33
It doesn't. I set `lsp-keep-workspace-alive` to `nil`. I can visit 10 different JS files from 10 different repos, kill all the JS buffers, and then the next one opened will trigger indexing all 10 repos again.

**Comment by yyoncho** [comment] 2020-06-15 14:33
the proposed code works between Emacs restarts, here it is the code to make that work in single session:
``` emacs-lisp
(advice-add 'lsp :before (lambda (&rest _args) (setf (lsp-session-server-id->folders (lsp-session)) (ht))))
```

**Comment by wyuenho** [comment] 2020-06-16 12:56
I get this in *Messages*

`let*: Symbol’s function definition is void: \(setf\ lsp-session-server-id->folders\)`

But even if it did work, it's not what I ask for, because this effectively wipes out the session folders every time I visit a file. What I'm asking is have the multi-root LSP servers to index incrementally and on demand instead of indexing everything or nothing at all.

**Comment by yyoncho** [comment] 2020-06-16 13:27
No, it won't work like that. The effect of this code is that lsp mode will always start the language server with only the current workspace folder. Then when you open a file from another project it will be added for indexing at that point.

Something like that will be able to bypass the error(not sure what is the best way to avoid that error though). 

``` elisp
(advice-add 'lsp :before (lambda (&rest _args) (eval '(setf (lsp-session-server-id->folders (lsp-session)) (ht)))))
```

**Comment by wyuenho** [comment] 2020-06-16 14:15
This just gets me this error after visiting a second file in a different folder

`LSP :: Sending to process failed with the following error: Process eslint not running`

**Comment by yyoncho** [comment] 2020-06-16 15:07
This is odd. I will have to setup eslint + typescript ls to try to reproduce it. I have tested the path with jdtls which is also multiroot server and works fine but it is standalone server.

**Comment by wyuenho** [comment] 2020-06-16 15:23
It doesn't alway give me that error. As I've said, I have `lsp-keep-workspace-alive` set to nil. After closing all the JS buffers, the workspace kills all servers, but then after opening 2 JS files from 2 repos, the second file will give me that error.

**Comment by yyoncho** [comment] 2020-06-24 19:35
I think that your issue was fixed by https://github.com/emacs-lsp/lsp-mode/commit/7b0b9c3785222ed89744a0d1376e764c30e950ac . Seems like we were not cleaning up the buffers correctly when you kill the server.

**Comment by leungbk** [comment] 2020-06-28 23:44
Yeah, this problem doesn't appear for me anymore.

**Comment by yyoncho** [comment] 2020-07-04 05:05
@leungbk do you have steps to reproduce?

**Comment by leungbk** [comment] 2020-07-06 02:42
> @leungbk do you have steps to reproduce?

Same procedure as OP, basically.

I cloned `vscode-eslint`, and then made a separate git project in with nothing but a `.eslintrc.base.json`. Then I deleted `.lsp-session-v1` and exited Emacs.

I visited for the first time the above projects using the below init, with ESLint starting up in each of them. Then I restarted Emacs. Once I opened `.eslintrc.base.json` in a single repo, I did `M-x lsp-describe-session` and saw that the ESLint server was running for both repos.

Your workaround posted above works for me, though.

``` elisp
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(setq debug-on-error t)

(setq read-process-output-max (* 1024 1024 3))

(use-package company
  :config
  (global-company-mode 1)
  (setq company-show-numbers t))

(use-package lsp-mode
  :hook (((
           js-mode
           typescript-mode) . lsp)
         )
  :init
  (setq lsp-prefer-flymake nil)
  (setq lsp-prefer-capf t)

  (setq
   lsp-eslint-server-command
   '("node"
     "/home/brian/.vscode/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js"
     "--stdio"))

  :config
  (setq lsp-log-io t))

(use-package projectile
  :config
  (projectile-mode 1))

(use-package yasnippet
  :config
  (yas-global-mode 1))

(require 'dired-x)

(use-package typescript-mode)

(use-package flycheck)

```

**Comment by wyuenho** [comment] 2020-07-08 03:08
I don't understand why we are spending so much time on hacks and documentation when we could just support delayed workspace/didChangeWorkspaceFolders notifications to the server. Is that even in the works?

**Comment by kiennq** [comment] 2020-07-16 13:59
This is actually really useful especially when Emacs is running as daemon (so basically only one big session).
Would you like to provide a PR for this?

**Comment by wyuenho** [comment] 2020-07-16 14:19
I'd love to, but all the anaphoric macros in the code gives me a headache. Someone more familiar with the code base should do it.

**Comment by yyoncho** [comment] 2020-07-24 17:47
The issue with restart was sorted out and it was not related to the suggested fix. I am marking this as closed(refer to the FAQ section on how to achieve that behavior). Please reopen or file another issue if you hit another issue related to the provided snippet.

**Closed** 2020-07-24 17:47 UTC

**Comment by wyuenho** [comment] 2020-08-06 19:01
And... now `lsp-keep-workspace-alive` is broken, I'll file another issue.

**Comment by raxod502** [comment] 2022-05-12 02:32
I am confused, why is this advice not the default behavior? In what situation is the default behavior desired?
