### ISSUE TITLE
server xxx-ls exited with status exit. Do you want to restart it?

### ISSUE THREAD

**Issue by Lecrapouille** [emacs-lsp/lsp-mode#983] opened 2019-08-22 19:37 UTC
**Describe the bug**
Following the ticket https://github.com/emacs-lsp/lsp-mode/issues/285 but a little different. I tried lsp with Julia and C++ and I noticed that when editing and typing something wrong, the server immediately crashes and produces this error message "server xxx-ls exited with status exit. Do you want to restart it?" This is very annoying because happens every time you are editing a code source and the prompt does not let you use macros until you type 'y' (because typing 'n' just make restart a process killing itself immediately with the same prompt).

**To Reproduce**
Just editing your code source as usual :) Just make a typo on a variable/function name. The lsp process crashes immediately.

**Expected behavior**
- The process should not crash.
- When crashing, allow you to edit your code and allow you to use Emacs commands.
- When a typo is detected, you should only surround the word with `~~~~` as flyspell does.

**Which Language Server did you use**
lsp-julia, lsp-c++

**OS**
Debian 10 64 bits. Emacs-25

**Error callstack**
Nothing

**Comment by yyoncho** [comment] 2019-08-22 19:49
> This is very annoying because happens every time you are editing a code source and the prompt does not let you use macros until you type 'y' 

As per readme - `lsp-restart` controls how lsp-mode handles server crash, here are the options: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L222 

> The process should not crash.

Take a look at the corresponding stderr buffer. Such behaviour indicates either server bug or client misconfiguration. I am closing the bug since based on the description there is no indication of lsp-mode misbehaviour. Before reopening the issue, please make sure that you provide a sample project + steps which can be used to reproduce the issue with.

**Closed by yyoncho** 2019-08-22 19:49 UTC
