### ISSUE TITLE
Non-integer line number

### ISSUE THREAD

**Issue by Elvecent** [emacs-lsp/lsp-mode#2435] opened 2020-12-23 06:43 UTC
Hello. I'm using lsp-mode 20201222.850 with lsp-haskell 20201210.1702 on Ubuntu 20.04 and getting the following error:
```
Error running timer `lsp--on-idle`: (wrong-type-argument integerp 9.223372036854776e+18)
```
I've also seen someone with the same issue on Gitter: https://gitter.im/syl20bnr/spacemacs?at=5fe23d6eac9d8e7463c68a5c

In my case, this is what debugger shows:
```
Debugger entered--Lisp error: (wrong-type-argument integerp 9.223372036854776e+18)
  lsp--line-character-to-point(9.223372036854776e+18 0)
  lsp--position-to-point(#<hash-table equal 2/65 0x1b4ed99>)
  lsp-headerline--symbol-with-action(#<hash-table equal 5/65 0x1af26f1> #("API" 0 3 (font-lock-face lsp-headerline-breadcrumb-symbols-face)))
  #f(compiled-function (input0) #<bytecode 0x185aa79>)((#<hash-table equal 5/65 0x1af26f1> . 1))
  mapconcat(#f(compiled-function (input0) #<bytecode 0x185aa79>) ((#<hash-table equal 5/65 0x1af26f1> . 1)) #(" › " 1 2 (face lsp-headerline-breadcrumb-separator-face)))
  lsp-headerline--build-symbol-string()
  #f(compiled-function (segment) #<bytecode 0x185adad>)(symbols)
  mapconcat(#f(compiled-function (segment) #<bytecode 0x185adad>) (path-up-to-project file symbols) "")
  lsp-headerline--build-string()
  lsp-headerline--check-breadcrumb()
  run-hooks(lsp-on-idle-hook)
  lsp--on-idle(#<buffer API.hs>)
  apply(lsp--on-idle #<buffer API.hs>)
  timer-event-handler([t 0 1 0 nil lsp--on-idle (#<buffer API.hs>) idle 0])
```

This happened reliably every time I tried, on a basic Haskell project generated by `cabal init`.

**Comment by Elvecent** [comment] 2020-12-23 07:01
Interestingly, this number (but negated) show up in Go when trying to round infinity: https://www.cockroachlabs.com/blog/rounding-implementations-in-go/

**Comment by yyoncho** [comment] 2020-12-23 08:05
> lsp-headerline--symbol-with-action(#<hash-table equal 5/65 0x1af26f1> 

I will need the following:

1. The exact content of the file that you actually edit.
2. The result of documentSymbols that corresponds to that error. In the bug template, there are instructions how to collect the logs. It should look like this:
```
[Trace - 10:02:10 AM] Received response 'textDocument/documentSymbol - (315)' in 207ms.
Result: [
  {
    "name": "temp",
    "kind": 4,
    "range": {
      "start": {
        "line": 0,
        "character": 0
....
```
3. The trace information from `M-x trace-function RET lsp-headerline--symbol-with-action RET`

**Comment by Elvecent** [comment] 2020-12-23 08:18
https://gist.github.com/Elvecent/4980d9bf83c83aeb5b24290a1a33a23e

**Comment by yyoncho** [comment] 2020-12-23 12:04
It is a sever issue: https://gist.github.com/Elvecent/4980d9bf83c83aeb5b24290a1a33a23e#file-log-L545  

@alanz , any idea?

**Comment by alanz** [comment] 2020-12-23 12:41
Taking a look. The problem is in documentSymbols

```
[Trace - 01:12:34 PM] Received response 'textDocument/documentSymbol - (2)' in 40ms.
Result: [
  {
    "range": {
      "end": {
        "character": 0,
        "line": 9.223372036854776e+18
      },
      "start": {
        "character": 0,
        "line": 0
      }
    },

    "name": "Main",
    "children": [
      {
        "range": {
          "end": {
            "character": 30,
            "line": 3
          },
          "start": {
            "character": 0,
            "line": 3
          }
        },
        "name": "main",
        "kind": 12,
        "selectionRange": {
          "end": {
            "character": 30,
            "line": 3
          },
          "start": {
            "character": 0,
            "line": 3
          }
        }
      }
    ],
    "kind": 1,
    "selectionRange": {
      "end": {
        "character": 11,
        "line": 0
      },
      "start": {
        "character": 7,
        "line": 0
      }
    }
  }
]
...
```

**Comment by alanz** [comment] 2020-12-23 13:00
I created an upstream issue at https://github.com/haskell/ghcide/issues/962

**Comment by yyoncho** [comment] 2020-12-23 13:30
Thank you @alanz. Marking the bug as upstream, I will keep it open for tracking purposes.

**Comment by philip-bl** [comment] 2021-03-31 14:24
Is there a workaround to use while this is not fixed?

**Comment by yyoncho** [comment] 2021-03-31 16:17
@philip-bl try `(setq lsp-headerline-breadcrumb-enable nil)` but before the first time lsp-mode is started.

**Comment by yyoncho** [comment] 2021-05-06 20:39
I am closing this on our side. We have a workaround and there is nothing we can do in lsp-mode.el.

**Closed by yyoncho** 2021-05-06 20:39 UTC
Labels: upstream
