### ISSUE TITLE
signature help shows different possible signatures then the sideline view shows as quick fixes

### ISSUE THREAD

**Issue by jtl5770** [emacs-lsp/lsp-mode#1224] opened 2019-12-05 15:20 UTC
Best explained if looking at the screenshot attached:

It can be seen that I am looking at the "String.indexOf" methods. In the lv area I can choose between 4 different signatures. The signature quick fixes in the sideview offer 6 different ones - the middle two ones are missing from the signature help in the lv area.

And this is actually good, because those two methods seem to be not visible here (at least that's the next error message that is shown when actually selecting one of the two quick fix with (char[]....) in the signature.

So I assume that the logic to retrieve the possible signatures is different in both places, and the way the signature help is retrieving them seems correct....
![Screenshot from 2019-12-05 16-10-23](https://user-images.githubusercontent.com/24967370/70248388-1c36ef80-177b-11ea-8283-8baa78dc936f.png)

**Comment by yyoncho** [comment] 2019-12-05 15:38
The server is the one calculating the signatures and the quick fixes. Why do you think that the middle 2 should not be present? (I am apparently using different JDK version and I am unable to reproduce the issue). I will close the issue since it is not client-side but let's continue the discussion in order to determine whether there is an actual server-side issue.

**Closed by yyoncho** 2019-12-05 15:38 UTC

**Comment by jtl5770** [comment] 2019-12-05 16:22
Well, I would assume that if there are 6 quick fixes available for 6 different possible signatures, then there would also be 6 entries in the lv area. But there are only 4. And the two ones missing from the available quick fixes are the ones that generate an error when applied, as can be seen in the (new) screenshot attached (The situation after applying one of the two extra quick fixes).
![Screenshot from 2019-12-05 17-18-42](https://user-images.githubusercontent.com/24967370/70253523-aaaf6f00-1783-11ea-9b6a-b41dd49578b3.png)
So, whatever the reason is, I assume having a quick fix resulting in a follow-up error isn't as it should be...

**Comment by yyoncho** [comment] 2019-12-05 16:50
@jtl5770 confirmed. JDTLS suggests a quick fix even for methods that are not visible. Can you report that in jdt ls repo?

(cc @fbricon)

**Comment by fbricon** [comment] 2019-12-05 17:21
Actually, this issue can be reproduced in Eclipse IDE itself. So it's an upstream JDT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=553826

**Comment by yyoncho** [comment] 2019-12-05 17:25
@fbricon thank you!

**Comment by jtl5770** [comment] 2019-12-05 18:58
So I assume this will magically fix itself as soon as there is an updated language server with the fix incorporated?

**Comment by yyoncho** [comment] 2019-12-05 19:12
Yes.
