### ISSUE TITLE
Don't prompt about killing server processes

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#175] opened 2017-11-16 20:56 UTC
Killing LSP processes shouldn't cause data loss, so prompting the user when quitting them isn't necessary. I think this can be prevented by adding `:noquery t` at https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L49.

**Comment by bkchr** [comment] 2017-11-17 12:30
Duplicate of: https://github.com/emacs-lsp/lsp-mode/issues/174

**Comment by phst** [comment] 2017-11-17 13:40
This is not a duplicate. This bug is about Emacs prompting when killing a process. #174 is about `lsp-mode` prompting when closing a workspace. The issues are somewhat related, but these are two different prompts.

**Comment by bkchr** [comment] 2017-11-17 13:42
Ahh, sorry! I also tried to solve this problem by using [set-process-query-on-exit-flag](https://www.gnu.org/software/emacs/manual/html_node/elisp/Query-Before-Exit.html), but I could not get this working. Do you have any ideas?

**Comment by phst** [comment] 2017-11-17 13:46
That should work. I think adding `:noquery t` to `make-process` would be a bit cleaner, but in the end it's the same thing.
Your PR would still make sense to fix the `lsp-mode` prompt, though maybe some users want the prompt (thus I suggested adding a user option).

**Comment by bkchr** [comment] 2017-11-17 13:53
I also tried `:noquery t` and that did not change the result...
I could close my pr and you open a new one with user prompt and maybe a fix for this issue?

**Comment by phst** [comment] 2017-11-17 13:58
You PR is fine. I'd let the maintainer decide whether the behavior should be controllable by a user option.

Adding `:noquery t` does not prevent the prompt issued by `lsp-mode`. It prevents different prompts when exiting Emacs while there are still running LSP processes that haven't been closed otherwise.

**Comment by bkchr** [comment] 2017-11-17 14:08
Yeah I know what you wanted to achieve with `:noquery t`and I tested that, but for me it did not work. I will maybe give it another try!

**Comment by vibhavp** [comment] 2017-11-17 16:25
Indeed, the user doesn't interact with the server directly, asking the user isn't of any use.

**Closed** 2017-11-17 16:26 UTC

**Comment by phst** [comment] 2017-11-17 17:21
As explained above, we still should have `:noquery t` so that users aren't prompted about lingering processes when quitting Emacs.
