### ISSUE TITLE
lsp completion disabled during multiple servers

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#2244] opened 2020-10-11 22:12 UTC
**Describe the bug**
I am trying to get both vls and eslint running on my vue buffers. When I initialize lsp, both vls and eslint startup without any issues, however I notice that `lsp-completion-mode` is automatically disabled on the buffer.
I can manually enable `lsp-completion-mode` and everything works fine, but I want to know why this is happening because, if i just use the vls server this issue does not happen and `lsp-completion-mode` is true.

**To Reproduce**
Install eslint vscode as described in the wiki and setup the lsp-eslint-server-command to the correct path.
Install vue language server (vls) and setup correctly.
Open a .vue buffer.

**Expected behavior**
`lsp-completion-mode` should be enabled automatically.

**Which Language Server did you use**
lsp-eslint, vls

**OS**
GNU/Linux

**Comment by vikigenius** [comment] 2020-10-11 22:37
Additionally, I notice that this issue does not happen sometimes when I debug and manually continue execution. This might be possibly due to some race condition?

**Comment by yyoncho** [comment] 2020-10-12 06:09
I think that I know what the issue is. Can you confirm that closing and reopening the buffer fixes the issue?

**Comment by vikigenius** [comment] 2020-10-12 07:02
@yyoncho It does not fix the issue. I just tried closing and reopening, and also revert-buffer. I also tried opening another buffer in the same project, but it is always the same `lsp-completion-mode` is always disabled automatically.

I actually define vue-mode as a derived mode of web-mode and then add lsp! (doom emacs convenience function: calls lsp-deferred interactively) to the mode hook. Now removing that and manually calling lsp in a vue buffer also has the same issue.

In all of the cases, unsetting the eslint-server-command and making sure only vls starts up fixes the issue and  completion is enabled automatically.

**Comment by yyoncho** [comment] 2020-10-12 07:05
What do you get when you do `M-: (lsp-feature? "textDocument/completion") RET` in that buffer?

**Comment by vikigenius** [comment] 2020-10-12 07:27
@yyoncho 
I tried to evaluate the given expression and it gives me a huge bunch of output.

<details>
<summary><b>Eval Output:</b></summary>
<p>


```
(#s(lsp--workspace nil #s(hash-table size 14 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                     ("textDocumentSync" 1 "completionProvider" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                              ("resolveProvider" t "triggerCharacters"
                                                                                               ["." ":" "<" "\"" "'" "/" "@" "*" " "]))
                                      "signatureHelpProvider" #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                            ("triggerCharacters"
                                                                             ["("]))
                                      "documentFormattingProvider" nil "hoverProvider" t "documentHighlightProvider" t "documentLinkProvider" #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                            ("resolveProvider" nil))
                                      "documentSymbolProvider" t "definitionProvider" t "referencesProvider" t "codeActionProvider" t "colorProvider" t "executeCommandProvider" #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                                               ("commands"
                                                                                                                                                                                                ["vetur.applyRefactorCommand"]))
                                      "foldingRangeProvider" t))
                   (#s(lsp--registered-capability "73fa768c-2afb-4570-bf0e-3e47a455b256" "textDocument/formatting" #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                 ("documentSelector"
                                                                                                                                  ["vue"]))))
                   "/home/void/Projects/nlpdemo" #s(lsp--client nil nil
                                                                (:connect
                                                                 (closure
                                                                  ((test-command)
                                                                   (command closure
                                                                            (t)
                                                                            nil
                                                                            (cons
                                                                             (or
                                                                              (executable-find
                                                                               (cl-first lsp-vetur-server-command))
                                                                              (lsp-package-path 'vetur-language-server))
                                                                             (cl-rest lsp-vetur-server-command)))
                                                                   cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines dap-ui-menu-items dap-auto-configure-mode t)
                                                                  (filter sentinel name environment-fn)
                                                                  (let
                                                                      ((final-command
                                                                        (lsp-resolve-final-function command))
                                                                       (process-name
                                                                        (generate-new-buffer-name name))
                                                                       (process-environment
                                                                        (lsp--compute-process-environment environment-fn)))
                                                                    (let*
                                                                        ((stderr-buf
                                                                          (format "*%s::stderr*" process-name))
                                                                         (proc
                                                                          (make-process :name process-name :connection-type 'pipe :buffer
                                                                                        (format "*%s*" process-name)
                                                                                        :coding 'no-conversion :command final-command :filter filter :sentinel sentinel :stderr stderr-buf :noquery t)))
                                                                      (set-process-query-on-exit-flag proc nil)
                                                                      (set-process-query-on-exit-flag
                                                                       (get-buffer-process stderr-buf)
                                                                       nil)
                                                                      (save-current-buffer
                                                                        (set-buffer
                                                                         (get-buffer stderr-buf))
                                                                        (special-mode))
                                                                      (cons proc proc))))
                                                                 :test\?
                                                                 (closure
                                                                  ((test-command)
                                                                   (command closure
                                                                            (t)
                                                                            nil
                                                                            (cons
                                                                             (or
                                                                              (executable-find
                                                                               (cl-first lsp-vetur-server-command))
                                                                              (lsp-package-path 'vetur-language-server))
                                                                             (cl-rest lsp-vetur-server-command)))
                                                                   cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines dap-ui-menu-items dap-auto-configure-mode t)
                                                                  nil
                                                                  (lsp-server-present\?
                                                                   (lsp-resolve-final-function command))))
                                                                nil
                                                                ("readFile .*? requested by Vue but content not available")
                                                                #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                              ())
                                                                #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                              ())
                                                                #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                              ())
                                                                nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                  ())
                                                                #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                              ())
                                                                nil
                                                                (closure
                                                                 (t)
                                                                 (filename _mode)
                                                                 (string=
                                                                  (file-name-extension filename)
                                                                  "vue"))
                                                                -1 vls t
                                                                (closure
                                                                 (t)
                                                                 nil
                                                                 (ht-merge
                                                                  (lsp-configuration-section "vetur")
                                                                  (lsp-configuration-section "html")
                                                                  (lsp-configuration-section "javascript")
                                                                  (lsp-configuration-section "typescript")
                                                                  (lsp-configuration-section "emmet")
                                                                  (let
                                                                      ((ht-temp
                                                                        (ht-create)))
                                                                    (ht-set! ht-temp "globalSnippetDir" lsp-vetur-global-snippets-dir)
                                                                    ht-temp)))
                                                                nil nil nil
                                                                (closure
                                                                 (t)
                                                                 (workspace)
                                                                 (let
                                                                     ((lsp--cur-workspace workspace))
                                                                   (lsp--set-configuration
                                                                    (ht-merge
                                                                     (lsp-configuration-section "vetur")
                                                                     (lsp-configuration-section "html")
                                                                     (lsp-configuration-section "javascript")
                                                                     (lsp-configuration-section "emmet")
                                                                     (lsp-configuration-section "typescript")))))
                                                                nil nil nil nil nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                      ())
                                                                (closure
                                                                 (t)
                                                                 (_client callback error-callback _update\?)
                                                                 (lsp-package-ensure 'vetur-language-server callback error-callback))
                                                                nil nil)
                   nil #<process vls> #<process vls>
                   (#<buffer App.vue>)
                   nil nil nil initialized #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                         ())
                   #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                 ())
                   nil 0 nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                               ())
                   #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                 ())))

```
</p>
</details>

Take a look because I am not sure if this is what I am supposed to be getting

**Comment by yyoncho** [comment] 2020-10-12 07:35
This looks good. I will have to check if reproduces. Just to make sure that the issue is not somewhere else, please call M-x lsp after M-x toggle-debug-on-error.

**Comment by vikigenius** [comment] 2020-10-12 07:41
I did as you suggested, and I don't see any errors being shown and the issue still persists.
Here is the message buffer just for reference:

```
Debug on Error enabled globally
LSP :: Guessed project root is ~/Projects/nlpdemo
LSP :: Connected to [vls:6601 status:starting][eslint:6602 status:starting].
LSP :: eslint:6602 initialized successfully
LSP :: vls:6601 initialized successfully
```

**Comment by beem812** [comment] 2020-10-17 15:48
I believe I am also seeing this issue while using eslint and a typescript language server. Completion works fine when manually enabled but it doesn't start enabled.

**Comment by vikigenius** [comment] 2020-10-17 21:57
@yyoncho Were you able to reproduce the issue ?

**Comment by dex157** [comment] 2020-10-18 10:19
I caught the same error when using ts-server and eslint 😞

**Comment by yyoncho** [comment] 2020-10-21 17:36
> @yyoncho Were you able to reproduce the issue ?

I will be inactive for some time.

**Comment by artemkovalyov** [comment] 2020-11-02 22:54
I see the same issue with TS/JS server + Eslint

**Closed** 2020-11-05 18:27 UTC
Labels: completion
