### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by daisylab** [emacs-lsp/lsp-mode#4545] opened 2024-09-14 02:47 UTC
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

lsp-mode package won't be installed.

### Steps to reproduce

1. start emacs.
2. add melpa.
3. M-x package-install lsp-mode
4. Package 'spinner-1.7.3' is unavailable.

### Expected behavior

I wanted lsp-mode to be installed on my emacs (via WSL mode on Windows 10).

### Which Language Server did you use?

I could not use any language server because lsp-mode package was not properly installed. I wanted to switch from elpy (I use python.)

### OS

Windows

**Comment by jcs090218** [comment] 2024-09-14 02:51
See our FAQ section, https://emacs-lsp.github.io/lsp-mode/page/faq/#i-am-getting-package-spinner-173-is-unavailable-when-trying-to-install-lsp-mode.

Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/1095.

**Comment by daisylab** [comment] 2024-09-14 04:29
Thanks for your quick response. I will try.

**Comment by daisylab** [comment] 2024-09-14 04:52
Thanks. It seems to work.

The following URL helped a lot.

https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

**Comment by jcs090218** [comment] 2024-09-14 05:08
I'll close the for now since it isn't the `lsp-mode`'s issue. :)

**Closed by jcs090218** 2024-09-14 05:08 UTC
Labels: bug
