### ISSUE TITLE
Intermittent connection in typescript-language-server via Docker-tramp

### ISSUE THREAD

**Issue by MokkeMeguru** [emacs-lsp/lsp-mode#1240] opened 2019-12-10 21:49 UTC
I want to use typescript-language-server in docker's project via tramp-mode.

So I try open docker container in eshell and evaluate this function.
```
@598d6202b669 /docker:598d6202b669:/usr/app λ (lsp-register-client
 (make-lsp-client :new-connection
                  (lsp-tramp-connection "typescript-language-server --stdio")
                  :major-modes '(typescript-mode)
                  :remote? t
                  :server-id 'typescript-remote))
```
And also, I installed typescript-language-server typescript in the docker.

When I open container's file with lsp-mode, but I got an error message "Server typescript-remote:32228 exited with status exit. Do you want to restart it? (y/n)" **every few** seconds.

I can get some lsp's refactoring between **the few** seconds.

So I want to know how to keep a lsp's connection.

Thanks!

**Comment by yyoncho** [comment] 2019-12-10 22:39
There might be another problem but `"typescript-language-server --stdio"` should be `(list "typescript-language-server"  "--stdio")`.

**Comment by MokkeMeguru** [comment] 2019-12-11 05:50
No. lsp-tramp-connection's argument is below
```
commands & optional GENERATE-ERROR-FILE-FN
```

**Comment by MokkeMeguru** [comment] 2019-12-11 06:04
if we run this command instead of previous one, we receive same error message at soon.
```
(lsp-register-client
 (make-lsp-client :new-connection
                  (lsp-tramp-connection "typescript-language-server")
                  :major-modes '(typescript-mode)
                  :priority 2
                  :remote? t
                  :server-id 'typescript-remote))
```

I know this tramp connection is succeed in pyls. (https://qiita.com/MeguruMokke/items/2188bd32b253233bdf73 sorry I wrote this article in Japanese... ) .

If you run pyls in command line,  you found pyls is running something like a server.
So I think typescript-language-server will be running as something like a server too.

Let's run typescript-language-server in command line.

```
$ npm install typescript-language-server typescript
$ typescript-language-server
Connection type required (stdio, node-ipc, socket). Refer to --help for more details.
```

So we should use **stdio** or **node-ipc** or **socket**

I think there are two solution to connect lsp server
- **stdio**
this is my solution. I think we can connect via tramp.
- **socket**
I don't know how to set the connection port number.

**Comment by yyoncho** [comment] 2019-12-11 06:09
As I already mentioned, the params must be list, not string when the command has arguments, please test this one:

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-tramp-connection '("typescript-language-server" "--stdio"))
                  :major-modes '(typescript-mode)
                  :remote? t
                  :server-id 'typescript-remote))
```

**Comment by MokkeMeguru** [comment] 2019-12-11 06:15
I got  same error...

**Comment by yyoncho** [comment] 2019-12-11 06:17
@MokkeMeguru ok, I will try it on my side. Meanwhile, check what do you have in the stderr buffer for the language server.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:20
lsp-log
```
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for /docker:598d6202b669:/usr/app/index.tsx: (server-id typescript-remote, priority 0)
The following clients were selected based on priority: (server-id typescript-remote, priority 0)
```

Message
```
Tramp: Opening connection for 598d6202b669 using docker...
Tramp: Sending command ‘exec docker  exec -it  598d6202b669 sh’
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on ‘598d6202b669’
Tramp: Opening connection for 598d6202b669 using docker...done
LSP :: Connected to [typescript-remote:31355 status:starting].
LSP :: typescript-remote:31355 initialized successfully
LSP :: typescript-remote has exited (exited abnormally with code 1)
Server typescript-remote:31355 exited with status exit. Do you want to restart it? (y or n) n
```

any more datasource?

**Comment by yyoncho** [comment] 2019-12-11 06:22
Yes, look for `*typescript-remote::stderr*` buffer.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:24
I cannot found `*typescript-remote::stderr*`
there is only `typescript-remote` buffer, and this buffer is empty.

**Comment by yyoncho** [comment] 2019-12-11 06:25
Ah, right - the when you are using tramp there is no stderr buffer because tramp does not support stderr stream. Please, check the content of `/tmp/` directory on the remote host for error file.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:28
```
/docker:598d6202b669:/tmp:
  drwxrwxrwt 1 root root 12288 Dec 11 06:27 .
  drwxr-xr-x 1 root root  4096 Dec 10 21:18 ..
-rw-r--r-- 1 root root     0 Dec 11 06:27  typescript-remote-8-stderr
```
I found empty folder...

**Comment by yyoncho** [comment] 2019-12-11 06:30
Ok, I will test on my side and I will let you know.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:30
https://github.com/MokkeMeguru/test-typescript-language-server
This is my test-project

**Comment by yyoncho** [comment] 2019-12-11 06:40
I am able to reproduce your issue, I will need some time to investigate.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:42
OK, And I found a option which print some log file
https://github.com/MokkeMeguru/test-typescript-language-server/blob/master/memo.lisp

You can see typescript-language-server's log in /tmp/tslog.txt

Thanks your help!

**Comment by yyoncho** [comment] 2019-12-11 06:46
One more thing, can you set lsp-print-io to t and the check the content of `*lsp-log: typescript-remote:PID*` . On my side, the server starts successfully but it just crashes at some point.

**Comment by MokkeMeguru** [comment] 2019-12-11 06:51
you can see Like this?
![image](https://user-images.githubusercontent.com/30849444/70598362-03708300-1c2e-11ea-988b-e461af5bc009.png)

**Comment by MokkeMeguru** [comment] 2019-12-11 07:02
full log is here https://gist.github.com/MokkeMeguru/9704154a180b558b954fa89c6ec40a3b

**Comment by yyoncho** [comment] 2019-12-11 07:18
Ok, so the problem seems to be in typescript language server itself. It does not like something passed to it and it just dies. lsp-mode tramp facilities work fine. And it is not obvious...

As a side note, do you know that you can run a language server in docker container over local sources? See https://github.com/emacs-lsp/lsp-docker/ and https://github.com/emacs-lsp/lsp-docker/blob/master/lsp-docker.el#L119

**Comment by MokkeMeguru** [comment] 2019-12-11 07:30
I'm coding dockerized project.
Can I use your lsp-docker?

What you say is like this image?
```
dockerized typescript-project <=> localhost <=> lsp-docker
```

**Comment by yyoncho** [comment] 2019-12-11 07:41
you can replace tramp with lsp-docker.

**Comment by MokkeMeguru** [comment] 2019-12-11 07:49
It sounds to me quite difficult.

For example, my test-project https://github.com/MokkeMeguru/test-typescript-language-server,
I should do...
0. run docker-compose

```
docker-compose run workspace
docker ps
=> 
ac2736529d12        test-ts-lsp_workspace   "docker-entrypoint.s…"   31 seconds ago      Up 28 seconds                                  test-ts-lsp_workspace_run_5a93d2877899

```

1. add new lsp-docker-register-client
eval this command in eshell ?
```
(lsp-docker-register-client
   :server-id 'typescript-remote
   :priority 1
   :docker-server-id 'typescript-docker
   :docker-image-id ac2736529d12
   :docker-container-name test-ts-lsp_workspace_run_5a93d2877899
   :server-command "typescript-language-server --stdio --log-level 4 --tsserver-log-file /tmp/tslog.txt"
   :path-mappings '(("/usr/app" . "/usr/app")) ;; I don't know what means.
   :launch-server-cmd-fn #'lsp-docker-launch-new-container)) ;; I don't know that means...
```

2. I don't know what should I do?

**Comment by yyoncho** [comment] 2019-12-11 07:54
> :server-id 'typescript-remote

Should be `ts-ls`

> :path-mappings '(("/usr/app" . "/usr/app"))

Here you have local path (on your machine) and the path the project is mounted in the docker. Then open a file from the local project and lsp-mode will fire up a docker running the language server.

> :launch-server-cmd-fn #'lsp-docker-launch-new-container)

This setting specifies whether you want to run an image or container.

**Comment by MokkeMeguru** [comment] 2019-12-11 08:05
Launch? 
Cannot I connect exists docker-project?

**Comment by MokkeMeguru** [comment] 2019-12-11 08:17
https://github.com/MokkeMeguru/test-typescript-language-server

I update my test-project.
And I found I got the same crash of language-server...

**Comment by mihai-dinu** [comment] 2020-01-23 18:27
I am having the same problems with using tramp and the typescript-language-server installed on a remote machine. Not using any docker-lsp things, just lsp-mode installed with emacs.

Emacs version is 26.3 with very recent lsp-mode (pulled from Github a week ago). 

```sh
npm list -g                                                                                                                                                                
├── typescript@3.7.5
└─┬ typescript-language-server@0.4.0
```

Please let me know what other info I can provide to help with the issue. 

There are no error logs from the typescript-language-server. 

*Messages*
```sh
LSP :: Guessed project root is /ssh:myremotehost:/local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloWorldCDK/
LSP :: Connected to [typescript-lsp-remote:77735 status:starting].
LSP :: typescript-lsp-remote:77735 initialized successfully
LSP :: typescript-lsp-remote has exited (exited abnormally with code 1)
Server typescript-lsp-remote:77735 exited with status exit. Do you want to restart it? (y or n) n
```

*lsp-log*
```sh
Command "/home/dimiha/npm-global/bin/typescript-language-server --stdio" is present on the path.
Found the following clients for /ssh:clouddesk:/local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts: (server-id typescript-lsp-remote, priority 0)
The following clients were selected based on priority: (server-id typescript-lsp-remote, priority 0)
```

<details>
<summary>*lsp-log-typescript-remote*</summary>

```
[Trace - 07:13:12 PM] Sending request 'initialize - (10)'.
Params: {
  "processId": 77409,
  "rootPath": "/local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK",
  "clientInfo": {
    "name": "vscode",
    "version": "1.41.1"
  },
  "rootUri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "semanticHighlightingCapabilities": {
        "semanticHighlighting": false
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown"
          ]
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true,
        "rangeLimit": null,
        "lineFoldingOnly": false
      },
      "callHierarchy": {
        "dynamicRegistration": false
      }
    },
    "window": {
      "workDoneProgress": true
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1"
}


[Trace - 07:13:13 PM] Received response 'initialize - (10)' in 138ms.
Result: {
  "capabilities": {
    "callsProvider": true,
    "foldingRangeProvider": true,
    "typeDefinitionProvider": true,
    "implementationProvider": true,
    "workspaceSymbolProvider": true,
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ",",
        "<"
      ]
    },
    "referencesProvider": true,
    "renameProvider": true,
    "hoverProvider": true,
    "executeCommandProvider": {
      "commands": [
        "_typescript.applyWorkspaceEdit",
        "_typescript.applyCodeAction",
        "_typescript.applyRefactoring",
        "_typescript.organizeImports",
        "_typescript.applyRenameFile"
      ]
    },
    "documentSymbolProvider": true,
    "documentHighlightProvider": true,
    "documentFormattingProvider": true,
    "definitionProvider": true,
    "codeActionProvider": true,
    "completionProvider": {
      "resolveProvider": true,
      "triggerCharacters": [
        ".",
        "\"",
        "'",
        "/",
        "@",
        "<"
      ]
    },
    "textDocumentSync": 2
  }
}


[Trace - 07:13:13 PM] Sending notification 'initialized'.
Params: {
}


[Trace - 07:13:13 PM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts",
    "languageId": "typescript",
    "version": 0,
    "text": "import cdk = require('@aws-cdk/core');\nimport ecs = require('@aws-cdk/aws-ecs');\nimport ec2 = require('@aws-cdk/aws-ec2');\nimport ecsPatterns = require('@aws-cdk/aws-ecs-patterns');\nimport elbv2 = require(\"@aws-cdk/aws-elasticloadbalancingv2\");\n\nimport { BrazilPackage, BrazilContainerImage, DeploymentStack, DogmaTagsOptions, SoftwareType } from \"@amzn/pipelines\";\nimport { DeploymentEnvironment } from '@amzn/builder-tools-scaffolding';\nimport { getAmazonDefaultEcsTaskInstanceRole } from \"@amzn/cdk-bones-internal\";\nimport { HydraTestRunResources } from '@amzn/hydra';\n\n\n\nexport interface EcsServiceStackProps {\n    readonly ecsCluster: ecs.ICluster;\n    readonly stage: string;\n    readonly env: DeploymentEnvironment;\n    readonly stackName?: string;\n    /**\n     * Stack tags that will be applied to all the taggable resources and the stack itself.\n     *\n     * @default {}\n     */\n    readonly tags?: {\n        [key: string]: string;\n    };\n    /**\n     * Optional Dogma tags. Read `DogmaTags` for mode details or\n     * this wiki https://w.amazon.com/bin/view/ReleaseExcellence/Team/Designs/PDGTargetSupport/Tags/\n     */\n    readonly dogmaTags?: DogmaTagsOptions;\n}\n\nexport class EcsServiceStack extends DeploymentStack {\n    public readonly service: ecsPatterns.NetworkLoadBalancedFargateService;\n    public readonly hydraResources: HydraTestRunResources;\n    public readonly loadBalancerOutput: cdk.CfnOutput;\n    constructor(parent: cdk.App, name: string, props: EcsServiceStackProps) {\n        super(parent, name, {\n            dogmaTags: props.dogmaTags,\n            env: props.env,\n            softwareType: SoftwareType.LONG_RUNNING_SERVICE,\n            stackName: props.stackName,\n            tags: props.tags,\n        });\n\n        // CloudFormation Resources\n        this.service = new ecsPatterns.NetworkLoadBalancedFargateService(this, 'Service', {\n            cluster: props.ecsCluster,\n            memoryLimitMiB: 1024,\n            cpu: 512,\n            taskImageOptions: {\n                containerPort: 8080,\n                image: new BrazilContainerImage({\n                    brazilPackage: BrazilPackage.fromString('DimihaHelloAmazon'),\n                    transformPackage: BrazilPackage.fromString('DimihaHelloAmazonImageBuild'),\n                    componentName: 'service',\n                }),\n                taskRole: getAmazonDefaultEcsTaskInstanceRole(this),\n                environment: {'STAGE': props.stage}\n            },\n        });\n        const allPorts = new ec2.Port({protocol: ec2.Protocol.TCP, fromPort: 0, toPort: 65535, stringRepresentation: 'All'})\n        this.service.service.connections.allowFromAnyIpv4(allPorts);\n\n        this.service.targetGroup.configureHealthCheck({\n                port: \"traffic-port\",\n                protocol: elbv2.Protocol.TCP}\n        );\n        this.service.targetGroup.setAttribute(\"deregistration_delay.timeout_seconds\", \"60\");\n        this.hydraResources = new HydraTestRunResources(this, 'HydraTestRunResources', {\n            hydraEnvironment: props.env.hydraEnvironment,\n            targetPackage: BrazilPackage.fromString('DimihaHelloAmazonTests'),\n            securityGroups: this.service.service.connections.securityGroups,\n            vpcSubnets: props.ecsCluster.vpc.privateSubnets,\n        });\n        this.loadBalancerOutput = new cdk.CfnOutput(this, 'LoadBalanceDNS', {\n            value: this.service.loadBalancer.loadBalancerDnsName,\n        });\n    }\n}\n"
  }
}


[Trace - 07:13:13 PM] Sending request 'textDocument/documentHighlight - (11)'.
Params: {
  "textDocument": {
    "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts"
  },
  "position": {
    "line": 61,
    "character": 10
  }
}


[Trace - 07:13:15 PM] Received response 'textDocument/documentHighlight - (11)' in 630ms.
Result: []


[Trace - 07:13:15 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts"
}


[Trace - 07:13:15 PM] Sending request 'textDocument/codeAction - (12)'.
Params: {
  "textDocument": {
    "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts"
  },
  "range": {
    "start": {
      "line": 61,
      "character": 10
    },
    "end": {
      "line": 61,
      "character": 10
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 07:13:15 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts"
}


[Trace - 07:13:15 PM] Sending request 'textDocument/codeAction - (13)'.
Params: {
  "textDocument": {
    "uri": "file:///local/home/dimiha/workspace/ecs_cdk/src/DimihaHelloAmazonCDK/lib/ecs_service.ts"
  },
  "range": {
    "start": {
      "line": 61,
      "character": 10
    },
    "end": {
      "line": 61,
      "character": 10
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 07:13:15 PM] Received response 'textDocument/codeAction - (12)' in 83ms.
Result: []


[Trace - 07:13:15 PM] Received response 'textDocument/codeAction - (13)' in 74ms.
Result: []
```
</details>

**Comment by yyoncho** [comment] 2020-01-23 18:39
@mihai-dinu I spent a lot of time but I was unable to figure out why it is crashing. I think we should go down to debugging typescript-language-server. My guess is that tsserver internal process is crashing

**Comment by mihai-dinu** [comment] 2020-01-23 20:51
Thanks for the reply Ivan. Is there anything i can do to help?

**Comment by yyoncho** [comment] 2020-01-24 17:04
> Thanks for the reply Ivan. Is there anything i can do to help?

What I did is to inspect if lsp-mode is sending local path by mistake(e. g. we have path translation bug) but everything seemed to be ok. What I was planning was to start the typescript server with debugging enabled and with emacs attached via remote debugging to it and check what is causing the crash.

**Comment by yyoncho** [comment] 2020-02-12 16:36
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/1408

**Closed by yyoncho** 2020-02-12 16:36 UTC
