### ISSUE TITLE
File mode specification error on starting lsp-mode on a Python file

### ISSUE THREAD

**Issue by halloleo** [emacs-lsp/lsp-mode#2273] opened 2020-10-19 07:36 UTC
I just installed the latest version of `lsp-mode` into Emacs plus I  installed `python-language-server` via pip(x).

I set `lsp` in the python hook and when I open a Python file I get the following errors:

```
File mode specification error: (wrong-type-argument listp #s(lsp--client nil nil (:connect #[1028 \302\300!\303!\304!\305\306"\307\310\311\312\313\305\314	"\315\316\317\320\321\322\323\324&\325\326"\210\325\327!\326"\210r\330!q\210\331 \210)\211B\266\202)\207 [#[0 \207 [lsp-clients-python-command] 1] process-environment lsp-resolve-final-function generate-new-buffer-name lsp--compute-process-environment format *%s::stderr* make-process :name :connection-type pipe :buffer *%s* :coding no-conversion :command :filter :sentinel :stderr :noquery t set-process-query-on-exit-flag nil get-buffer-process get-buffer special-mode] 26 

(fn FILTER SENTINEL NAME ENVIRONMENT-FN)] :test? #[0 \301\302\300!!\207 [#[0 \207 [lsp-clients-python-command] 1] lsp-server-present? lsp-resolve-final-function] 3]) nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) (python-mode cython-mode) nil -1 pyls nil nil nil #[257 \207 [lsp-clients-python-library-directories] 2 
```

## Details:

* The version of `lsp-mode` is 20201018.509, `pyls` reports the version 0.35.1.
* Emacs is 26.3 (and 27 on anther machine where the same thing happens)
* The OS is macOS 10.13 (and 10.14 on the other machine)
* `*lsp-log*` is 

        Command "pyls" is present on the path.
        Command "pyls" is present on the path.
        Found the following clients for /Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py: (server-id pyls, priority -1)
        The following clients were selected based on priority: (server-id pyls, priority -1)

* `lsp-workspace-show-log` does not produce anything (no workspace created yet).

**Comment by leungbk** [comment] 2020-10-20 01:22
Could you run `M-x toggle-debug-on-error` and post a backtrace?

**Comment by halloleo** [comment] 2020-10-20 07:05
Sure, here you are:

```
Debugger entered--Lisp error: (wrong-type-argument listp #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil))
  lsp--start-workspace(#s(lsp-session :folders ("/Users/alba" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday") :folders-blacklist nil :server-id->folders #<hash-table equal 0/65 0x40efc02d> :folder->servers #<hash-table equal 0/65 0x40efc1d9> :metadata #<hash-table equal 0/65 0x42d4e081>) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil) "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday" nil)
  lsp--start-connection(#s(lsp-session :folders ("/Users/alba" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday") :folders-blacklist nil :server-id->folders #<hash-table equal 0/65 0x40efc02d> :folder->servers #<hash-table equal 0/65 0x40efc1d9> :metadata #<hash-table equal 0/65 0x42d4e081>) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil) "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday")
  #f(compiled-function (client) #<bytecode 0x42d54619>)(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil))
  mapcar(#f(compiled-function (client) #<bytecode 0x42d54619>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil)))
  -map(#f(compiled-function (client) #<bytecode 0x42d54619>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil)))
  lsp--ensure-lsp-servers(#s(lsp-session :folders ("/Users/alba" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday") :folders-blacklist nil :server-id->folders #<hash-table equal 0/65 0x40efc02d> :folder->servers #<hash-table equal 0/65 0x40efc1d9> :metadata #<hash-table equal 0/65 0x42d4e081>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x42d348a9>) :test\? #f(compiled-function () #<bytecode 0x42e88e65>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x42ce35e5> :request-handlers #<hash-table equal 0/65 0x42e7ee41> :response-handlers #<hash-table eql 0/65 0x42e7fd41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x42e80141> :action-handlers #<hash-table equal 0/65 0x42e66ad5> :major-modes (python-mode cython-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x42d0d4f1>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x42d0fcf1>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x42e66af5> :download-server-fn nil :download-in-progress? nil :buffers nil)) "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday" nil)
  lsp--try-project-root-workspaces(nil nil)
  lsp()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer tasks.py> "~/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py" nil nil "~/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py" (35188432 16777220))
  find-file-noselect("/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py" nil nil nil)
  find-file("/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py")
  #f(compiled-function (f) #<bytecode 0x40ddfa71>)("/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py")
  ivy-call()
  ivy-read("Recentf: " ("/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/gallery/settings.yaml" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/gallery/At_the_Portrait_Gallery_for_Felix_Birthday_IMG_9281.JPGAEB0.jpg" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/tasks.py" "/Users/alba/Dropbox/devel/webdev/prosopopee/felix_second_birthday/" "/Users/alba/opt/pipx/venvs/python-language-server/lib/python3.8/site-packages/pyls/_version.py" "/Users/alba/opt/pipx/venvs/python-language-server/lib/python3.8/site-packages/pyls/lsp.py" "/Users/alba/opt/pipx/venvs/python-language-server/lib/python3.8/site-packages/" "/Users/alba/Dropbox/emacs/user-lisp/leo-python.el" "/" "/Users/alba/Dropbox/emacs/site-lisp/elpa/lsp-mode-20201018.509/lsp-mode-autoloads.el" "/Users/alba/Dropbox/emacs/site-lisp/elpa/dash-functional-20200617.702/dash-functional-autoloads.el" "/Users/alba/Dropbox/emacs/site-lisp/elpa/f-20191110.1357/f-autoloads.el" "/Users/alba/Dropbox/emacs/site-lisp/elpa/ht-20200217.2331/ht-autoloads.el" "/Users/alba/Dropbox/emacs/site-lisp/elpa/spinner-1.7.3/spinner-autoloads.el" "/Users/alba/Dropbox/emacs/site-lisp/elpa/lv-20200507.1518/lv-autoloads.el" "/Users/alba/Dropbox/notes/deft/se-emacs How to filter the package list by package name.md" "/Users/alba/Dropbox/notes/deft/" "/Users/alba/Dropbox/notes/deft/se-emacs p.md" "/Applications/Optional/Homebrew/Emacs.app/Contents/Resources/lisp/emacs-lisp/package.el.gz" "/Users/alba/Dropbox/sync/unison-staged/emacs/" "/Applications/Optional/Fiji.app/README.md" "/Applications/Optional/Fiji.app/" "/Users/alba/tmp/" "/Users/alba/.xonshrc_bkp" "/Users/alba/" "/Users/alba/Dropbox/temp/fiji-macosx.zip" "/Users/alba/Dropbox/temp/" "/Users/alba/Dropbox/temp/Fiji.app/README.md" "/Users/alba/Dropbox/temp/Fiji.app/" "/Users/alba/Dropbox/journals/diary/" "/Users/alba/Dropbox/journals/diary/_assets/" "/Users/alba/Dropbox/notes/deft/dt-j Like the Mannequin man.mumd" "/Users/alba/Dropbox/notes/deft/dt-j Hurt.mumd" "/Users/alba/Dropbox/notes/deft/tsf.md" "/Users/alba/Dropbox/notes/deft/digIT-notes thankful and learnd.md" "/Users/alba/Dropbox/notes/deft/dylan poster text.md" "/Users/alba/Dropbox/notes/deft/digIT Appreciation of Dylan.md" "/Users/alba/Dropbox/notes/deft/gh-issue pipx valueerror.md" "/Users/alba/Dropbox/notes/deft/xonsh-recipes Test for a command.md" "/Users/alba/Dropbox/notes/deft/gitter-xonsh results from execx.md" "/Users/alba/Dropbox/notes/deft/dt-comp Making sure the dock size is correct.md" "/Users/alba/Dropbox/notes/deft/my-note Unsplash pics for Prosopopee.md" "/Users/alba/Dropbox/notes/deft/dt-j Our Kids choices.md" "/Users/alba/Dropbox/devel/csv/mlr-test/inp.csv" "/Users/alba/Dropbox/devel/csv/mlr-test/" "/Users/alba/Dropbox/devel/csv/" "/Users/alba/Dropbox/devel/" "/Users/alba/Dropbox/docs/profession/jobapps/ACIC_DataScientist_2020/MdResume/Leo_Broskas_Resume.log" "/Users/alba/Dropbox/docs/profession/jobapps/ACIC_DataScientist_2020/SCs/cmds.xsh" "/Users/alba/opt/pipx_list.txt" ...) :action #f(compiled-function (f) #<bytecode 0x40ddfa71>) :caller counsel-recentf)
  counsel-recentf()
  funcall-interactively(counsel-recentf)
  call-interactively(counsel-recentf nil nil)
  command-execute(counsel-recentf)
```

Thanks heaps for looking into this!

**Comment by jcs090218** [comment] 2020-10-20 07:11
It seems like we have un-handled data type. Mark this with `bug ` label for now.

Thanks for reporting this issue to us! 👍

**Comment by halloleo** [comment] 2020-10-20 07:19
Sorry to hassle, but... 

The strange thing for me is that on two other machines (both CentOS and using a slightly older version of lsp-mode) it works just fine. Only on macOS with the latest version of lsp-mode I have the trroubles...

Is it a version issue?

**Comment by jcs090218** [comment] 2020-10-20 07:33
> Is it a version issue?

I would guess... yes! I think we current do have an issue while progressing development. Like releasing next version but unfix the previous issue by accident, etc.

---

Anyway, this issue can cause by various of reasons. OS layer, language server layer, Emacs layer (cross-platform), to maybe the scripting layer (elisp), etc. I think we might need more information about it. Like maybe making a table with what is working and what isn't, for comparison purpose. Especially for the **older** version of `lsp-mode`, what version is it? From this, we are likely to have a good first step to deduct the possible cause from various of reasons.

And thank you for your report and your patience with us.

**Comment by halloleo** [comment] 2020-10-21 06:51
@jcs090218 On the machine where lsp-mode works fine I have version **20200826.525** installed. Both versions, the older and the newer one, are installed from melpa.

**Comment by leungbk** [comment] 2020-10-25 00:48
> @jcs090218 On the machine where lsp-mode works fine I have version **20200826.525** installed. Both versions, the older and the newer one, are installed from melpa.

Loading with `emacs -q -l my-lsp-repo/scripts/lsp-start-plain.el`, I cannot reproduce your error on macOS + Emacs 26.3; `pyls` seems to work well for me. Please try starting Emacs with this command and posting a backtrace after entering a Python file.

**Comment by yyoncho** [comment] 2021-05-20 18:05
Marking as closed - please reopen after confirming that the issue is present after doing https://github.com/emacs-lsp/lsp-mode/issues/2273#issuecomment-716075424

**Closed by yyoncho** 2021-05-20 18:05 UTC
Labels: bug
