### ISSUE TITLE
lsp-mode doesn't display signatures in Rust when lsp-eldoc-render-all is nil

### ISSUE THREAD

**Issue by RomeuG** [emacs-lsp/lsp-mode#2613] opened 2021-02-16 11:58 UTC
**Describe the bug**
If `lsp-eldoc-render-all` is nil, signatures are not displayed when using `rust`/`rust-analyzer`:

![image](https://user-images.githubusercontent.com/2325589/108059389-57a29e80-704d-11eb-975b-0e57e8f10f65.png)

When we enable `lsp-eldoc-render-all`, all is displayed normally:

![image](https://user-images.githubusercontent.com/2325589/108059575-a3554800-704d-11eb-9e2a-f32cbfc679f2.png)

It should be noted here that there is an empty line on top of the result.
What I think is: since there is an empty line, if `lsp-eldoc-render-all` is disabled, then it displays the newline instead of the function signature (I may be wrong about this).

**To Reproduce**
Disable `lsp-eldoc-render-all` and open a Rust project with `lsp-mode` enabled with `rust-analyzer`.

**Expected behavior**
Signature should appear in a single line, giving information for the user.

**Which Language Server did you use**
I did use `lsp-rust` with `rust-analyzer`.

**OS**
GNU/Linux

Feel free to change the title to something more fitting.

**Comment by yyoncho** [comment] 2021-02-19 18:51
I will take a look.

**Comment by yyoncho** [comment] 2021-02-19 19:25
There are 2 options: trim and take the first line which is easy to implement. The other option is to take everything till the horizontal line which will be harder to implement and will break when rust-analyzer changes their format.

**Comment by yyoncho** [comment] 2021-02-19 19:29
I implemented first option in https://github.com/emacs-lsp/lsp-mode/pull/2627 .

**Comment by RomeuG** [comment] 2021-02-19 19:36
Ok great. Any way of testing this now or should I wait for it to be pushed?

**Comment by yyoncho** [comment] 2021-02-19 19:38
Just eval this:

``` emacs-lisp
(cl-defgeneric lsp-clients-extract-signature-on-hover (contents _server-id)
  "Extract a representative line from CONTENTS, to show in the echo area."
  (car (s-lines (s-trim (lsp--render-element contents)))))
```

**Comment by RomeuG** [comment] 2021-02-19 19:47
Thanks! I confirm that it works!

**Comment by RomeuG** [comment] 2021-02-19 19:56
Although that solves the issue, it solves it partially. I say this because having `lsp-eldoc-render-all` as `t`, this is shown:

![image](https://user-images.githubusercontent.com/2325589/108554641-46c38880-72ec-11eb-81dd-1cb8754dbb6c.png)

It shows the return type and the function signature.

Having `lsp-eldoc-render-all` as `nil`, only the variable type I am working on is shown:

![image](https://user-images.githubusercontent.com/2325589/108554797-85f1d980-72ec-11eb-9ccb-980646ea1645.png)

Sorry if this is something specific to `rust-analyzer`. Just making sure of it.

**Comment by yyoncho** [comment] 2021-02-19 20:02
Yep, this is what I was describing. The issue is that rust analyzer returns markdown and its structure is not fixed. Thus we have to write custom logic to extract that first section. This is point 2 in my previous post. The question is whether the proposed PR is useful as is, or better to go with custom extracting?

**Comment by RomeuG** [comment] 2021-02-19 20:39
Yes! Sorry for my misinterpretation.

Well, I guess the goal of this feature is to actually show the function signature (correct me if I am wrong).
The proposed PR is obviously an upgrade from before, no doubt. But I would say that custom extracting would actually achieve what is needed from the feature.

But you obviously raise a good point: `rust-analyzer` could have future breaking changes related to that, and then there would be the need to change, once again, how you extract the information.

Honestly, I do not know the best course of action. I guess you can decide what is the best way of dealing with this.

**Comment by yyoncho** [comment] 2021-03-01 19:10
I merged it as it is, later we can improve futher.

**Closed** 2021-03-01 19:10 UTC

**Comment by RomeuG** [comment] 2021-03-01 19:30
Sure, thanks!

**Comment by restfuladi** [comment] 2022-03-06 18:56
Would it be possible to extract the line showing the actual signature?
