### ISSUE TITLE
Add ability to jump back and forward, i.e. location stack navigation

### ISSUE THREAD

**Issue by JohnC32** [emacs-lsp/lsp-mode#1102] opened 2019-10-16 00:33 UTC
Many code navigation packages have ability to "jump back" to where you were and "jump forward", i.e. a location navigation system. For example if you do M-x lsp-find-references and click around, you should be able to jump back to your staring point. The alternative to a formal location navigation system is to simply switch buffers to get back but it's not so friendly as it's easy to forget buffer names, etc. Having a formal location navigation system where you can jump back and forward is a very nice capability that quickly becomes a key time savings feature. 

A good implementation of this is in https://github.com/Andersbakken/rtags. They have two functions 'rtags-location-stack-back and 'rtags-location-stack-forward. Could you add something similar?

Thanks

**Comment by yyoncho** [comment] 2019-10-16 04:56
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/1034

**Closed by yyoncho** 2019-10-16 04:56 UTC
