### ISSUE TITLE
LSP: eval:evalCommand not implemented?

### ISSUE THREAD

**Issue by rubenmoor** [emacs-lsp/lsp-mode#2527] opened 2021-01-15 03:41 UTC
I type

```
{-
>>> foo
-}
```

And there appears

```evaluate```

If I click on it, I get the message

```
LSP :: Please open an issue in lsp-mode for implementing `12876:eval:evalCommand'.

```

EDIT: this is using `lsp-haskell`/`haskell-langauge-server`.

**Comment by kiennq** [comment] 2021-01-15 07:45
Which language server are you using?
That error means the language server and its client code doesn't support the extension method of `eval:evalCommand` and need to be implemented in client side

**Comment by michaelpj** [comment] 2021-01-15 12:03
I suspect this might be the haskell language server. We had a previous report of this which led to me opening https://github.com/emacs-lsp/lsp-mode/issues/2250.

**Comment by rubenmoor** [comment] 2021-01-15 14:43
Yes, `haskell-language-server` (updated my original post). I will inquire there. I guess, the error message might deserve an update in that case.

**Comment by yyoncho** [comment] 2021-01-15 15:11
Closing as duplicate of #2250

**Closed** 2021-01-15 15:11 UTC
Labels: need-info
