### ISSUE TITLE
Running LSP for multiple languages breaks flycheck.

### ISSUE THREAD

**Issue by JordanAnthonyKing** [emacs-lsp/lsp-mode#2117] opened 2020-08-26 20:27 UTC
_I have recreated this bug in a completely clean install of emacs 27.1 with the versions of lsp-mode and flycheck available on MELPA as of 26/10/20. I initially spotted this bug in Doom emacs_

**Describe the bug**
Running `lsp-mode` for a new language will cause flycheck to stop working in buffers running lsp-mode for other languages.

Related: lsp's diagnostics are only shared across major-modes, not projects. This behaviour can be seen in the screenshot below.

**To Reproduce**
Open a file supported by lsp-mode in a buffer (for example a .js file). Now open another file in a new buffer (say a .html file). Run `lsp-mode` in either buffer. Switch to the other buffer and activate `lsp-mode` for it too. Switch back to the previous buffer, flycheck functions  such as `flycheck-next-error` will now no longer work. Diagnostics will still be accurate.

Here is a screenshot of a fresh emacs install. I have manually installed and left completely default `lsp-mode` `flycheck` `tide`. Please note the cursor position, I have deleted a closing brace causing spurious errors beneath it. These errors are shown by lsp's diagnostics but running `flycheck-next-error` gives "No more flycheck errors". Also note the buffer on the right hand side, same project, different major-mode, lsp-diagnostics do not factor in those of the other buffer. I have verified (in Doom Emacs) that this behavious is based on major-mode not language server by recreating the bug with ng2-ts and typescript-mode.

![image](https://user-images.githubusercontent.com/58787893/91352612-9b70c580-e7d9-11ea-94a2-7a79fe2aebab.png)

**Expected behavior**
LSP should support running multiple language servers within a project with no effect on flycheck or lsp-diagnostics.

**Which Language Server did you use**
I expect this issue to occur with all language servers but have verified it to occur for any combination of `ts-ls` `angular-ls` `html-ls` and `css-ls`.

**OS**
I am running Emacs on Ubuntu 20.04, under WSL2, through an X-Server.

**Error callstack**
Unfortunately as far as I am aware no errors are given by lsp, the language servers, or flycheck.

**Comment by yyoncho** [comment] 2020-08-27 05:49
The issue here is caused by `flycheck` disabling lsp-mode flychecker for some reason. You may verify that by doing M-x flycheck-verify-setup in the first buffer after you open the second file flycheck will disable lsp-mode flychecker in the first one. At this point, I am not sure whos fault is that. Closing and reopening the buffer fixes the issue. 

(cc @cpitclaudel )

**Comment by yyoncho** [comment] 2020-08-27 07:04
Ok, I found the issue, it is in lsp-mode. I will do a fix later today.

**Comment by JordanAnthonyKing** [comment] 2020-08-27 08:19
@yyoncho Brilliant! This has been driving me up the wall for the last week and was surprised noone else had reported it.

**Comment by yyoncho** [comment] 2020-08-27 15:17
> @yyoncho Brilliant! This has been driving me up the wall for the last week and
> was surprised noone else had reported it.

I think that it is fairly recent regression. I have saw it few times, but I was unable to narrow down what is causing it.

**Comment by yyoncho** [comment] 2020-08-27 15:20
proposed fix at #2119

**Closed** 2020-08-27 15:47 UTC
