### ISSUE TITLE
When and how does lsp mode update reported errors?

### ISSUE THREAD

**Issue by intrasight** [emacs-lsp/lsp-mode#2492] opened 2020-12-31 15:38 UTC
Now that I sort of having lsp mode setup, I'm editing some files. C# in my case.
I purposely introduce an error by calling a function that doesn't exists in
the project. Then I edit another file and add the missing function. I would expect
that the UI is updated to remove the error but it does not. 

Perhaps similar to
[https://github.com/emacs-lsp/lsp-mode/issues/1792](https://github.com/emacs-lsp/lsp-mode/issues/1792)

**Comment by ericdallo** [comment] 2020-12-31 15:41
It seems that the server is not returning new diagnostics regarding the old file that have the errors, it's responsibility of the server to warn the client (lsp-mode) about these changes.

**Comment by intrasight** [comment] 2020-12-31 15:50
In my case I am using omnisharp
Is there a command that I can run interactively to force lsp to resync with the server? Or on file save?

**Comment by ericdallo** [comment] 2020-12-31 15:54
It depends on how the server will behave for that, for clojure-lsp for example, just saving the buffer will do the trick

**Comment by yyoncho** [comment] 2020-12-31 15:54
You can force sync by doing M-x flycheck-buffer or you may try adding idle-buffer-switch to flycheck-check-syntax-automatically

**Comment by intrasight** [comment] 2020-12-31 16:00
I get [No match] when I do M-x flycheck-buffer

**Comment by nbfalcon** [comment] 2020-12-31 16:41
@intrasight do you have `flycheck` installed and loaded?

**Comment by intrasight** [comment] 2020-12-31 16:51
I do now. I had assumed it was loaded as a dependency. What does flycheck add to the situation?

I can now run M-x flycheck-buffer, but the error notification is still there. 
If I close and open the buffer, the error notification is still present.
If I restart emacs and load the buffer, the error notification is gone.

**Comment by yyoncho** [comment] 2020-12-31 16:55
So, seems like the issue is that the server does not actually send a notification that the diagnostic is cleared. @sebasmonia and @razzmatazz might know what the reason is.

**Comment by intrasight** [comment] 2020-12-31 17:23
I found this: 

https://stackoverflow.com/questions/56186264/vscode-omnisharp-not-working-for-solution-but-works-for-project

And this:

https://www.reddit.com/r/emacs/comments/adxcal/subprojects_do_i_need_to_armwrestle_projectile_or/

Trying to figure out how the pieces fit together  - multiple projects in a "solution". I'll keep experimenting, but if anyone has figured out omnisharp solution semantics with LSP, I'd be grateful for pointers.

**Comment by sebasmonia** [comment] 2021-01-02 05:23
Hi everyone,

In my experience the errors don't go away until you re-open the file. I never bothered to fix it because I tend to compile often so in a similar situation (I setup function/method usage, and then start working on the code) once compilation reports no errors I'm OK.

You can try cleaning the solution before compiling too, @intrasight. Does that help?

**Comment by razzmatazz** [comment] 2021-01-02 11:10
To add to @sebasmonia, sometimes forcingly-saving on one of the files clears diagnostics too. This needs more investigation on behalf of `omnisharp-roslyn` language server protocol and I don't think it is an issue of `lsp-mode` -- rather an issue with `omnisharp-roslyn` IMHO.

**Comment by intrasight** [comment] 2021-01-02 21:53
Not sure if it makes any difference, but I should ask. I'm not using omnisharp-roslyn. Rather, since I have VS Code and Omnisharp installed, I just set lsp-csharp-server-path to the OnmiSharp.exe and confirmed that it was indeed the most current version. 

> You can try cleaning the solution

I think this is my main area of misunderstanding. Visual Studio has the concept of a "solution", but I don't see where to find solution level semantics in lsp-mode or projectile

**Comment by razzmatazz** [comment] 2021-01-03 08:46
> Not sure if it makes any difference, but I should ask. I'm not using omnisharp-roslyn. Rather, since I have VS Code and Omnisharp installed, I just set lsp-csharp-server-path to the OnmiSharp.exe and confirmed that it was indeed the most current version.

Just to confirm -- do you know that lsp-mode can install omnisharp for you (i.e. there is no need to set `lsp-csharp-server-path`)? -- just use `M-x lsp-csharp-update-server`. (Eventually we will move this functionality to the standard `lsp-install-server` infrastructure).

> 
> > You can try cleaning the solution
> 
> I think this is my main area of misunderstanding. Visual Studio has the concept of a "solution", but I don't see where to find solution level semantics in lsp-mode or projectile

By "cleaning solution" he probably mean trying to do `dotnet clean` from the shell/ or clean solution w/ visual studio tools.

W.r.t. to solution/vs project semantics -- omnisharp-roslyn (the server) does support loading specific solution file when starting via params but ATM we're passing the root of the project (from `projectile` or `project`) by default -- so it loads ALL the .csproj it finds in the subtree (although I am not 100% but I think it works like this).

Adding a way to require user to specify a specific .sln file if more than one found is something of a TODO item ATM, I guess.

**Comment by razzmatazz** [comment] 2021-01-03 08:52
Btw, can you dump a `tree` of your solution (.sln/.csproj files -- sans actual .cs filenames) -- so we can get an idea what is your project structure.

Also I would recommend creating a test solution w/1 project to see if omnisharp is working for you in the simplest case -- i.e. something like:
- Solution (dir)
  - .git (or some other project marker for `projectile` to match on)
  - Solution.sln
  - ProjectA (dir)
    - ProjectA.csproj
    - ClassA.cs
    - ClassB.cs

This layout is definitely supported and IIRC modifying `ClassA.cs` when I have `ClassB.cs` open does clean flycheck errors for me in the buffer for `ClassB.c` too.

Lets start from this simplest case and check where things break.

**Comment by intrasight** [comment] 2021-01-03 17:08
@razzmatazz 
I did know that lsp-mode can install omnisharp for me. But like I said, it was already installed via VSCode extension and so I used that exe. would the omnisharp-roslyn version behave differently in lsp-mode perhaps? Should I try and compare?

I am using .net core 5 for my tests

My test with a single project (like you outlined) is working fine. It's when I add a dependency to a second project that I'm finding that I need to restart emacs before modifications to the second project are reflected in the first.

**Comment by razzmatazz** [comment] 2021-01-04 20:24
> @razzmatazz
> I did know that lsp-mode can install omnisharp for me. But like I said, it was already installed via VSCode extension and so I used that exe. would the omnisharp-roslyn version behave differently in lsp-mode perhaps? Should I try and compare?

You *should* get the same behaviour, unless your version of OmniSharp.exe is older from VSCode. I believe we're using the same distro .zip on Windows as VSCode does. `lsp-csharp-update-server` would ensure you have the latest though.

> 
> I am using .net core 5 for my tests
> 
> My test with a single project (like you outlined) is working fine. It's when I add a dependency to a second project that I'm finding that I need to restart emacs before modifications to the second project are reflected in the first.

I can confirm I get this behaviour when using omnisharp w/lsp-mode while it does work properly when using VSCode -- i.e. notifications about cleared diagnostics is not issued to open files.

I did notice that if you move focus/cursor to the buffer that has diagnostics displayed (when you have two emacs `windows` open side to side) -- then it does clear/update diagnostics on the file when you switch to it. So I *guess* at the time focus moves to a buffer `lsp-mode` does inform the server to recheck(?) diagnostics. Can @yyoncho confirm this? I am not well-versed in LSP semantics to know this.

Anyway here is a small video of this buggy(?) behaviour @intrasight has reported that I think I have properly replicated:

https://user-images.githubusercontent.com/563556/103576218-799bf380-4edb-11eb-9a56-745d57b3fff7.mov

**Comment by yyoncho** [comment] 2021-01-04 20:38
@razzmatazz we do not call the server, the server is sending us notifications. You can force redisplaying diagnostics via M-x flycheck-buffer(that won't call the server) or you may try adding idle-buffer-switch to flycheck-check-syntax-automatically

**Comment by razzmatazz** [comment] 2021-01-04 20:47
@yyoncho if I understand you properly, you're saying that in this case it does seem that the server *did* send updated diagnostics for `Program.cs` file in time -- when I was updating/fixing/saving `Class1.cs` -- it is just that flycheck has cared to update the diagnostics+marker for the other buffer (`Program.cs`) only when I actually switched the focus to it, right? 

And thus this issue is jus ta matter of configuring the value of `flycheck-check-syntax-automatically` to your taste? (My current value is `(save idle-change mode-enabled)`.

**Comment by yyoncho** [comment] 2021-01-04 20:51
@razzmatazz it is not flycheck, it is lsp-mode... We had a lot of trouble with `find-buffer-visiting` performance, thus we update diagnostics only for the current buffer. Thus it is a limitation. But I think that @intrasight has a different issue, the diagnostics are not received till they restarts the buffer, right? But if M-x flycheck-buffer is refreshing the diagnostics, then the issue is not really related to omnisharp.

**Comment by sebasmonia** [comment] 2021-01-05 05:49
FWIW I use Flymake, not Flycheck.
Trying a minimal example of Program.cs calling a method on Whatever.cs, I only get updates in the diagnostics after modifying the buffers (not necessarily saving them).

But I know for larger, multi-project solutions, sometimes the only way to get updated diagnostics is to build the solution and then editing the buffers. And even that is not 100% reliable. (But like I said, since I tend to recompile often...I don't pay attention to diagnostics that much)

**Comment by yyoncho** [comment] 2021-10-16 08:37
closing since it seems like there is nothing to do here, please reopen if you disagree.

**Closed by yyoncho** 2021-10-16 08:37 UTC
