### ISSUE TITLE
lsp-mode overrides existing Imenu customisation group

### ISSUE THREAD

**Issue by ivan-m** [emacs-lsp/lsp-mode#1320] opened 2020-01-16 07:47 UTC
**Describe the bug**

If I try and customize Imenu settings using `M-x customize-group imenu` I'm presented only with lsp-related options, not the standard Imenu customisations.

I think this is because of how the `lsp-imenu` group is defined:

```elisp
(defgroup lsp-imenu nil
  "Imenu."
  :group 'lsp-mode
  :tag "Imenu")
```

Maybe instead it should be:

```elisp
(defgroup lsp-imenu nil
  "Imenu integration for lsp-mode."
  :group 'lsp-mode
  :group 'imenu)
```

**To Reproduce**
With `lsp-mode` loaded, try `M-x customize-group imenu`

**Expected behavior**
I see standard Imenu options: "Imenu After Jump Hook", "Imenu AUto Rescan", etc.

**Which Language Server did you use**
lsp-haskell

**OS**
Red Hat 7 running in a VM on Windows 7.

**Comment by yyoncho** [comment] 2020-01-26 14:09
I am unable to reproduce. Which emacs version do you use?

**Comment by yyoncho** [comment] 2020-02-07 06:59
Any update?

**Comment by ivan-m** [comment] 2020-02-12 09:53
Sorry for the delay.  I can no longer replicate this issue, so it might have been a temporary glitch.

The only thing I've noticed is that if I do `M-x customize-group imenu` and then `M-x customize-group lsp-imenu`, I'm still shown the first imenu customization buffer.  If I kill that then do `M-x customize-group lsp-imenu` then I get shown the LSP-specific customizations.

(Maybe because the buffers have the same name? So maybe this was what was really happening to me and I didn't think about the buffer having the same name and thus failing to open/show the correct one?)

**Comment by yyoncho** [comment] 2020-02-12 16:39
What you are describing is not related to lsp-mode but it seems like emacs behaviour - I am not sure what is the logic behind that. emacs-devel mailing list is the proper place to ask that question. 

Closing based on the previous comment.

**Closed by yyoncho** 2020-02-12 16:39 UTC
Labels: Unable to reproduce, good-first-issue, need-info
