### ISSUE TITLE
lsp-show-xrefs doesn't push markers

### ISSUE THREAD

**Issue by vspinu** [emacs-lsp/lsp-mode#1055] opened 2019-10-01 14:50 UTC
`lsp-show-xrefs` doesn't push markers, contrary to the plain `xref--show-xrefs`. 

Markers are needed to return to the invocation location with `xref-pop-marker-stack`. 

This is lsp mode lsp-mode-20190930.503 from MELPA on emacs 27.

**Comment by yyoncho** [comment] 2019-10-01 15:24
Duplicate of https://github.com/emacs-lsp/lsp-mode/issues/1034

**Closed** 2019-10-01 15:24 UTC
