### ISSUE TITLE
Bad gopls completion reordering

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#2195] opened 2020-09-19 17:33 UTC
lsp-mode seems to be rearranging the completion candidate order from gopls. In below screenshot, `foo.str` should be the first candidate. It is of type `string`, so it matches the assignment well.
![Screen Shot 2020-09-19 at 10 24 41 AM](https://user-images.githubusercontent.com/11356572/93680171-7f6fe500-fa62-11ea-88c5-afaed68cbb1c.png)

<details>
<summary>
Candidates
</summary>

    [Trace - 10:24:27 AM] Received response 'textDocument/completion - (10408)' in 6ms.
    Result: {
      "items": [
        {
          "textEdit": {
            "newText": "foo.str",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "foo.str",
          "sortText": "00000",
          "preselect": true,
          "detail": "string",
          "kind": 5,
          "label": "foo.str"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"path/filepath\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "filepath.Base(${1:path string})",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "filepath.Base",
          "sortText": "00001",
          "detail": "func(path string) string (from \"path/filepath\")",
          "kind": 3,
          "label": "filepath.Base"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"path/filepath\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "filepath.Clean(${1:path string})",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "filepath.Clean",
          "sortText": "00002",
          "detail": "func(path string) string (from \"path/filepath\")",
          "kind": 3,
          "label": "filepath.Clean"
        },
        {
          "textEdit": {
            "newText": "foo",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "foo",
          "sortText": "00003",
          "detail": "struct{...}",
          "kind": 6,
          "label": "foo"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"path/filepath\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "filepath",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "filepath",
          "sortText": "00004",
          "detail": "\"path/filepath\"",
          "kind": 9,
          "label": "filepath"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"compress/flate\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "flate",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "flate",
          "sortText": "00005",
          "detail": "\"compress/flate\"",
          "kind": 9,
          "label": "flate"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"fmt\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "fmt",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "fmt",
          "sortText": "00006",
          "detail": "\"fmt\"",
          "kind": 9,
          "label": "fmt"
        },
        {
          "textEdit": {
            "newText": "false",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "false",
          "sortText": "00007",
          "kind": 21,
          "label": "false"
        },
        {
          "textEdit": {
            "newText": "float32",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "float32",
          "sortText": "00008",
          "kind": 7,
          "label": "float32"
        },
        {
          "textEdit": {
            "newText": "float64",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "float64",
          "sortText": "00009",
          "kind": 7,
          "label": "float64"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"golang.org/x/tools/internal/fastwalk\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "fastwalk",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "fastwalk",
          "sortText": "00010",
          "detail": "\"golang.org/x/tools/internal/fastwalk\"",
          "kind": 9,
          "label": "fastwalk"
        },
        {
          "additionalTextEdits": [
            {
              "newText": "\nimport \"internal/fmtsort\"\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 1
                },
                "start": {
                  "character": 0,
                  "line": 1
                }
              }
            }
          ],
          "textEdit": {
            "newText": "fmtsort",
            "range": {
              "end": {
                "character": 17,
                "line": 4
              },
              "start": {
                "character": 16,
                "line": 4
              }
            }
          },
          "insertTextFormat": 2,
          "filterText": "fmtsort",
          "sortText": "00011",
          "detail": "\"internal/fmtsort\"",
          "kind": 9,
          "label": "fmtsort"
        }
      ],
      "isIncomplete": true
    }    

</details>

VSCode keeps the proper order:
![Screen Shot 2020-09-19 at 10 32 07 AM](https://user-images.githubusercontent.com/11356572/93682187-661b6880-fa63-11ea-88d4-7e66443ad4e9.png)

**Comment by kiennq** [comment] 2020-09-20 12:46
I can't seem to reproduce this problem
![image](https://user-images.githubusercontent.com/2631472/93711550-40d54a00-fb8a-11ea-9aae-d796d4404377.png)

Are you using `company-statistics-mode`?

**Comment by psanford** [comment] 2020-09-20 15:28
I upgraded lsp-mode this morning and now I'm seeing this issue as well. I'm not using `company-statistics-mode`.

**Comment by psanford** [comment] 2020-09-20 15:38
It looks like the suggestions are just sorted by string length right now:

![image](https://user-images.githubusercontent.com/33375/93715124-2e242c00-fb1c-11ea-8c7b-92762565cd7f.png)

**Comment by muirdm** [comment] 2020-09-20 16:54
This seems to be caused by `lsp-completion-sort-initial-results` (and `lsp-completion-filter-on-incomplete`). gopls does fuzzy filtering server side, and gopls orders completion candidates intelligently, so the lsp client should not change the order.

I don't really understand all the filtering/sorting lsp-mode does. #1661 seems to allow sorting if `sortText` is present in the response, but AFAIK gopls puts the sortText to try to _stop_ the client for changing the order of completion items. If sortText is present, don't you want to use that to sort? (I don't care what VSCode does - it has a lot of similar filtering/sort issues that caused a lot of problems for gopls trying to intelligently order completion candidates).

@kiennq why does lsp-mode default to changing the order of completion results? That seems to assume the server is "stupid", giving only an unordered list of all possible completions.

**Comment by muirdm** [comment] 2020-09-20 17:01
At the very least, whether to sort/filter needs to be a property of the language server, not a global config setting. lsp clients should not sort (and probably not filter) gopls completion results.

**Comment by yyoncho** [comment] 2020-09-20 17:21
@muirdm 

> At the very least, whether to sort/filter needs to be a property of the language server, not a global config setting. lsp clients should not sort (and probably not filter) gopls completion results.

You can have dir local for that or use the `lsp-gopls-after-open-hook` hook to turn that on.

> If sortText is present, don't you want to use that to sort? 

We should sort using sortText. Then we should perform stable sort again using the prefix match score. I think that the first one is not happening but @kiennq has to confirm. The issue here is that the prefix score overtakes the sortText even if the score of each item is the same.

**Comment by kiennq** [comment] 2020-09-21 01:46
> The issue here is that the prefix score overtakes the sortText even if the score of each item is the same.

The score of each item is not the same. With our current fuzzy score algorithm, short string will be boosted more since it's match ratio is better than the longer one. Well, this heuristic and hard to change. And I don't think we should faithfully try to reimplement VsCode algorithm in `lsp-code` using Elisp, JavaScript runtime is actually better than Elisp, we will stumbled in perf problem if we're doing that. 

@muirdm @psanford 
And as I said before, I cannot seem to repro this. At least on `golang.org/x/tools/gopls 0.4.3`. 
However, this problem does occur on `golang.org/x/tools/gopls@v0.5.0`.

The issue here is because in the former one , the `filterText` is the same for every completion items, and that make our re-sorting for fuzzy useless, since all the items have the same score. The sort is stable so the correct order is showing as in https://github.com/emacs-lsp/lsp-mode/issues/2195#issuecomment-695783305.

The latest version (0.5.0) however put different `filterText` for each item, and that make we reordering the candidates.
And here is the commit which's doing that https://github.com/golang/tools/commit/b2d8b03366329f6cb0ff15138a7732def14679a7#diff-4f76f1e205dd09c758df98edb416d93b.

We can follow their step and put the same logic inside `lsp-go` or we can doing simpler with `(setq-local lsp-completion-filter-on-incomplete nil)` inside `:after-open-fn` of `lsp-go` client registration, which will benefit all user of `lsp-go`.

For current user who just want to quick fix / customize on their own, setting inside `lsp-go-after-open-hook` is enough.

**Comment by muirdm** [comment] 2020-09-21 14:45
@kiennq Thanks for the fix.

Are there other servers that order their completion results and would want similar treatment in lsp-mode?

**Comment by yyoncho** [comment] 2020-09-21 15:03
> The score of each item is not the same. With our current fuzzy score algorithm, short string will be boosted more since it's match ratio is better than the longer one. Well, this heuristic and hard to change. And I don't think we should faithfully try to reimplement VsCode algorithm in `lsp-code` using Elisp, JavaScript runtime is actually better than Elisp, we will stumbled in perf problem if we're doing that.

Sooner or later we should fix that. Without benchmarks, it is unclear if it will be slow or not. And if it is slow we can build a dynamic module, or write C implementation as part of gnu emacs with the expected behavior. 

I consider #2198 as a temporary workaround that will work only with servers that return incomplete results. You know that there are servers that will return complete result and then the fuzzy filtering will kick in and we will have the same issue.

**Comment by yyoncho** [comment] 2020-09-22 10:33
@kiennq I see also this with jdtls: 

![image](https://user-images.githubusercontent.com/13259670/93871857-fbbf2e00-fcd7-11ea-90ed-0fb3e09855d1.png)

Is the length of the item pushing `asSubclass` down on the list?

**Comment by kiennq** [comment] 2020-09-22 15:59
Yes, I think so.
``` elisp
(lsp-completion--fuz-score "as" "hashCode() : int")
0.10416666666666667

(lsp-completion--fuz-score "as" "asSubclass(Class<U> clazz) : Class<? extends U>")
0.0425531914893617
```

**Comment by muirdm** [comment] 2020-09-22 17:06
Why is an exact prefix scoring lower than a random-middle-of-word match? The length of the candidate is not really material to how well it matches.

**Comment by kiennq** [comment] 2020-09-25 11:34
> Why is an exact prefix scoring lower than a random-middle-of-word match? The length of the candidate is not really material to how well it matches.

I'm using simple score algorithm similar to `flex-score` (in `completion-pcm--hilit-commonality`), which normalize the score by length, thus favor the word that's shorter.

We can try remove that and see if the experience improves.

**Comment by yyoncho** [comment] 2020-10-02 17:21
This one was fixed by @kiennq

**Closed** 2020-10-02 17:21 UTC
Labels: completion
