### ISSUE TITLE
gopls type documentation not color formated

### ISSUE THREAD

**Issue by numkem** [emacs-lsp/lsp-mode#757] opened 2019-04-10 01:53 UTC
**Describe the bug**
Switching from current master of bingo vs current master of gopls shows that the signature help on the right side when hovering over something isn't color coded when using gopls. With bingo it looks just fine.

Ex: https://imgur.com/mQSMYCw

**To Reproduce**
Install the bingo branch of gopls from github.com/saibing/tools/cmd/gopls

**Expected behavior**
Color coded output using the same colors as bingo

**Which Language Server did you use**
golang using gopls lsp server.

**OS**
Linux Debian testing.

**Comment by yyoncho** [comment] 2019-04-10 04:04
Duplicate of https://github.com/emacs-lsp/lsp-ui/issues/220 . I am working on a solution now.

**Closed by yyoncho** 2019-04-10 04:04 UTC
