### ISSUE TITLE
lsp-mode.elc failed to define function 

### ISSUE THREAD

**Issue by tfighting** [emacs-lsp/lsp-mode#1401] opened 2020-02-09 13:34 UTC
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode
When I use "lsp-describe-thing-at-point" command, a mistake always occurs.The below code display some information.
`command-execute: Autoloading file /home/t_fighting/.emacs.d/elpa/lsp-mode-20200208.1522/lsp-mode.elc failed to define function lsp--describe-thing-at-point`.
Who can tell me why the error happens?

**Comment by yyoncho** [comment] 2020-02-09 16:09
I am closing the issue since this string is not mentioned in emacs-lsp org:

https://github.com/search?q=org%3Aemacs-lsp+lsp--describe-thing-at-point&unscoped_q=lsp--describe-thing-at-point

I suggest you to delete your emacs.d/elpa directory to force downloading the latest lsp-mode(and related) version. 

Before reopening the bug please make sure that it reproduces with `emacs -q -l lsp-start-plain.el`.

**Closed by yyoncho** 2020-02-09 16:09 UTC

**Comment by alarya** [comment] 2022-12-02 19:57
Deleting the emacs.d dir did work, however, is quite inconvenient. I tried to `byte-force-recompile` the emacs.d dir and that worked for me.
