### ISSUE TITLE
[Spacemacs.develop][lsp-go] Autocompletion quirk, "run-on" completion

### ISSUE THREAD

**Issue by dennismayr** [emacs-lsp/lsp-mode#872] opened 2019-06-05 20:36 UTC
Autocomplete chooses the expected word, but doesn't insert it properly.
![Drop-down](https://imgur.com/xKBMZgo.png)
![Completion quirk](https://imgur.com/Y2e9q52.png)

**To Reproduce**

- Use the `lsp` backend for **Go** instead of `go-mode` in Spacemacs:
```emacs-lisp
(go :variables
         go-backend 'lsp
```
- Type a word to autocomplete
- Select the word and tap `return` to enter it

**Expected behavior**
After typing 2 letters, the word is suggested, and when chosen, the word is inserted and replaces the characters typed to get the drop-down suggestion box.

**What happens**
The word gets inserted mixed with the previously typed characters.

Note: this _only_ happens in `lsp` for **Go**; `lsp` for other major modes doesn't exhibit this behavior.

**Which Language Server did you use**
`gopls` backend for `lsp-go`

**OS**
elementaryOS 5.0 Juno (Ubuntu 18.04-based)
Emacs 26.1

**Comment by yyoncho** [comment] 2019-06-05 20:49
Can you list the versions of lsp-mode and company-lsp?

**Comment by dennismayr** [comment] 2019-06-05 20:52
Sure thing.

`lsp-mode-20190605.1330`
`company-lsp-20190525.207`

**Comment by yyoncho** [comment] 2019-06-06 03:25
I am unable to reproduce the issue using spacemacs or `lsp-start-plain.el`, can you try upgrading the gopls server? If the issue is still there can you set lsp-print-io to `t` and paste the client-server communication?

**Comment by dennismayr** [comment] 2019-06-08 18:29
Sure thing.

`gopls` is up-to-date (just pulled it, Sat - june 8 2019 @ 13:50 GMT -3).

I've noticed something:
If you type `f`-TAB to get autocompletion suggestions expecting to show `fmt` as result, those will be suggested in `helm` minibuffer; that way, you can choose `fmt`, the standard _I/O format_ module.

If you go on and after choosing `fmt`, you autocomplete, say, to `fmt.Println(a ...interface{})` and leave those default snippet values as-is, the `fm`->`fmfmt` autocompletion quirk occurs.

Even further: if you left `fmt.Println(a ...interface{})` unchanged, any line after it won't have contextual suggestions in place, like if an error in a line broke autocompletion from that point onwards, as shown below:

![imgur](https://imgur.com/PxFSEWJ.png)
![imgur](https://imgur.com/ekD3Jcj.png)
![imgur](https://imgur.com/PktoKtx.png)
![imgur](https://imgur.com/XnZJs1U.png)
 
`lsp-print-io t` is set; _client-server_ communication shows the following in *lsp-log: gopls* buffer (quite a long stream of text):

[Pastebin](https://pastebin.com/Pj2TK4wR)

Let me know how else I can help debugging this.
If it's a _Spacemacs_ problem, I'll take this issue over there.

**Comment by yyoncho** [comment] 2019-06-08 18:39
Is it possible that you are using tng company frontend? It does not work quite well with lsp-mode. Also, is it possible for you to share your .spacemacs configuration? Or at least the layers + the company/lsp related configuration?

**Comment by dennismayr** [comment] 2019-06-08 18:55
[My current _Spacemacs_ dotfile](https://pastebin.com/aG6yeYq7)

[Spacemacs.develop Golang layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/go)

**Comment by yyoncho** [comment] 2019-06-09 15:28
I managed to repro your issue. First thing is that completion-at-point does not support snippets, this is tracked in https://github.com/emacs-lsp/lsp-mode/issues/350 . If you want to use snippets you should use company-lsp. Then after you enter the snippet it seems like the gopls server is starting to return wrong completions for fmt prefix.

Consider the following snippet:

``` go
package main
import "fmt"
func main() {
	// fmt.Errorf(format string, a ...interface{})
f
}
```

Notice that gopls is returning different textEdit depending on whether the line containing fmt.Errorf is commented or uncommented. Here are the 2 textEdits(separated with ---)

``` json
    {
      "textEdit": {
        "newText": "fmt",
        "range": {
          "end": {
            "character": 1,
            "line": 6
          },
          "start": {
            "character": 1,
            "line": 6
          }
        }
      },
      "insertTextFormat": 2,
      "filterText": "fmt",
      "sortText": "00000",
      "preselect": true,
      "detail": "\"fmt\"",
      "kind": 9,
      "label": "fmt"
    },
--------------------------------------------------------------------------------------------
    {
      "textEdit": {
        "newText": "fmt",
        "range": {
          "end": {
            "character": 1,
            "line": 6
          },
          "start": {
            "character": 0,
            "line": 6
          }
        }
      },
      "insertTextFormat": 2,
      "filterText": "fmt",
      "sortText": "00000",
      "preselect": true,
      "detail": "\"fmt\"",
      "kind": 9,
      "label": "fmt"
    },
```

I am closing the issue based on:

1. completion-at-point issue is tracked by #350 
2. The fmt related issue should be addressed on the server. 

(CC @muirrn @stamblerre )

**Comment by dennismayr** [comment] 2019-06-09 20:06
At least we now know where the problem resides :smile: 
Thanks for the assistance; I'll stick to `go-mode` for the time being, while keeping an eye on this.
LSP has made my workflow much better in general.

**Comment by muirrn** [comment] 2019-06-09 21:10
Gopls can't detect the "f" prefix properly due to the syntax error on the previous line. The "f" is not parsed as an identifier, so gopls falls back to assuming there is no prefix. There are many other similar cases where gopls doesn't work due to surrounding/preceding syntax errors. It is a tough problem to solve in general, but in this particular case it seems like we could "manually" detect the enclosing identifier. I created https://github.com/golang/go/issues/32510 to track this issue upstream.

**Comment by dennismayr** [comment] 2019-06-09 23:36
Excellent!

`go` language servers are going a long way (pun not intended); `gopls` still is the best option, looking back to other projects.

The _"silver lining"_ of this problem is that is if autocompletion fails, it means that there's an error on the line above, and it needs immediate attention.

**Closed** 2019-06-10 06:51 UTC
Labels: Unable to reproduce
